import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { sha256 } from '../src/active-work-state.js';
import { GitHubReceiptConsumingCasWriter, GitHubProductionMutationError, GITHUB_PRODUCTION_MUTATION_PLAN_PROTOCOL, GITHUB_PRODUCTION_MUTATION_GRANT_PROTOCOL, productionMutationGrantDigest, productionMutationPlanDigest } from '../src/github-production-mutation.js';
import { GitHubSystemFileLeaseCoordinator, GitHubSystemFileLeaseError, SYSTEM_FILE_LEASE_STATE_REF, systemFileLeaseEventPath, systemFileLeaseRecordPath } from '../src/github-system-file-lease.js';
const sha = (c) => c.repeat(40), MAIN=sha('a'), STATE=sha('b'), TARGET='system-master/owner-lane-execution-lease-adoption-001', FILE='governance/CURRENT-AUTHORITY.json', FILE2='governance/SYSTEM-TOPOLOGY-007.json', T0=new Date('2026-09-20T02:30:00Z');
const holder = (id='MUT-1') => ({ workstream_id:'SYSTEM-MASTER-OWNER-LANE-EXECUTION-LEASE-ADOPTION-001', operation_id:'SYSTEM-MASTER-OWNER-LANE-EXECUTION-LEASE-ADOPTION-001', mutation_id:id });
class FakeTransport {
  constructor(){this.refs=new Map([[SYSTEM_FILE_LEASE_STATE_REF,STATE],[TARGET,MAIN]]);this.commits=new Map([[STATE,{sha:STATE,parents:[sha('0')],files:{}}],[MAIN,{sha:MAIN,parents:[sha('9')],files:{}}]]);this.n=1;this.race=false;this.ambiguous=false;}
  async getRef(r){return this.refs.has(r)?{sha:this.refs.get(r)}:null;} async getCommit(s){const c=this.commits.get(s);return c?{sha:c.sha,parents:[...c.parents]}:null;} async readFile(s,p){const c=this.commits.get(s);return c&&Object.hasOwn(c.files,p)?c.files[p]:null;}
  async createCommitFromFiles({parentSha,files}){const p=this.commits.get(parentSha);const s=this.n.toString(16).padStart(40,'c');this.n+=1;this.commits.set(s,{sha:s,parents:[parentSha],files:{...p.files,...files}});return {sha:s};}
  async updateRefFastForward(r,s){if(this.race){this.race=false;const h=this.refs.get(r),p=this.commits.get(h),x=this.n.toString(16).padStart(40,'d');this.n+=1;this.commits.set(x,{sha:x,parents:[h],files:{...p.files}});this.refs.set(r,x);throw new Error('race');}this.refs.set(r,s);if(this.ambiguous){this.ambiguous=false;throw new Error('ambiguous');}return {sha:s};}
}
function make(){const transport=new FakeTransport();let byte=1;return {transport,lease:new GitHubSystemFileLeaseCoordinator({transport,randomBytesFn:(n)=>Buffer.alloc(n,byte++)})};}
const code = async (p,c) => assert.rejects(p,(e)=>e instanceof GitHubSystemFileLeaseError&&e.code===c);
test('acquire persists epoch-1 held record and exact replay preserves fence',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});assert.equal(a.leases[0].lease_epoch,1);const b=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:new Date(T0.getTime()+1000)});assert.equal(b.idempotent_replay,true);assert.equal(b.leases[0].fence_token,a.leases[0].fence_token);assert.equal(JSON.parse(await transport.readFile(a.state_commit_sha,systemFileLeaseRecordPath(FILE))).state,'HELD');});
test('second concurrent holder is refused before target mutation',async()=>{const {lease}=make();await lease.acquire({paths:[FILE],holder:holder('A'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});await code(lease.acquire({paths:[FILE],holder:holder('B'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:new Date(T0.getTime()+1000)}),'SYSTEM_FILE_LOCKED');});
test('expired lease takeover increments epoch and fences stale holder',async()=>{const {lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder('A'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});const later=new Date(T0.getTime()+600001);const b=await lease.acquire({paths:[FILE],holder:holder('B'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:later});assert.equal(b.leases[0].lease_epoch,2);await code(lease.requireAuthority(a,{now:later}),'FENCED_STALE_EXECUTOR');});
test('target movement fails authority check',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});transport.refs.set(TARGET,sha('f'));await code(lease.requireAuthority(a,{now:new Date(T0.getTime()+1000)}),'LEASE_TARGET_MOVED');});
test('multi-path acquisition is atomic and CAS race retries',async()=>{const {transport,lease}=make();transport.race=true;const a=await lease.acquire({paths:[FILE2,FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});assert.equal(a.leases.length,2);const c=transport.commits.get(a.state_commit_sha);assert.ok(c.files[systemFileLeaseRecordPath(FILE)]&&c.files[systemFileLeaseRecordPath(FILE2)]);});
test('ambiguous state-ref update reconciles exact applied commit',async()=>{const {transport,lease}=make();transport.ambiguous=true;const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});assert.equal((await transport.getRef(SYSTEM_FILE_LEASE_STATE_REF)).sha,a.state_commit_sha);});
test('release advances path revision and emits immutable event',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});const result=sha('e');transport.commits.set(result,{sha:result,parents:[MAIN],files:{}});transport.refs.set(TARGET,result);const rel=await lease.release(a,{resultCommitSha:result,now:new Date(T0.getTime()+2000)});const r=JSON.parse(await transport.readFile(rel.state_commit_sha,systemFileLeaseRecordPath(FILE)));assert.equal(r.state,'RELEASED');assert.equal(r.path_revision,1);const e=JSON.parse(await transport.readFile(rel.state_commit_sha,systemFileLeaseEventPath('MUT-1',FILE)));assert.equal(e.result_commit_sha,result);assert.equal(e.acquisition_commit_sha,a.state_commit_sha);});
test('release replay is idempotent',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});const result=sha('e');transport.commits.set(result,{sha:result,parents:[MAIN],files:{}});transport.refs.set(TARGET,result);await lease.release(a,{resultCommitSha:result,now:new Date(T0.getTime()+2000)});const r=await lease.release(a,{resultCommitSha:result,now:new Date(T0.getTime()+3000)});assert.equal(r.idempotent_replay,true);});

test('production writer acquires and revalidates lease before target CAS and releases after success',()=>{const text=fs.readFileSync(new URL('../../.github/scripts/control-gateway-production-writer.js',import.meta.url),'utf8');const acquire=text.indexOf('leaseCoordinator.acquire({');const requireAuth=text.indexOf('leaseCoordinator.requireAuthority(leaseReceipt)');const execute=text.indexOf('writer.execute({ grant: productionGrant, plan, leaseReceipt })');const release=text.indexOf('leaseCoordinator.release(leaseReceipt');assert.ok(acquire>=0&&requireAuth>acquire&&execute>requireAuth&&release>execute);assert.ok(text.includes('system-file-lease-acquisition.json'));assert.ok(text.includes('system-file-lease-release.json'));});


const WRITER_PREDECESSOR='4'.repeat(40), WRITER_TREE='5'.repeat(40), WRITER_RESULT='6'.repeat(40), WRITER_REF='system-master/lease-writer-test';
function writerPlan(message='core: lease-bound write'){const content='x\n';return {protocol_version:GITHUB_PRODUCTION_MUTATION_PLAN_PROTOCOL,mutation_id:'MUT-1',repository:'BFochtman746/system-master',target_kind:'WORK_REF',target_ref:WRITER_REF,expected_predecessor_sha:WRITER_PREDECESSOR,commit_message:message,writes:[{path:FILE,content_utf8:content,content_sha256:sha256(content)}],deletes:[]};}
function writerGrant(plan=writerPlan()){const grant={protocol_version:GITHUB_PRODUCTION_MUTATION_GRANT_PROTOCOL,decision:'GRANTED',mutation_id:'MUT-1',request_digest:'1'.repeat(64),admission_digest:'2'.repeat(64),plan_digest:productionMutationPlanDigest(plan),repository:'BFochtman746/system-master',target_kind:'WORK_REF',target_ref:WRITER_REF,observed_predecessor_sha:WRITER_PREDECESSOR,operation_id:'OP-1',predecessor_receipt_id:null,paths:[FILE],effects:['CONTROL_GATEWAY_DEVELOPMENT_WRITE'],executor_requirement:'RECEIPT_CONSUMING_EXACT_PREDECESSOR_CAS_REQUIRED',grant_digest:''};grant.grant_digest=productionMutationGrantDigest(grant);return grant;}
function writerLease(overrides={}){const receipt={protocol_version:'control-gateway.system-file-lease-acquisition.v1',state_ref:SYSTEM_FILE_LEASE_STATE_REF,state_commit_sha:'7'.repeat(40),target_ref:WRITER_REF,expected_predecessor_sha:WRITER_PREDECESSOR,holder:{workstream_id:'SYSTEM-MASTER-OWNER-LANE-EXECUTION-LEASE-ADOPTION-001',operation_id:'OP-1',mutation_id:'MUT-1'},leases:[{path:FILE,path_revision:0,lease_epoch:3,fence_token:'a'.repeat(64),record_digest:'b'.repeat(64),expires_at:'2099-01-01T00:00:00.000Z'}],idempotent_replay:false,receipt_digest:''};Object.assign(receipt,overrides);const unsigned=structuredClone(receipt);delete unsigned.receipt_digest;receipt.receipt_digest=sha256(unsigned);return receipt;}
class FakeWriterTransport {constructor(){this.owner='BFochtman746';this.repo='system-master';this.refSha=WRITER_PREDECESSOR;this.created=null;}async createTreeFromPlan(){return {sha:WRITER_TREE};}async getRef(){return {sha:this.refSha};}async getCommit(value){if(value===WRITER_PREDECESSOR)return {sha:value,tree_sha:'8'.repeat(40),parents:['9'.repeat(40)],message:'parent'};if(value===WRITER_RESULT)return this.created;return null;}async createCommit({parentSha,treeSha,message}){this.created={sha:WRITER_RESULT,tree_sha:treeSha,parents:[parentSha],message};return {sha:WRITER_RESULT};}async updateRefFastForward(_ref,value){this.refSha=value;return {sha:value};}}
async function writerReject(receipt,code,message='core: lease-bound write'){const plan=writerPlan(message),grant=writerGrant(plan),transport=new FakeWriterTransport();await assert.rejects(new GitHubReceiptConsumingCasWriter({transport}).execute({grant,plan,leaseReceipt:receipt}),(error)=>error instanceof GitHubProductionMutationError&&error.code===code);}
test('lease-bound writer generates exact immutable System-File-Lease trailer',async()=>{const plan=writerPlan(),grant=writerGrant(plan),transport=new FakeWriterTransport();await new GitHubReceiptConsumingCasWriter({transport}).execute({grant,plan,leaseReceipt:writerLease()});assert.match(transport.created.message,/System-File-Lease: governance\/CURRENT-AUTHORITY\.json@3\/a{64}$/m);assert.equal((transport.created.message.match(/System-File-Lease:/g)||[]).length,1);});
test('lease-bound writer rejects caller-forged lease trailer',async()=>{await writerReject(writerLease(),'PRODUCTION_MUTATION_CALLER_LEASE_TRAILER_FORBIDDEN',`core: lease-bound write\n\nSystem-File-Lease: ${FILE}@1/${'c'.repeat(64)}`);});
test('lease-bound writer rejects wrong mutation holder',async()=>{const r=writerLease();r.holder.mutation_id='OTHER';const u=structuredClone(r);delete u.receipt_digest;r.receipt_digest=sha256(u);await writerReject(r,'PRODUCTION_MUTATION_LEASE_BINDING_MISMATCH');});
test('lease-bound writer rejects wrong operation holder',async()=>{const r=writerLease();r.holder.operation_id='OTHER';const u=structuredClone(r);delete u.receipt_digest;r.receipt_digest=sha256(u);await writerReject(r,'PRODUCTION_MUTATION_LEASE_BINDING_MISMATCH');});
test('lease-bound writer rejects wrong target ref',async()=>{const r=writerLease();r.target_ref='system-master/other';const u=structuredClone(r);delete u.receipt_digest;r.receipt_digest=sha256(u);await writerReject(r,'PRODUCTION_MUTATION_LEASE_BINDING_MISMATCH');});
test('lease-bound writer rejects wrong predecessor',async()=>{const r=writerLease();r.expected_predecessor_sha='e'.repeat(40);const u=structuredClone(r);delete u.receipt_digest;r.receipt_digest=sha256(u);await writerReject(r,'PRODUCTION_MUTATION_LEASE_BINDING_MISMATCH');});
test('lease-bound writer rejects wrong path set',async()=>{const r=writerLease();r.leases[0].path=FILE2;const u=structuredClone(r);delete u.receipt_digest;r.receipt_digest=sha256(u);await writerReject(r,'PRODUCTION_MUTATION_LEASE_PATH_SET_MISMATCH');});
test('lease-bound writer rejects tampered lease receipt digest',async()=>{const r=writerLease();r.receipt_digest='f'.repeat(64);await writerReject(r,'PRODUCTION_MUTATION_LEASE_RECEIPT_DIGEST_MISMATCH');});
