import test from 'node:test';
import assert from 'node:assert/strict';
import { GitHubSystemFileLeaseCoordinator, GitHubSystemFileLeaseError, SYSTEM_FILE_LEASE_STATE_REF, systemFileLeaseEventPath, systemFileLeaseRecordPath } from '../src/github-system-file-lease.js';
const sha = (c) => c.repeat(40), MAIN=sha('a'), STATE=sha('b'), TARGET='system-master/owner-lane-execution-lease-adoption-001', FILE='governance/CURRENT-AUTHORITY.json', FILE2='governance/SYSTEM-TOPOLOGY-007.json', T0=new Date('2026-09-20T02:30:00Z');
const holder = (id='MUT-1') => ({ workstream_id:'SYSTEM-MASTER-OWNER-LANE-EXECUTION-LEASE-ADOPTION-001', operation_id:'SYSTEM-MASTER-OWNER-LANE-EXECUTION-LEASE-ADOPTION-001', mutation_id:id });
class FakeTransport {
  constructor(){this.refs=new Map([[SYSTEM_FILE_LEASE_STATE_REF,STATE],[TARGET,MAIN]]);this.commits=new Map([[STATE,{sha:STATE,parents:[sha('0')],files:{}}],[MAIN,{sha:MAIN,parents:[sha('9')],files:{}}]]);this.n=1;this.race=false;this.ambiguous=false;}
  async getRef(r){return this.refs.has(r)?{sha:this.refs.get(r)}:null;} async getCommit(s){const c=this.commits.get(s);return c?{sha:c.sha,parents:[...c.parents]}:null;} async readFile(s,p){const c=this.commits.get(s);return c&&Object.hasOwn(c.files,p)?c.files[p]:null;}
  async createCommitFromFiles({parentSha,files}){const p=this.commits.get(parentSha);const s=this.n.toString(16).padStart(40,'c');this.n+=1;this.commits.set(s,{sha:s,parents:[parentSha],files:{...p.files,...files}});return {sha:s};}
  async updateRefFastForward(r,s){if(this.race){this.race=false;const h=this.refs.get(r),p=this.commits.get(h),x=this.n.toString(16).padStart(40,'d');this.n+=1;this.commits.set(x,{sha:x,parents:[h],files:{...p.files}});this.refs.set(r,x);throw new Error('race');}this.refs.set(r,s);if(this.ambiguous){this.ambiguous=false;throw new Error('ambiguous');}return {sha:s};}
}
function make(){const transport=new FakeTransport();let byte=1;return {transport,lease:new GitHubSystemFileLeaseCoordinator({transport,randomBytesFn:(n)=>Buffer.alloc(n,byte++)})};}
const code = async (p,c) => assert.rejects(p,(e)=>e instanceof GitHubSystemFileLeaseError&&e.code===c);
test('acquire persists epoch-1 held record and exact replay preserves fence',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});assert.equal(a.leases[0].lease_epoch,1);const b=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:new Date(T0.getTime()+1000)});assert.equal(b.idempotent_replay,true);assert.equal(b.leases[0].fence_token,a.leases[0].fence_token);assert.equal(JSON.parse(await transport.readFile(a.state_commit_sha,systemFileLeaseRecordPath(FILE))).state,'HELD');});
test('second concurrent holder is refused before target mutation',async()=>{const {lease}=make();await lease.acquire({paths:[FILE],holder:holder('A'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});await code(lease.acquire({paths:[FILE],holder:holder('B'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:new Date(T0.getTime()+1000)}),'SYSTEM_FILE_LOCKED');});
test('expired lease takeover increments epoch and fences stale holder',async()=>{const {lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder('A'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});const later=new Date(T0.getTime()+600001);const b=await lease.acquire({paths:[FILE],holder:holder('B'),targetRef:TARGET,expectedPredecessorSha:MAIN,now:later});assert.equal(b.leases[0].lease_epoch,2);await code(lease.requireAuthority(a,{now:later}),'FENCED_STALE_EXECUTOR');});
test('target movement fails authority check',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});transport.refs.set(TARGET,sha('f'));await code(lease.requireAuthority(a,{now:new Date(T0.getTime()+1000)}),'LEASE_TARGET_MOVED');});
test('multi-path acquisition is atomic and CAS race retries',async()=>{const {transport,lease}=make();transport.race=true;const a=await lease.acquire({paths:[FILE2,FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});assert.equal(a.leases.length,2);const c=transport.commits.get(a.state_commit_sha);assert.ok(c.files[systemFileLeaseRecordPath(FILE)]&&c.files[systemFileLeaseRecordPath(FILE2)]);});
test('ambiguous state-ref update reconciles exact applied commit',async()=>{const {transport,lease}=make();transport.ambiguous=true;const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});assert.equal((await transport.getRef(SYSTEM_FILE_LEASE_STATE_REF)).sha,a.state_commit_sha);});
test('release advances path revision and emits immutable event',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});const result=sha('e');transport.commits.set(result,{sha:result,parents:[MAIN],files:{}});transport.refs.set(TARGET,result);const rel=await lease.release(a,{resultCommitSha:result,now:new Date(T0.getTime()+2000)});const r=JSON.parse(await transport.readFile(rel.state_commit_sha,systemFileLeaseRecordPath(FILE)));assert.equal(r.state,'RELEASED');assert.equal(r.path_revision,1);const e=JSON.parse(await transport.readFile(rel.state_commit_sha,systemFileLeaseEventPath('MUT-1',FILE)));assert.equal(e.result_commit_sha,result);assert.equal(e.acquisition_commit_sha,a.state_commit_sha);});
test('release replay is idempotent',async()=>{const {transport,lease}=make();const a=await lease.acquire({paths:[FILE],holder:holder(),targetRef:TARGET,expectedPredecessorSha:MAIN,now:T0});const result=sha('e');transport.commits.set(result,{sha:result,parents:[MAIN],files:{}});transport.refs.set(TARGET,result);await lease.release(a,{resultCommitSha:result,now:new Date(T0.getTime()+2000)});const r=await lease.release(a,{resultCommitSha:result,now:new Date(T0.getTime()+3000)});assert.equal(r.idempotent_replay,true);});
