'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const obs = require('./book-literary-diagnostic-observation-v1');
const diagnosis = require('./book-literary-diagnosis-v1');
const fx = require('./book-literary-test-fixtures');

const expectCode = code => err => err && err.code === code;

function contextForLens(lensId) {
  if (['B05-LENS-004','B05-LENS-005','B05-LENS-006','B05-LENS-007'].includes(lensId)) return fx.makeContext({ lenses: [lensId], b03: true });
  if (lensId === 'B05-LENS-009') return fx.makeContext({ lenses: [lensId], b04: true });
  if (lensId === 'B05-LENS-016') return fx.makeContext({ lenses: [lensId], b03: true, author: true });
  return fx.makeContext({ lenses: [lensId] });
}
function seal(context, lensId, overrides = {}, providerAdmission = null) {
  return obs.acceptLiteraryDiagnosticObservationV1({ diagnostic_context: context, observation: fx.makeObservationPayload(context, lensId, overrides), provider_admission: providerAdmission });
}
function accepted(lensId, options = {}) {
  const context = contextForLens(lensId);
  return { context, observation: seal(context, lensId, options) };
}
function forbidExtra(lensId, extra, expectedCode = 'BLOCKED_OBSERVATION_BINDING_MISMATCH') {
  const context = contextForLens(lensId);
  assert.throws(() => seal(context, lensId, extra), expectCode(expectedCode));
}

// Frozen S01-S36 specialist/lens laws. These are focused implementation checks, not B05-E denominator substitution.
test('D2-S01 sentence rhythm/syntax emits bounded craft evidence', () => { const { observation } = accepted('B05-LENS-001'); assert.equal(observation.lens_id, 'B05-LENS-001'); assert.equal(observation.canonical_effect, false); });
test('D2-S02 sentence rhythm/syntax cannot emit replacement prose', () => forbidExtra('B05-LENS-001', { replacement_prose: 'rewrite' }, 'BLOCKED_REWRITE_PAYLOAD_FORBIDDEN'));
test('D2-S03 paragraph movement emits bounded craft evidence', () => { const { observation } = accepted('B05-LENS-002'); assert.equal(observation.standing, 'ACCEPTED_UNCALIBRATED'); });
test('D2-S04 paragraph movement preserves exact scope and cannot mutate source structure', () => { const c = contextForLens('B05-LENS-002'); const p = fx.makeObservationPayload(c, 'B05-LENS-002'); p.scope_limits = { ...c.scope, scope_ref: 'mutated' }; assert.throws(() => obs.acceptLiteraryDiagnosticObservationV1({ diagnostic_context: c, observation: p, provider_admission: null }), expectCode('BLOCKED_OBSERVATION_BINDING_MISMATCH')); });
test('D2-S05 diction/register emits local craft evidence', () => { const { observation } = accepted('B05-LENS-003'); assert.equal(observation.lens_id, 'B05-LENS-003'); });
test('D2-S06 diction/register cannot promote local evidence to B08 governing voice standing', () => forbidExtra('B05-LENS-003', { voice_standing: 'VOICE_EVOLUTION' }, 'BLOCKED_VOICE_STANDING_FORBIDDEN'));
test('D2-S07 POV/focalization/distance requires exact upstream context', () => { const c = fx.makeContext({ lenses: ['B05-LENS-004'], b03: true }); assert.equal(seal(c, 'B05-LENS-004').lens_id, 'B05-LENS-004'); const bad = fx.makeContext({ lenses: ['B05-LENS-004'] }); assert.throws(() => seal(bad, 'B05-LENS-004'), expectCode('BLOCKED_OBSERVATION_BINDING_MISMATCH')); });
test('D2-S08 POV lens cannot redefine POV/focalization truth', () => forbidExtra('B05-LENS-004', { pov_truth: 'OMNISCIENT' }));
test('D2-S09 character agency/continuity consumes B03 character/event truth', () => { const c = fx.makeContext({ lenses: ['B05-LENS-005'], b03: true }); assert.equal(seal(c, 'B05-LENS-005').standing, 'ACCEPTED_UNCALIBRATED'); });
test('D2-S10 character lens cannot synthesize goals/knowledge/relationships', () => forbidExtra('B05-LENS-005', { character_goal_truth: 'invented' }));
test('D2-S11 dialogue/subtext emits local craft evidence', () => { const { observation } = accepted('B05-LENS-006'); assert.equal(observation.lens_id, 'B05-LENS-006'); });
test('D2-S12 dialogue distinctiveness cannot become governing voice standing', () => forbidExtra('B05-LENS-006', { trait_disposition: 'PROTECT' }, 'BLOCKED_VOICE_STANDING_FORBIDDEN'));
test('D2-S13 scene tension/causality emits craft evidence against exact upstream truth', () => { const { observation } = accepted('B05-LENS-007'); assert.equal(observation.finding_class, 'STRENGTH'); });
test('D2-S14 scene tension lens cannot mutate causal or reader truth', () => forbidExtra('B05-LENS-007', { causal_event_truth: 'mutated' }));
test('D2-S15 pacing compression/expansion emits local craft evidence', () => { const { observation } = accepted('B05-LENS-008'); assert.equal(observation.lens_id, 'B05-LENS-008'); });
test('D2-S16 pacing lens cannot create B04 reader pacing standing', () => forbidExtra('B05-LENS-008', { reader_pacing_standing: 'FAST_IS_BETTER' }));
test('D2-S17 information release/orientation consumes exact B04 evidence', () => { const c = fx.makeContext({ lenses: ['B05-LENS-009'], b04: true }); assert.equal(seal(c, 'B05-LENS-009').standing, 'ACCEPTED_UNCALIBRATED'); });
test('D2-S18 information release cannot create reveal frontier/reader-access truth', () => forbidExtra('B05-LENS-009', { reveal_frontier: { invented: true } }));
test('D2-S19 description/imagery/metaphor/motif emits local craft evidence', () => { const { observation } = accepted('B05-LENS-010'); assert.equal(observation.lens_id, 'B05-LENS-010'); });
test('D2-S20 motif lens cannot synthesize B03 motif/theme truth', () => forbidExtra('B05-LENS-010', { canonical_motif_truth: 'invented' }));
test('D2-S21 emotional progression emits craft evidence with exact dependencies', () => { const { observation } = accepted('B05-LENS-011'); assert.ok(observation.upstream_dependency_refs.length > 0); });
test('D2-S22 emotional progression cannot synthesize character emotion or B04 affect standing', () => forbidExtra('B05-LENS-011', { reader_affect_standing: 'CERTAIN' }));
test('D2-S23 exposition/argument emits bounded rhetorical/craft evidence', () => { const { observation } = accepted('B05-LENS-012'); assert.equal(observation.canonical_effect, false); });
test('D2-S24 exposition quality cannot certify factual truth', () => forbidExtra('B05-LENS-012', { factual_truth_certified: true }));
test('D2-S25 theological/philosophical presentation emits craft/reasoning-presentation evidence', () => { const { observation } = accepted('B05-LENS-013'); assert.equal(observation.lens_id, 'B05-LENS-013'); });
test('D2-S26 theological/philosophical craft cannot certify truth', () => forbidExtra('B05-LENS-013', { theological_truth_certified: true }));
test('D2-S27 historical register emits bounded craft/register evidence', () => { const { observation } = accepted('B05-LENS-014'); assert.equal(observation.lens_id, 'B05-LENS-014'); });
test('D2-S28 historical register cannot certify historical fact/source authority', () => forbidExtra('B05-LENS-014', { historical_fact_certified: true }));
test('D2-S29 opening/ending turns emit bounded entry/exit movement evidence', () => { const { observation } = accepted('B05-LENS-015'); assert.equal(observation.lens_id, 'B05-LENS-015'); });
test('D2-S30 opening/ending inference cannot synthesize author intent', () => forbidExtra('B05-LENS-015', { author_intent: 'invented' }));
test('D2-S31 canon/protected-language check requires exact B03 + B10 context', () => { const c = fx.makeContext({ lenses: ['B05-LENS-016'], b03: true, author: true }); assert.equal(seal(c, 'B05-LENS-016').standing, 'ACCEPTED_UNCALIBRATED'); });
test('D2-S32 canon check can report risk but cannot create canon/protected-language/author decision', () => forbidExtra('B05-LENS-016', { author_decision: 'APPROVE' }));
test('D2-S33 voice evolution remains B08 seam while B05 may emit local voice signal', () => { const c = contextForLens('B05-LENS-003'); const o = seal(c, 'B05-LENS-003', { external_owner_signal_refs: [{ owner_domain: 'B08', signal_class: 'VOICE_RELEVANT_LOCAL_SIGNAL', signal_ref: 'signal:voice:1' }] }); assert.equal(o.external_owner_signal_refs[0].owner_domain, 'B08'); });
test('D2-S34 local voice signal cannot serialize B08 degradation/evolution standing', () => forbidExtra('B05-LENS-003', { voice_evolution: 'SUPPORTED' }, 'BLOCKED_VOICE_STANDING_FORBIDDEN'));
test('D2-S35 homogenization remains B08 seam while B05 may emit potential-risk signal', () => { const c = contextForLens('B05-LENS-001'); const o = seal(c, 'B05-LENS-001', { external_owner_signal_refs: [{ owner_domain: 'B08', signal_class: 'POTENTIAL_HOMOGENIZATION_RISK_SIGNAL', signal_ref: 'signal:homo:1' }] }); assert.equal(o.external_owner_signal_refs[0].signal_class, 'POTENTIAL_HOMOGENIZATION_RISK_SIGNAL'); });
test('D2-S36 B05 potential homogenization signal cannot satisfy B08 governing standing', () => forbidExtra('B05-LENS-001', { homogenization_standing: 'PASS' }, 'BLOCKED_VOICE_STANDING_FORBIDDEN'));

// D2 observation and assembly hardening.
test('D2-37 same deterministic observation input yields same sealed identity', () => { const c = contextForLens('B05-LENS-001'); const a = seal(c, 'B05-LENS-001'); const b = seal(c, 'B05-LENS-001'); assert.equal(a.diagnostic_observation_id, b.diagnostic_observation_id); assert.equal(a.diagnostic_observation_digest, b.diagnostic_observation_digest); });
test('D2-38 MODEL observation requires exact current provider admission', () => { const c = contextForLens('B05-LENS-001'); const p = fx.makeObservationPayload(c, 'B05-LENS-001', { source_class: 'MODEL' }); assert.throws(() => obs.acceptLiteraryDiagnosticObservationV1({ diagnostic_context: c, observation: p, provider_admission: null }), expectCode('BLOCKED_PROVIDER_SUBJECT_UNADMITTED')); const admitted = obs.acceptLiteraryDiagnosticObservationV1({ diagnostic_context: c, observation: p, provider_admission: fx.makeProviderAdmission() }); assert.equal(admitted.provider_capability_id, 'BOOK.LITERARY.DIAGNOSE'); });
test('D2-39 HUMAN source cannot carry provider standing or calibrated gold standing', () => { const c = contextForLens('B05-LENS-001'); const p = fx.makeObservationPayload(c, 'B05-LENS-001', { source_class: 'HUMAN' }); const o = obs.acceptLiteraryDiagnosticObservationV1({ diagnostic_context: c, observation: p, provider_admission: null }); assert.equal(o.provider_subject_ref, null); assert.equal(o.standing, 'ACCEPTED_UNCALIBRATED'); });
test('D2-40 substantive finding requires anchors evidence dependencies and non-unspecified strength', () => { const c = contextForLens('B05-LENS-001'); assert.throws(() => seal(c, 'B05-LENS-001', { evidence_refs: [] }), expectCode('BLOCKED_OBSERVATION_BINDING_MISMATCH')); assert.throws(() => seal(c, 'B05-LENS-001', { evidence_strength_class: 'UNSPECIFIED' }), expectCode('BLOCKED_OBSERVATION_BINDING_MISMATCH')); });
test('D2-41 abstention is sparse and strength-unspecified with reason', () => { const c = contextForLens('B05-LENS-001'); const o = seal(c, 'B05-LENS-001', { finding_class: 'ABSTAINED', target_anchor_refs: [], evidence_refs: [], upstream_dependency_refs: [], evidence_strength_class: 'UNSPECIFIED', purpose_relevance_class: 'UNKNOWN', preservation_risk_class: 'UNKNOWN', collateral_risk_class: 'UNKNOWN', abstention_or_blocker_reason: 'INSUFFICIENT_EVIDENCE', standing: 'ABSTAINED' }); assert.equal(o.standing, 'ABSTAINED'); });
test('D2-42 blocked observation is sparse and preserves blocker reason', () => { const c = contextForLens('B05-LENS-001'); const o = seal(c, 'B05-LENS-001', { finding_class: 'BLOCKED', target_anchor_refs: [], evidence_refs: [], upstream_dependency_refs: [], evidence_strength_class: 'UNSPECIFIED', purpose_relevance_class: 'UNKNOWN', preservation_risk_class: 'UNKNOWN', collateral_risk_class: 'UNKNOWN', abstention_or_blocker_reason: 'OWNER_CONSTRAINT', standing: 'BLOCKED' }); assert.equal(o.abstention_or_blocker_reason, 'OWNER_CONSTRAINT'); });
test('D2-43 observation for unrequested lens fails closed', () => { const c = contextForLens('B05-LENS-001'); assert.throws(() => seal(c, 'B05-LENS-002'), expectCode('BLOCKED_OBSERVATION_BINDING_MISMATCH')); });
test('D2-44 raw text, candidate text, universal score and named-author target payloads fail closed', () => { const c = contextForLens('B05-LENS-001'); assert.throws(() => seal(c, 'B05-LENS-001', { raw_manuscript_text: 'x' }), expectCode('BLOCKED_RAW_TEXT_FORBIDDEN')); assert.throws(() => seal(c, 'B05-LENS-001', { candidate_text: 'x' }), expectCode('BLOCKED_REWRITE_PAYLOAD_FORBIDDEN')); assert.throws(() => seal(c, 'B05-LENS-001', { literary_quality_score: 99 }), expectCode('BLOCKED_UNIVERSAL_PROSE_SCORE_FORBIDDEN')); assert.throws(() => seal(c, 'B05-LENS-001', { named_author_target: 'x' }), expectCode('BLOCKED_NAMED_AUTHOR_TARGET_FORBIDDEN')); });
test('D2-45 sealed observation digest tampering fails closed', () => { const c = contextForLens('B05-LENS-001'); const o = seal(c, 'B05-LENS-001'); const t = fx.clone(o); t.diagnostic_observation_digest = fx.H('f'); assert.throws(() => obs.validateLiteraryDiagnosticObservationV1(t, c), expectCode('BLOCKED_DIGEST_MISMATCH')); });
test('D2-46 empty diagnosis exposes exactly 16 lens coverage rows and requested lens remains unobserved', () => { const c = contextForLens('B05-LENS-001'); const d = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [] }); assert.equal(d.lens_coverage.length, 16); assert.equal(d.lens_coverage.find(x => x.lens_id === 'B05-LENS-001').disposition, 'UNOBSERVED'); assert.equal(d.standing, 'PARTIALLY_OBSERVED'); });
test('D2-47 a resolved requested lens yields DIAGNOSED while unrequested lenses remain UNOBSERVED', () => { const c = contextForLens('B05-LENS-001'); const o = seal(c, 'B05-LENS-001'); const d = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [o] }); assert.equal(d.standing, 'DIAGNOSED'); assert.equal(d.lens_coverage[0].disposition, 'OBSERVED'); assert.equal(d.lens_coverage[1].disposition, 'UNOBSERVED'); });
test('D2-48 abstained or blocked requested lens remains PARTIALLY_OBSERVED, never implicit PASS', () => { const c = contextForLens('B05-LENS-001'); const a = seal(c, 'B05-LENS-001', { finding_class: 'ABSTAINED', target_anchor_refs: [], evidence_refs: [], upstream_dependency_refs: [], evidence_strength_class: 'UNSPECIFIED', purpose_relevance_class: 'UNKNOWN', preservation_risk_class: 'UNKNOWN', collateral_risk_class: 'UNKNOWN', abstention_or_blocker_reason: 'NO_BASIS', standing: 'ABSTAINED' }); const d = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [a] }); assert.equal(d.standing, 'PARTIALLY_OBSERVED'); assert.equal(d.lens_coverage[0].disposition, 'ABSTAINED'); });
test('D2-49 duplicate observation IDs are rejected rather than double-counted', () => { const c = contextForLens('B05-LENS-001'); const o = seal(c, 'B05-LENS-001'); assert.throws(() => diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [o,o] }), expectCode('BLOCKED_OBSERVATION_BINDING_MISMATCH')); });
test('D2-50 diagnosis preserves strengths, limitations/risks/opportunities and contradictions separately', () => { const c = fx.makeContext({ lenses: ['B05-LENS-001','B05-LENS-002'] }); const s = seal(c, 'B05-LENS-001', { finding_class: 'STRENGTH' }); const l = seal(c, 'B05-LENS-002', { finding_class: 'LIMITATION' }); const d = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [s,l] }); assert.deepEqual(d.strength_observation_refs, [s.diagnostic_observation_id]); assert.deepEqual(d.limitation_risk_opportunity_observation_refs, [l.diagnostic_observation_id]); });
test('D2-51 external B08 signals remain signals, not governing standing', () => { const c = contextForLens('B05-LENS-003'); const o = seal(c, 'B05-LENS-003', { external_owner_signal_refs: [{ owner_domain: 'B08', signal_class: 'VOICE_RELEVANT_LOCAL_SIGNAL', signal_ref: 'signal:voice:diagnosis' }] }); const d = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [o] }); assert.equal(d.external_owner_signal_refs.length, 1); assert.equal(Object.hasOwn(d, 'voice_standing'), false); });
test('D2-52 MODEL provider admission becomes exact diagnosis dependency', () => { const c = contextForLens('B05-LENS-001'); const p = fx.makeObservationPayload(c, 'B05-LENS-001', { source_class: 'MODEL' }); const o = obs.acceptLiteraryDiagnosticObservationV1({ diagnostic_context: c, observation: p, provider_admission: fx.makeProviderAdmission() }); const d = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [o] }); const dep = d.dependency_refs.find(x => x.dependency_kind === 'B01_PROVIDER_ADMISSION'); assert.equal(dep.dependency_ref, o.provider_admission_ref); assert.equal(dep.dependency_digest, o.provider_admission_digest); });
test('D2-53 diagnosis is deterministic/content-addressed independent of observation input order', () => { const c = fx.makeContext({ lenses: ['B05-LENS-001','B05-LENS-002'] }); const a = seal(c, 'B05-LENS-001'); const b = seal(c, 'B05-LENS-002'); const d1 = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [a,b] }); const d2 = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [b,a] }); assert.equal(d1.diagnosis_id, d2.diagnosis_id); assert.equal(d1.diagnosis_digest, d2.diagnosis_digest); });
test('D2-54 diagnosis canonical effect is false and digest tampering fails closed', () => { const c = contextForLens('B05-LENS-001'); const o = seal(c, 'B05-LENS-001'); const d = diagnosis.assembleLiteraryDiagnosisV1({ diagnostic_context: c, observations: [o] }); assert.equal(d.canonical_effect, false); const t = fx.clone(d); t.diagnosis_digest = fx.H('e'); assert.throws(() => diagnosis.validateLiteraryDiagnosisV1(t, c, [o]), expectCode('BLOCKED_DIGEST_MISMATCH')); });
