package org.systemmaster.foundation.planning;

import org.systemmaster.foundation.planning.PlanningOrchestrationAuthorityRuntime.*;
import org.systemmaster.foundation.workproject.WorkProjectAuthorityRuntime;
import org.systemmaster.foundation.workproject.WorkProjectAuthorityRuntime.WorkLifecycle;
import org.systemmaster.foundation.workproject.WorkProjectAuthorityRuntime.WorkPlanningRefV1;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

public final class PlanningOrchestrationAuthorityQualificationTest {
    private static final String CONTRACT_DIGEST=PlanningOrchestrationAuthorityRuntime.sha256("planning-contract-v1");
    private static final Instant T=Instant.parse("2026-09-12T12:00:00Z");
    private static int command=0;

    @FunctionalInterface interface ThrowingRunnable { void run() throws Exception; }
    static final class Cases {
        int count=0;
        void run(String name,ThrowingRunnable body) throws Exception { try{body.run();count++;System.out.println("ok "+count+" - "+name);}catch(Throwable t){System.err.println("not ok "+(count+1)+" - "+name);throw t;} }
    }
    static final class Fixture {
        final Path dir;final Path log;WorkPlanningRefV1 ref;final String[] currentDigest;final GateStanding[] gate={GateStanding.VALID};boolean contract=true;
        Fixture() throws IOException {dir=Files.createTempDirectory("planning-q-");log=dir.resolve("planning.log");ref=workRef("work-1",1,WorkLifecycle.ACTIVE,"goal-1",1,1);currentDigest=new String[]{ref.canonicalDigest()};}
        PlanningOrchestrationAuthorityRuntime runtime() throws IOException {return runtime(()->{});}
        PlanningOrchestrationAuthorityRuntime runtime(FaultInjector fault) throws IOException {return new PlanningOrchestrationAuthorityRuntime(log,Clock.fixed(T,ZoneOffset.UTC),b->Objects.equals(currentDigest[0],b.canonicalDigest()),(id,v,d)->contract&&PlanningOrchestrationAuthorityRuntime.CONTRACT_ID.equals(id)&&PlanningOrchestrationAuthorityRuntime.CONTRACT_VERSION.equals(v)&&CONTRACT_DIGEST.equals(d),(w,c)->gate[0],fault);}
    }

    public static void main(String[] args) throws Exception {
        Cases c=new Cases();

        c.run("01 create Plan identity from exact WorkPlanningRef",()->{Fixture f=new Fixture();var r=f.runtime();var v=create(r,f.ref,"p1",single(),"k1");eq(1,v.planRevision());eq(PlanStanding.DRAFT,v.standing());});
        c.run("02 duplicate Plan identity rejects",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",single(),"k2"));});
        c.run("03 malformed Plan identity rejects zero mutation",()->{Fixture f=new Fixture();var r=f.runtime();expect(IllegalArgumentException.class,()->create(r,f.ref," ",single(),"k1"));eq(0,r.planIdentityCount());});
        c.run("04 unknown/stale Work ref rejects activation",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");f.currentDigest[0]=PlanningOrchestrationAuthorityRuntime.sha256("other");expect(IllegalStateException.class,()->activate(r,"p1",1,"k2"));});
        c.run("05 Work-ref digest mismatch rejects",()->{Fixture f=new Fixture();var bad=new WorkPlanningRefV1(f.ref.workId(),f.ref.workEntityRevision(),f.ref.governedGoalRef(),f.ref.projectId(),f.ref.parentWorkId(),f.ref.lifecycle(),f.ref.blockerRefs(),f.ref.registryRevision(),PlanningOrchestrationAuthorityRuntime.sha256("bad"));var r=f.runtime();expect(IllegalArgumentException.class,()->create(r,bad,"p1",single(),"k1"));});
        c.run("06 stale Work entity revision rejects actionable activation",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");f.ref=workRef("work-1",2,WorkLifecycle.ACTIVE,"goal-1",1,2);f.currentDigest[0]=f.ref.canonicalDigest();expect(IllegalStateException.class,()->activate(r,"p1",1,"k2"));});
        c.run("07 exact Goal ref survives into readiness handoff",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");var h=r.readinessHandoff("p1",1,"s1");eq(f.ref.governedGoalRef().goalRevisionId(),h.governedGoalRef().goalRevisionId());eq(f.ref.governedGoalRef().goalContentDigest(),h.governedGoalRef().goalContentDigest());});
        c.run("08 cross-Work Plan rebinding rejects",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");var other=workRef("work-2",1,WorkLifecycle.ACTIVE,"goal-1",1,1);expect(IllegalArgumentException.class,()->revision(r,"p1",1,other,single(),"k2"));});
        c.run("09 different goalId replan rejects",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");var other=workRef("work-1",2,WorkLifecycle.ACTIVE,"goal-2",2,2);expect(IllegalArgumentException.class,()->revision(r,"p1",1,other,single(),"k2"));});
        c.run("10 newer same-goal revision accepted only through exact new Work ref",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");var newer=workRef("work-1",2,WorkLifecycle.ACTIVE,"goal-1",2,2);var v=revision(r,"p1",1,newer,single(),"k2");eq(2,v.planRevision());});

        c.run("11 first Plan revision is one",()->{Fixture f=new Fixture();eq(1,create(f.runtime(),f.ref,"p1",single(),"k1").planRevision());});
        c.run("12 exact command replay returns exact logical result",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=single();String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("CreatePlan",f.ref.canonicalDigest(),"p1",p.digest());CommandMeta m=meta("same",null,req);var a=r.createPlan(m,f.ref,"p1",p);var b=r.createPlan(m,f.ref,"p1",p);eq(a.planRevisionId(),b.planRevisionId());eq(1,r.planIdentityCount());});
        c.run("13 idempotency key with different request conflicts",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"same");expect(IdempotencyConflictException.class,()->create(r,f.ref,"p2",single(),"same"));});
        c.run("14 stale expected orchestration revision rejects",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("ActivatePlanRevision","p1","1",r.getPlan("p1",1).planContentDigest());expect(StaleRevisionException.class,()->r.activatePlanRevision(meta("k2",99L,req),"p1",1));});
        c.run("15 successor revision increments exactly one",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");eq(2,revision(r,"p1",1,f.ref,single(),"k2").planRevision());});
        c.run("16 same next revision fork conflicts",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");revision(r,"p1",1,f.ref,single(),"k2");expect(IllegalArgumentException.class,()->revision(r,"p1",1,f.ref,linear(),"k3"));});
        c.run("17 successor activation atomically supersedes prior",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");revision(r,"p1",1,f.ref,linear(),"k3");activate(r,"p1",2,"k4");eq(PlanStanding.SUPERSEDED,r.getPlan("p1",1).standing());eq(PlanStanding.ACTIVE,r.getPlan("p1",2).standing());});
        c.run("18 failed successor activation preserves prior",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");revision(r,"p1",1,f.ref,linear(),"k3");f.gate[0]=GateStanding.INVALID;expect(IllegalStateException.class,()->activate(r,"p1",2,"k4"));eq(PlanStanding.ACTIVE,r.getPlan("p1",1).standing());eq(PlanStanding.DRAFT,r.getPlan("p1",2).standing());});
        c.run("19 superseded revision cannot emit new handoff",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");revision(r,"p1",1,f.ref,single(),"k3");activate(r,"p1",2,"k4");expect(IllegalStateException.class,()->r.readinessHandoff("p1",1,"s1"));});
        c.run("20 second concurrent actionable Plan for Work rejects",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");create(r,f.ref,"p2",single(),"k2");activate(r,"p1",1,"k3");expect(IllegalStateException.class,()->activate(r,"p2",1,"k4"));});

        c.run("21 valid linear DAG publishes",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",linear(),"k1");activate(r,"p1",1,"k2");eq(List.of("a"),r.listReadySteps("p1",1));});
        c.run("22 valid parallel DAG with join publishes",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",parallelJoin(JoinKind.ALL,0),"k1");activate(r,"p1",1,"k2");eq(List.of("a","b"),r.listReadySteps("p1",1));});
        c.run("23 self-edge rejects",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=candidate(List.of(exec("a",CompletionRole.REQUIRED)),List.of(new EdgeSpec("e","a","a",EdgeGate.ON_SATISFIED)),Map.of(),null);expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",p,"k1"));});
        c.run("24 two-node cycle rejects",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=candidate(List.of(exec("a",CompletionRole.REQUIRED),exec("b",CompletionRole.REQUIRED)),List.of(new EdgeSpec("e1","a","b",EdgeGate.ON_SATISFIED),new EdgeSpec("e2","b","a",EdgeGate.ON_SATISFIED)),Map.of(),null);expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",p,"k1"));});
        c.run("25 multi-node cycle rejects",()->{Fixture f=new Fixture();var r=f.runtime();List<StepSpec>s=List.of(exec("a",CompletionRole.REQUIRED),exec("b",CompletionRole.REQUIRED),exec("c",CompletionRole.REQUIRED));List<EdgeSpec>e=List.of(new EdgeSpec("e1","a","b",EdgeGate.ON_SATISFIED),new EdgeSpec("e2","b","c",EdgeGate.ON_SATISFIED),new EdgeSpec("e3","c","a",EdgeGate.ON_SATISFIED));expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",candidate(s,e,Map.of(),null),"k1"));});
        c.run("26 missing Step dependency rejects",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=candidate(List.of(exec("a",CompletionRole.REQUIRED)),List.of(new EdgeSpec("e","a","missing",EdgeGate.ON_SATISFIED)),Map.of(),null);expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",p,"k1"));});
        c.run("27 duplicate Step id conflicting content rejects",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=candidate(List.of(exec("a",CompletionRole.REQUIRED),exec("a",CompletionRole.OPTIONAL)),List.of(),Map.of(),null);expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",p,"k1"));});
        c.run("28 duplicate edge identity rejects",()->{Fixture f=new Fixture();var r=f.runtime();List<StepSpec>s=List.of(exec("a",CompletionRole.REQUIRED),exec("b",CompletionRole.REQUIRED));List<EdgeSpec>e=List.of(new EdgeSpec("x","a","b",EdgeGate.ON_SATISFIED),new EdgeSpec("x","a","b",EdgeGate.ON_FAILED));expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",candidate(s,e,Map.of("b",new JoinSpec(JoinKind.ANY,0)),null),"k1"));});
        c.run("29 exactly 1024 Steps structurally admissible",()->{Fixture f=new Fixture();var r=f.runtime();List<StepSpec>s=new ArrayList<>();for(int i=0;i<1024;i++)s.add(exec("s"+i,CompletionRole.OPTIONAL));create(r,f.ref,"p1",candidate(s,List.of(),Map.of(),"partial"),"k1");});
        c.run("30 1025 Steps rejects",()->{Fixture f=new Fixture();var r=f.runtime();List<StepSpec>s=new ArrayList<>();for(int i=0;i<1025;i++)s.add(exec("s"+i,CompletionRole.OPTIONAL));expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",candidate(s,List.of(),Map.of(),"partial"),"k1"));});
        c.run("31 exactly 8192 edges structurally admissible",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=edgeBoundary(8192);create(r,f.ref,"p1",p,"k1");});
        c.run("32 8193 edges rejects",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=edgeBoundary(8193);expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",p,"k1"));});
        c.run("33 depth 64 accepted and 65 rejected",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",chain(64),"k1");expect(IllegalArgumentException.class,()->create(r,f.ref,"p2",chain(65),"k2"));});
        c.run("34 ready-width over 64 rejects activation",()->{Fixture f=new Fixture();var r=f.runtime();List<StepSpec>s=new ArrayList<>();for(int i=0;i<65;i++)s.add(exec("s"+i,CompletionRole.OPTIONAL));create(r,f.ref,"p1",candidate(s,List.of(),Map.of(),"partial"),"k1");expect(IllegalArgumentException.class,()->activate(r,"p1",1,"k2"));});

        c.run("35 active root execution becomes READY",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");eq(StepStanding.READY,r.getStepReadiness("p1",1,"s1").standing());});
        c.run("36 Draft or Blocked Plan cannot emit readiness",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");expect(IllegalStateException.class,()->r.readinessHandoff("p1",1,"s1"));activate(r,"p1",1,"k2");block(r,"p1",1,"k3");expect(IllegalStateException.class,()->r.readinessHandoff("p1",1,"s1"));});
        c.run("37 satisfied predecessor unlocks dependent",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",linear(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"a","k3");basis(r,"p1",1,"a",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k4");eq(StepStanding.READY,r.getStepReadiness("p1",1,"b").standing());});
        c.run("38 UNKNOWN predecessor cannot unlock dependent",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",linear(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"a","k3");basis(r,"p1",1,"a",BasisKind.OWNER_COMPLETION,StepStanding.UNKNOWN,"k4");eq(StepStanding.NOT_READY,r.getStepReadiness("p1",1,"b").standing());});
        c.run("39 failed required predecessor blocks ordinary path",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",linear(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"a","k3");basis(r,"p1",1,"a",BasisKind.OWNER_COMPLETION,StepStanding.FAILED,"k4");eq(StepStanding.NOT_READY,r.getStepReadiness("p1",1,"b").standing());});
        c.run("40 ALL join waits for all predecessors",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",parallelJoin(JoinKind.ALL,0),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"a","k3");basis(r,"p1",1,"a",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k4");eq(StepStanding.NOT_READY,r.getStepReadiness("p1",1,"j").standing());associate(r,"p1",1,"b","k5");basis(r,"p1",1,"b",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k6");eq(StepStanding.SATISFIED,r.getStepReadiness("p1",1,"j").standing());});
        c.run("41 ANY join unlocks from one resolved gate",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",parallelJoin(JoinKind.ANY,0),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"a","k3");basis(r,"p1",1,"a",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k4");eq(StepStanding.SATISFIED,r.getStepReadiness("p1",1,"j").standing());});
        c.run("42 AT_LEAST_N unlocks only at threshold",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",parallelJoin(JoinKind.AT_LEAST_N,2),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"a","k3");basis(r,"p1",1,"a",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k4");eq(StepStanding.NOT_READY,r.getStepReadiness("p1",1,"j").standing());associate(r,"p1",1,"b","k5");basis(r,"p1",1,"b",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k6");eq(StepStanding.SATISFIED,r.getStepReadiness("p1",1,"j").standing());});
        c.run("43 unknown predicate language rejects",()->{Fixture f=new Fixture();var r=f.runtime();ConditionSpec cs=new ConditionSpec("c","UNKNOWN",PredicateNode.constant("true"));StepSpec s=new StepSpec("c",1,StepKind.CONDITION,CompletionRole.REQUIRED,req(),cs,null,null);expect(IllegalArgumentException.class,()->create(r,f.ref,"p1",candidate(List.of(s),List.of(),Map.of(),null),"k1"));});
        c.run("44 same predicate exact inputs deterministic",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=conditionPlan();create(r,f.ref,"p1",p,"k1");activate(r,"p1",1,"k2");BoundValue v=new BoundValue("owner","ref","v1","5");ConditionReceipt a=condition(r,"p1",1,"c",Map.of("x",v),"k3");eq(ConditionResult.TRUE,a.result());});
        c.run("45 missing exact condition input yields UNKNOWN and no branch readiness",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",conditionPlan(),"k1");activate(r,"p1",1,"k2");ConditionReceipt a=condition(r,"p1",1,"c",Map.of(),"k3");eq(ConditionResult.UNKNOWN,a.result());eq(StepStanding.NOT_READY,r.getStepReadiness("p1",1,"t").standing());});
        c.run("46 true condition selects only true branch",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",conditionPlan(),"k1");activate(r,"p1",1,"k2");condition(r,"p1",1,"c",Map.of("x",new BoundValue("owner","ref","v1","5")),"k3");eq(StepStanding.READY,r.getStepReadiness("p1",1,"t").standing());eq(StepStanding.SKIPPED,r.getStepReadiness("p1",1,"f").standing());});
        c.run("47 human wait without basis remains WAITING_EXTERNAL",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",humanPlan(),"k1");activate(r,"p1",1,"k2");eq(StepStanding.WAITING_EXTERNAL,r.getStepReadiness("p1",1,"h").standing());});
        c.run("48 exact external human basis satisfies wait",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",humanPlan(),"k1");activate(r,"p1",1,"k2");ExternalBasis b=new ExternalBasis(BasisKind.HUMAN_DECISION,"HUMAN","approval-ref",PlanningOrchestrationAuthorityRuntime.sha256("subject"),"APPROVED",T);human(r,"p1",1,"h",b,"k3");eq(StepStanding.SATISFIED,r.getStepReadiness("p1",1,"h").standing());});

        c.run("49 readiness handoff binds exact causal refs",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");var h=r.readinessHandoff("p1",1,"s1");eq(f.ref.canonicalDigest(),h.workPlanningRefDigest());eq("s1",h.planStepRef().stepId());truth(h.canonicalDigest().length()==64);});
        c.run("50 Step requirements declare demand without grant truth",()->{ResourceDemand d=new ResourceDemand("cpu","2","cores","HARD");StepRequirements q=new StepRequirements(List.of("cap:x"),List.of(d),List.of(),List.of(),List.of(),List.of());truth(q.resourceDemand().size()==1);for(var rc:StepRequirements.class.getRecordComponents())truth(!rc.getName().toLowerCase(Locale.ROOT).contains("grant"));});
        c.run("51 Planning handoff contains no route/provider selection field",()->{for(var rc:ReadinessHandoff.class.getRecordComponents()){String n=rc.getName().toLowerCase(Locale.ROOT);truth(!n.contains("route")&&!n.contains("provider"));}});
        c.run("52 Planning handoff contains no executor assignment field",()->{for(var rc:ReadinessHandoff.class.getRecordComponents()){String n=rc.getName().toLowerCase(Locale.ROOT);truth(!n.contains("executor")&&!n.contains("assignment"));}});
        c.run("53 Planning handoff contains no job attempt lease fence fields",()->{for(var rc:ReadinessHandoff.class.getRecordComponents()){String n=rc.getName().toLowerCase(Locale.ROOT);truth(!n.contains("job")&&!n.contains("attempt")&&!n.contains("lease")&&!n.contains("fence"));}});
        c.run("54 Planning handoff contains no effect permission field",()->{for(var rc:ReadinessHandoff.class.getRecordComponents())truth(!rc.getName().toLowerCase(Locale.ROOT).contains("effect"));});
        c.run("55 Planning handoff contains no evidence standing field",()->{for(var rc:ReadinessHandoff.class.getRecordComponents())truth(!rc.getName().toLowerCase(Locale.ROOT).contains("evidence"));});
        c.run("56 unknown requirement refinement blocks activation",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");f.gate[0]=GateStanding.UNKNOWN;expect(IllegalStateException.class,()->activate(r,"p1",1,"k2"));});
        c.run("57 downstream facts stored only as associations",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1",AssociationKind.RESOURCE_GRANT,"grant-1","k3");eq("grant-1",r.listStepAssociations("p1",1,"s1").get(0).externalRef());eq(StepStanding.WAITING_EXTERNAL,r.getStepReadiness("p1",1,"s1").standing());});
        c.run("58 stale Plan handoff rejects after supersession",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");revision(r,"p1",1,f.ref,single(),"k3");activate(r,"p1",2,"k4");expect(IllegalStateException.class,()->r.readinessHandoff("p1",1,"s1"));});

        c.run("59 failed pre-append fault cannot expose successful mutation",()->{Fixture f=new Fixture();var r=f.runtime(()->{throw new IOException("injected");});expect(IOException.class,()->create(r,f.ref,"p1",single(),"k1"));eq(0,r.planIdentityCount());});
        c.run("60 full replay reconstructs identical state",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");String id=r.getPlan("p1",1).planRevisionId();var reopened=f.runtime();eq(id,reopened.getPlan("p1",1).planRevisionId());eq(PlanStanding.ACTIVE,reopened.getPlan("p1",1).standing());});
        c.run("61 corrupt journal fails closed",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");Files.writeString(f.log,"garbage\n",StandardCharsets.UTF_8,StandardOpenOption.APPEND);expect(CorruptStoreException.class,f::runtime);});
        c.run("62 truncated journal fails closed",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");byte[] b=Files.readAllBytes(f.log);Files.write(f.log,Arrays.copyOf(b,b.length-5));expect(CorruptStoreException.class,f::runtime);});
        c.run("63 hash-chain discontinuity fails closed",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");String s=Files.readString(f.log);int at=s.lastIndexOf('|')+1;char ch=s.charAt(at);s=s.substring(0,at)+(ch=='a'?'b':'a')+s.substring(at+1);Files.writeString(f.log,s);expect(CorruptStoreException.class,f::runtime);});
        c.run("64 compatible checkpoint validates after reconstruction",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");PlanningCheckpoint cp=checkpoint(r,"p1",1,"k3");var reopened=f.runtime();truth(reopened.validateCheckpoint("p1",1,cp));});
        c.run("65 wrong Plan checkpoint rejects",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");PlanningCheckpoint cp=checkpoint(r,"p1",1,"k3");create(r,f.ref,"p2",single(),"k4");truth(!r.validateCheckpoint("p2",1,cp));});
        c.run("66 concurrent exact duplicate mutation converges",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=single();String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("CreatePlan",f.ref.canonicalDigest(),"p1",p.digest());CommandMeta m=meta("same-concurrent",null,req);ExecutorService x=Executors.newFixedThreadPool(2);try{Future<PlanRevisionView>a=x.submit(()->r.createPlan(m,f.ref,"p1",p));Future<PlanRevisionView>b=x.submit(()->r.createPlan(m,f.ref,"p1",p));eq(a.get().planRevisionId(),b.get().planRevisionId());eq(1,r.planIdentityCount());}finally{x.shutdownNow();}});
        c.run("67 concurrent conflicting activations yield one canonical current Plan",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");create(r,f.ref,"p2",single(),"k2");ExecutorService x=Executors.newFixedThreadPool(2);try{Future<Boolean>a=x.submit(()->tryActivate(r,"p1",1,"ka"));Future<Boolean>b=x.submit(()->tryActivate(r,"p2",1,"kb"));int wins=(a.get()?1:0)+(b.get()?1:0);eq(1,wins);truth(r.getCurrentPlanForWork("work-1")!=null);}finally{x.shutdownNow();}});
        c.run("68 crash-after-commit replay does not duplicate",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");long rev=r.registryRevision();var reopened=f.runtime();eq(rev,reopened.registryRevision());eq(1,reopened.planIdentityCount());});

        c.run("69 all required Steps satisfied produces COMPLETION_READY",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1","k3");basis(r,"p1",1,"s1",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k4");eq(PlanStanding.COMPLETION_READY,complete(r,"p1",1,"k5").standing());});
        c.run("70 required failed Step without partial policy blocks completion",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1","k3");basis(r,"p1",1,"s1",BasisKind.OWNER_COMPLETION,StepStanding.FAILED,"k4");expect(IllegalStateException.class,()->complete(r,"p1",1,"k5"));});
        c.run("71 optional failure allowed only with locked partial policy",()->{Fixture f=new Fixture();var r=f.runtime();PlanCandidate p=candidate(List.of(exec("s1",CompletionRole.OPTIONAL)),List.of(),Map.of(),"partial-policy");create(r,f.ref,"p1",p,"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1","k3");basis(r,"p1",1,"s1",BasisKind.OWNER_COMPLETION,StepStanding.FAILED,"k4");eq(PlanStanding.COMPLETION_READY,complete(r,"p1",1,"k5").standing());});
        c.run("72 required UNKNOWN blocks completion",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1","k3");basis(r,"p1",1,"s1",BasisKind.OWNER_COMPLETION,StepStanding.UNKNOWN,"k4");expect(IllegalStateException.class,()->complete(r,"p1",1,"k5"));});
        c.run("73 runtime exit alone cannot satisfy Step",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1","k3");expect(IllegalArgumentException.class,()->basis(r,"p1",1,"s1",BasisKind.RUNTIME_EXIT,StepStanding.SATISFIED,"k4"));});
        c.run("74 telemetry/specialist existence alone cannot satisfy Step",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1","k3");expect(IllegalArgumentException.class,()->basis(r,"p1",1,"s1",BasisKind.TELEMETRY,StepStanding.SATISFIED,"k4"));});
        c.run("75 COMPLETION_READY does not mutate Work or Goal identity",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1","k3");basis(r,"p1",1,"s1",BasisKind.OWNER_COMPLETION,StepStanding.SATISFIED,"k4");complete(r,"p1",1,"k5");eq("work-1",r.getPlan("p1",1).workId());eq("goal-1",r.readinessSafeGoalId("p1",1));});
        c.run("76 same-Work same-Goal replan creates successor",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");eq(2,revision(r,"p1",1,f.ref,linear(),"k3").planRevision());});
        c.run("77 replan cannot widen hard constraints",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");revision(r,"p1",1,f.ref,linear(),"k3");f.gate[0]=GateStanding.INVALID;expect(IllegalStateException.class,()->activate(r,"p1",2,"k4"));});
        c.run("78 Plan supersession does not assert downstream cancellation",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");associate(r,"p1",1,"s1",AssociationKind.JOB,"job-1","k3");revision(r,"p1",1,f.ref,single(),"k4");activate(r,"p1",2,"k5");eq("job-1",r.listStepAssociations("p1",1,"s1").get(0).externalRef());eq(PlanStanding.SUPERSEDED,r.getPlan("p1",1).standing());});
        c.run("79 upstream invalidation stops new handoff and can mark replan required",()->{Fixture f=new Fixture();var r=f.runtime();create(r,f.ref,"p1",single(),"k1");activate(r,"p1",1,"k2");f.currentDigest[0]=PlanningOrchestrationAuthorityRuntime.sha256("new-work-truth");expect(IllegalStateException.class,()->r.readinessHandoff("p1",1,"s1"));eq(PlanStanding.REPLAN_REQUIRED,replanRequired(r,"p1",1,"k3").standing());});
        c.run("80 historical donor standing cannot substitute for exact subject",()->{truth(!PlanningOrchestrationAuthorityRuntime.CONTRACT_ID.contains("F-WP"));truth(!PlanningOrchestrationAuthorityRuntime.CONTRACT_ID.contains("021I"));truth(PlanningOrchestrationAuthorityRuntime.MAX_STEPS==1024);});

        if(c.count!=80)throw new AssertionError("case denominator mismatch "+c.count);
        System.out.println("PASS FOUNDATION_PLANNING_ORCHESTRATION cases=80");
    }

    private static WorkPlanningRefV1 workRef(String workId,long entityRevision,WorkLifecycle lifecycle,String goalId,int goalRevision,long registry){
        String gd=PlanningOrchestrationAuthorityRuntime.sha256("goal-content-"+goalId+"-"+goalRevision);String val=PlanningOrchestrationAuthorityRuntime.sha256("keel-receipt-"+goalId+"-"+goalRevision);String cd=PlanningOrchestrationAuthorityRuntime.sha256("keel-contract");var g=new WorkProjectAuthorityRuntime.GovernedGoalRefV1(goalId,goalRevision,"goal-rev-"+goalId+"-"+goalRevision,gd,val,"FOUNDATION-KEEL","1",cd,null,registry);String goalRefDigest=WorkProjectAuthorityRuntime.goalRefDigest(g);String canonical=PlanningOrchestrationAuthorityRuntime.sha256(workId+"|"+entityRevision+"|"+goalRefDigest+"|<null>|<null>|"+lifecycle+"||"+registry);return new WorkPlanningRefV1(workId,entityRevision,g,null,null,lifecycle,List.of(),registry,canonical);
    }
    private static StepRequirements req(){return new StepRequirements(List.of("capability:generic"),List.of(new ResourceDemand("cpu","1","unit","HARD")),List.of("policy:default"),List.of(),List.of(),List.of("keel:constraints"));}
    private static StepSpec exec(String id,CompletionRole role){return new StepSpec(id,1,StepKind.EXECUTION,role,req(),null,null,"basis:"+id);}
    private static PlanCandidate single(){return candidate(List.of(exec("s1",CompletionRole.REQUIRED)),List.of(),Map.of(),null);}
    private static PlanCandidate linear(){return candidate(List.of(exec("a",CompletionRole.REQUIRED),exec("b",CompletionRole.REQUIRED)),List.of(new EdgeSpec("e1","a","b",EdgeGate.ON_SATISFIED)),Map.of(),null);}
    private static PlanCandidate humanPlan(){HumanWaitSpec h=new HumanWaitSpec("approval-ref","HUMAN",PlanningOrchestrationAuthorityRuntime.sha256("subject"),List.of("APPROVED"));StepSpec s=new StepSpec("h",1,StepKind.HUMAN_WAIT,CompletionRole.REQUIRED,req(),null,h,"basis:h");return candidate(List.of(s),List.of(),Map.of(),null);}
    private static PlanCandidate conditionPlan(){ConditionSpec cs=new ConditionSpec("cond","SM_PREDICATE_V1",PredicateNode.op("EQ",PredicateNode.ref("x"),PredicateNode.constant("5")));StepSpec c=new StepSpec("c",1,StepKind.CONDITION,CompletionRole.REQUIRED,req(),cs,null,"cond");StepSpec t=exec("t",CompletionRole.CONDITIONAL),f=exec("f",CompletionRole.CONDITIONAL);List<EdgeSpec> e=List.of(new EdgeSpec("et","c","t",EdgeGate.ON_CONDITION_TRUE),new EdgeSpec("ef","c","f",EdgeGate.ON_CONDITION_FALSE));return candidate(List.of(c,t,f),e,Map.of(),"partial");}
    private static PlanCandidate parallelJoin(JoinKind kind,int n){StepSpec a=exec("a",CompletionRole.OPTIONAL),b=exec("b",CompletionRole.OPTIONAL);StepSpec j=new StepSpec("j",1,StepKind.JOIN,CompletionRole.REQUIRED,req(),null,null,"join");List<EdgeSpec> e=List.of(new EdgeSpec("e1","a","j",EdgeGate.ON_SATISFIED),new EdgeSpec("e2","b","j",EdgeGate.ON_SATISFIED));return candidate(List.of(a,b,j),e,Map.of("j",new JoinSpec(kind,n)),"partial");}
    private static PlanCandidate chain(int n){List<StepSpec>s=new ArrayList<>();List<EdgeSpec>e=new ArrayList<>();for(int i=0;i<n;i++){s.add(exec("s"+i,CompletionRole.OPTIONAL));if(i>0)e.add(new EdgeSpec("e"+i,"s"+(i-1),"s"+i,EdgeGate.ON_SATISFIED));}return candidate(s,e,Map.of(),"partial");}
    private static PlanCandidate edgeBoundary(int edges){List<StepSpec>s=new ArrayList<>();for(int i=0;i<128;i++)s.add(exec("r"+i,CompletionRole.OPTIONAL));for(int i=0;i<129;i++)s.add(exec("t"+i,CompletionRole.OPTIONAL));List<EdgeSpec>e=new ArrayList<>();Map<String,JoinSpec>j=new HashMap<>();int k=0;outer:for(int r=0;r<128;r++){for(int off=0;off<64;off++){if(k>=edges)break outer;int t=(r+off)%128;e.add(new EdgeSpec("e"+k,"r"+r,"t"+t,EdgeGate.ON_SATISFIED));k++;}}if(edges>8192)e.add(new EdgeSpec("e8192","r0","t128",EdgeGate.ON_SATISFIED));Map<String,Integer>incoming=new HashMap<>();for(EdgeSpec x:e)incoming.merge(x.toStepId(),1,Integer::sum);for(var x:incoming.entrySet())if(x.getValue()>1)j.put(x.getKey(),new JoinSpec(JoinKind.ALL,0));return candidate(s,e,j,"partial");}
    private static PlanCandidate candidate(List<StepSpec>s,List<EdgeSpec>e,Map<String,JoinSpec>j,String partial){return new PlanCandidate(s,e,j,"plan-completion-v1",partial);}

    private static CommandMeta meta(String key,Long expected,String request){return new CommandMeta("cmd-"+(++command),key,"principal:test",expected,PlanningOrchestrationAuthorityRuntime.CONTRACT_ID,PlanningOrchestrationAuthorityRuntime.CONTRACT_VERSION,CONTRACT_DIGEST,request);}
    private static PlanRevisionView create(PlanningOrchestrationAuthorityRuntime r,WorkPlanningRefV1 w,String id,PlanCandidate p,String key) throws Exception {String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("CreatePlan",w.canonicalDigest(),id,p.digest());return r.createPlan(meta(key,null,req),w,id,p);}
    private static PlanRevisionView revision(PlanningOrchestrationAuthorityRuntime r,String id,int parent,WorkPlanningRefV1 w,PlanCandidate p,String key) throws Exception {long er=r.getPlan(id,parent).orchestrationRevision();String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("CreatePlanRevision",id,Integer.toString(parent),w.canonicalDigest(),p.digest());return r.createPlanRevision(meta(key,er,req),id,parent,w,p);}
    private static PlanRevisionView activate(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String key) throws Exception {var v=r.getPlan(id,rev);String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("ActivatePlanRevision",id,Integer.toString(rev),v.planContentDigest());return r.activatePlanRevision(meta(key,v.orchestrationRevision(),req),id,rev);}
    private static boolean tryActivate(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String key){try{activate(r,id,rev,key);return true;}catch(Exception e){return false;}}
    private static PlanRevisionView associate(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String step,String key) throws Exception {return associate(r,id,rev,step,AssociationKind.JOB,"job:"+step,key);}
    private static PlanRevisionView associate(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String step,AssociationKind kind,String ref,String key) throws Exception {var v=r.getPlan(id,rev);StepAssociation a=new StepAssociation("assoc:"+key,step,kind,"DOWNSTREAM",ref,"v1",T);String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("RecordStepAssociation",id,Integer.toString(rev),step,a.associationId(),a.kind().name(),a.ownerAuthority(),a.externalRef(),a.versionOrDigest());return r.recordStepAssociation(meta(key,v.orchestrationRevision(),req),id,rev,step,a);}
    private static PlanRevisionView basis(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String step,BasisKind kind,StepStanding standing,String key) throws Exception {var v=r.getPlan(id,rev);ExternalBasis b=new ExternalBasis(kind,"OWNER","basis:"+key,PlanningOrchestrationAuthorityRuntime.sha256("basis-subject-"+key),standing.name(),T);String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("RecordStepBasis",id,Integer.toString(rev),step,b.digest(),standing.name());return r.recordStepBasis(meta(key,v.orchestrationRevision(),req),id,rev,step,b,standing);}
    private static ConditionReceipt condition(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String step,Map<String,BoundValue> inputs,String key) throws Exception {var v=r.getPlan(id,rev);StepSpec s=conditionPlan().steps().stream().filter(x->x.stepId().equals(step)).findFirst().orElseThrow();String in=inputs.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->e.getKey()+":"+e.getValue().digest()).reduce((a,b)->a+"|"+b).orElse("");String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("RecordConditionEvaluation",id,Integer.toString(rev),step,s.conditionSpec().digest(),in);return r.recordConditionEvaluation(meta(key,v.orchestrationRevision(),req),id,rev,step,inputs);}
    private static PlanRevisionView human(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String step,ExternalBasis b,String key) throws Exception {var v=r.getPlan(id,rev);String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("RecordHumanWaitBasis",id,Integer.toString(rev),step,b.digest());return r.recordHumanWaitBasis(meta(key,v.orchestrationRevision(),req),id,rev,step,b);}
    private static PlanRevisionView complete(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String key) throws Exception {var v=r.getPlan(id,rev);String states=digestStates(v.stepStates());String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("EvaluatePlanCompletion",id,Integer.toString(rev),"plan-completion-v1",states);return r.evaluatePlanCompletion(meta(key,v.orchestrationRevision(),req),id,rev);}
    private static PlanningCheckpoint checkpoint(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String key) throws Exception {var v=r.getPlan(id,rev);String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("RecordPlanningCheckpoint",id,Integer.toString(rev),Long.toString(v.orchestrationRevision()),digestStates(v.stepStates()));return r.recordPlanningCheckpoint(meta(key,v.orchestrationRevision(),req),id,rev);}
    private static PlanRevisionView block(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String key) throws Exception {var v=r.getPlan(id,rev);String reason="blocker";String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("MarkPlanBlocked",id,Integer.toString(rev),PlanStanding.BLOCKED.name(),reason);return r.markPlanBlocked(meta(key,v.orchestrationRevision(),req),id,rev,reason);}
    private static PlanRevisionView replanRequired(PlanningOrchestrationAuthorityRuntime r,String id,int rev,String key) throws Exception {var v=r.getPlan(id,rev);String reason="upstream-invalidated";String req=PlanningOrchestrationAuthorityRuntime.payloadDigest("MarkPlanReplanRequired",id,Integer.toString(rev),PlanStanding.REPLAN_REQUIRED.name(),reason);return r.markPlanReplanRequired(meta(key,v.orchestrationRevision(),req),id,rev,reason);}
    private static String digestStates(Map<String,StepState> m){String raw=m.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->e.getKey()+":"+e.getValue().standing()+":"+nv(e.getValue().basisDigest())+":"+nv(e.getValue().conditionReceiptDigest())+":"+e.getValue().stateRevision()).reduce((a,b)->a+"|"+b).orElse("");return PlanningOrchestrationAuthorityRuntime.sha256(raw);}
    private static String nv(String s){return s==null?"<null>":s;}
    private static void eq(Object a,Object b){if(!Objects.equals(a,b))throw new AssertionError("expected "+a+" == "+b);}
    private static void truth(boolean v){if(!v)throw new AssertionError("expected true");}
    private static <T extends Throwable> void expect(Class<T> type,ThrowingRunnable r) throws Exception {try{r.run();}catch(Throwable t){if(type.isInstance(t))return;throw t;}throw new AssertionError("expected "+type.getSimpleName());}
}
