'use strict';
const crypto=require('crypto');const fs=require('fs');const path=require('path');const{spawnSync}=require('child_process');
const workspace=process.env.GITHUB_WORKSPACE||process.cwd();const packageRoot='system-master/f-wp-008';const runId=process.env.GITHUB_RUN_ID||'local';const evidenceDir=path.join(process.env.RUNNER_TEMP||path.join(workspace,'.tmp'),`system-master-fwp008-${runId}`);fs.mkdirSync(evidenceDir,{recursive:true});
const write=(n,v)=>fs.writeFileSync(path.join(evidenceDir,n),String(v).endsWith('\n')?String(v):String(v)+'\n','utf8');const sha256=b=>crypto.createHash('sha256').update(b).digest('hex');
function git(args,encoding='utf8'){const r=spawnSync('git',['-c',`safe.directory=${workspace}`,...args],{cwd:workspace,encoding,shell:false,windowsHide:true});if(r.error||r.status!==0)throw new Error(`GIT_FAILED:${args.join(' ')}:${r.error?r.error.message:String(r.stderr||r.stdout)}`);return r.stdout;}
function run(cmd,args){const r=spawnSync(cmd,args,{cwd:workspace,encoding:'utf8',shell:false,windowsHide:true});const out=`${r.stdout||''}${r.stderr||''}`;if(r.error||r.status!==0)throw new Error(`${cmd.toUpperCase()}_FAILED:${r.error?r.error.message:out}`);return out;}
function exactSet(a,e,l){a=[...a].sort();e=[...e].sort();if(JSON.stringify(a)!==JSON.stringify(e))throw new Error(`${l}_MISMATCH actual=${a} expected=${e}`);}
try{
 const head=git(['rev-parse','HEAD']).trim();const baseline=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','BASELINE-BINDING.json'),'utf8'));
 if(baseline.primary_predecessor.qualified_commit!=='2bf878a012b5e0ad2bb3ba3602996d57104f8d34')throw new Error('F_WP_007_BASELINE_BINDING_MISMATCH');git(['merge-base','--is-ancestor',baseline.primary_predecessor.qualified_commit,'HEAD']);
 const req=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','REQUIREMENTS.json'),'utf8'));exactSet(req.requirements.map(x=>x.id),['F-RQ-024','F-RQ-025','F-RQ-027','F-RQ-040','F-RQ-058'],'F_WP_008_REQUIREMENTS');
 const gate=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','CONTRACT-GATE-021T.json'),'utf8'));
 if(gate.status!=='SATISFIED_FOR_BOUNDED_F_WP_008_SCOPE_WITH_021T_R1_BUILD_SPEC_RESIDUAL')throw new Error('021T_GATE_STATUS_MISMATCH');if(gate['021T'].semantic_architecture_status!=='CLOSED')throw new Error('021T_SEMANTIC_ARCH_NOT_CLOSED');if(gate['021T'].r1_build_spec_status!=='INCOMPLETE')throw new Error('021T_RESIDUAL_WAS_HIDDEN_OR_CHANGED');if(gate['021T'].computer_implementation_status!=='NOT_STARTED'||gate['021T'].executable_qualification_status!=='NOT_STARTED')throw new Error('021T_FALSE_IMPLEMENTATION_CLAIM');
 write('contract-gate.txt',`gate=${gate.status}\n021T_semantic_architecture=CLOSED\n021T_r1_build_spec=INCOMPLETE\n021T_computer_implementation=NOT_STARTED\nresidual_preserved=YES`);
 const manifest=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','SOURCE-SLICE-MANIFEST.json'),'utf8'));for(const e of manifest.files){const repoPath=`${packageRoot}/${e.path}`;const bytes=git(['show',`HEAD:${repoPath}`],null);if(bytes.length!==e.size)throw new Error(`SEALED_SIZE_MISMATCH:${e.path}:${bytes.length}:${e.size}`);const digest=sha256(bytes);if(digest!==e.sha256)throw new Error(`SEALED_HASH_MISMATCH:${e.path}:${digest}:${e.sha256}`);}
 const predecessor=run('node',['.github/scripts/fwp007-qualify.js']);if(!predecessor.includes('PASS F-WP-007 tests=46 requirements=9'))throw new Error(`F_WP_007_REGRESSION_NOT_PROVEN:${predecessor}`);write('dependency-fwp007.txt',predecessor);
 const classes=path.join(evidenceDir,'classes');fs.mkdirSync(classes,{recursive:true});const srcBase=path.join(workspace,packageRoot,'src','main','java','org','systemmaster','core');const testSource=path.join(workspace,packageRoot,'src','test','java','org','systemmaster','core','Fwp008QualificationTest.java');const sources=['VerificationEvidenceContracts.java','EvidencePublisher.java','IntegrityQuarantineService.java','ChangeVerifier.java'].map(x=>path.join(srcBase,x));const compileOut=run('javac',['-encoding','UTF-8','-d',classes,...sources,testSource]);write('compile.txt',compileOut||'javac=PASS');const testOut=run('java',['-cp',classes,'org.systemmaster.core.Fwp008QualificationTest']);write('qualification.txt',testOut);if(!testOut.includes('PASS F-WP-008 tests=38 requirements=5'))throw new Error(`QUALIFICATION_SENTINEL_MISSING:${testOut}`);
 write('subject.txt',[`objective=SYSTEM-MASTER-F-WP-008-CONTRACT-GATE-VERIFY-A01-IMPLEMENT-QUALIFY-001`,`commit=${head}`,`branch=${process.env.GITHUB_REF_NAME||''}`,`runner=${process.env.RUNNER_NAME||''}`,`machine=${process.env.COMPUTERNAME||''}`,`predecessor_commit=${baseline.primary_predecessor.qualified_commit}`,`predecessor_run=${baseline.primary_predecessor.workflow_run_id}`,`predecessor_evidence_sha256=${baseline.primary_predecessor.evidence_artifact_sha256}`].join('\n'));write('result.txt','result=PASS\ntests=38\nrequirements=5\nfwp007_regression=PASS\ncontract_gate_021T=BOUNDED_PASS_WITH_R1_BUILD_SPEC_RESIDUAL');console.log('PASS F-WP-008 tests=38 requirements=5');console.log(`evidence_dir=${evidenceDir}`);
}catch(error){const detail=error&&error.stack?error.stack:String(error);write('failure.txt',detail);write('result.txt','result=FAIL_OR_INCOMPLETE');console.error(detail);process.exit(1);}
