'use strict';
const crypto=require('crypto');const fs=require('fs');const path=require('path');const{spawnSync}=require('child_process');
const workspace=process.env.GITHUB_WORKSPACE||process.cwd();const packageRoot='system-master/f-wp-009';const runId=process.env.GITHUB_RUN_ID||'local';const evidenceDir=path.join(process.env.RUNNER_TEMP||path.join(workspace,'.tmp'),`system-master-fwp009-${runId}`);fs.mkdirSync(evidenceDir,{recursive:true});
const write=(n,v)=>fs.writeFileSync(path.join(evidenceDir,n),String(v).endsWith('\n')?String(v):String(v)+'\n','utf8');const sha256=b=>crypto.createHash('sha256').update(b).digest('hex');
function git(args,encoding='utf8'){const r=spawnSync('git',['-c',`safe.directory=${workspace}`,...args],{cwd:workspace,encoding,shell:false,windowsHide:true});if(r.error||r.status!==0)throw new Error(`GIT_FAILED:${args.join(' ')}:${r.error?r.error.message:String(r.stderr||r.stdout)}`);return r.stdout;}
function run(cmd,args){const r=spawnSync(cmd,args,{cwd:workspace,encoding:'utf8',shell:false,windowsHide:true});const out=`${r.stdout||''}${r.stderr||''}`;if(r.error||r.status!==0)throw new Error(`${cmd.toUpperCase()}_FAILED:${r.error?r.error.message:out}`);return out;}
function exactSet(a,e,l){a=[...a].sort();e=[...e].sort();if(JSON.stringify(a)!==JSON.stringify(e))throw new Error(`${l}_MISMATCH actual=${a} expected=${e}`);}
try{
 const head=git(['rev-parse','HEAD']).trim();const baseline=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','BASELINE-BINDING.json'),'utf8'));
 if(baseline.lineage_predecessor.qualified_commit!=='eab69123ebda547fd5ae065289c253b4620f5d45')throw new Error('F_WP_008_BASELINE_BINDING_MISMATCH');
 for(const c of ['eab69123ebda547fd5ae065289c253b4620f5d45','2bf878a012b5e0ad2bb3ba3602996d57104f8d34','b1f00e624dbd9a8c779dc2c4c210ec6a7e1dd94e'])git(['merge-base','--is-ancestor',c,'HEAD']);
 const req=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','REQUIREMENTS.json'),'utf8'));exactSet(req.requirements.map(x=>x.id),['F-RQ-031','F-RQ-032','F-RQ-042','F-RQ-048'],'F_WP_009_REQUIREMENTS');
 const gate=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','CONTRACT-GATE-021K-P-R-Y.json'),'utf8'));
 if(gate.status!=='SATISFIED_FOR_BOUNDED_F_WP_009_SCOPE_WITH_021Y_PARENT_BUILD_SPEC_RESIDUAL')throw new Error('CONTRACT_GATE_STATUS_MISMATCH');
 if(gate['021K'].architecture_build_spec_status!=='CLOSED_REQUALIFIED_DEPENDENCY_VALID'||gate['021P'].architecture_build_spec_status!=='CLOSED_ZERO_MATERIAL_RESIDUALS'||gate['021R'].architecture_build_spec_status!=='CLOSED_REQUALIFIED_DEPENDENCY_VALID')throw new Error('CLOSED_GATE_STATUS_MISMATCH');
 if(gate['021Y'].parent_build_spec_status!=='INCOMPLETE_ADVANCEMENT_BLOCKED'||gate['021Y'].r1a_source_surface_adapter_contract!=='FROZEN_READ_OBSERVE_ONLY'||gate['021Y'].computer_implementation_status!=='NOT_STARTED')throw new Error('021Y_RESIDUAL_HIDDEN_OR_CHANGED');
 write('contract-gate.txt',`gate=${gate.status}\n021K=CLOSED_REQUALIFIED\n021P=CLOSED_ZERO_RESIDUALS\n021R=CLOSED_REQUALIFIED\n021Y_parent=INCOMPLETE_ADVANCEMENT_BLOCKED\n021Y_adapter=FROZEN_READ_OBSERVE_ONLY\nresidual_preserved=YES`);
 const manifest=JSON.parse(fs.readFileSync(path.join(workspace,packageRoot,'control','SOURCE-SLICE-MANIFEST.json'),'utf8'));for(const e of manifest.files){const repoPath=`${packageRoot}/${e.path}`;const bytes=git(['show',`HEAD:${repoPath}`],null);if(bytes.length!==e.size)throw new Error(`SEALED_SIZE_MISMATCH:${e.path}:${bytes.length}:${e.size}`);const digest=sha256(bytes);if(digest!==e.sha256)throw new Error(`SEALED_HASH_MISMATCH:${e.path}:${digest}:${e.sha256}`);}
 const predecessor=run('node',['.github/scripts/fwp008-qualify.js']);if(!predecessor.includes('PASS F-WP-008 tests=38 requirements=5'))throw new Error(`F_WP_008_REGRESSION_NOT_PROVEN:${predecessor}`);write('dependency-fwp008.txt',predecessor);
 const classes=path.join(evidenceDir,'classes');fs.mkdirSync(classes,{recursive:true});const srcBase=path.join(workspace,packageRoot,'src','main','java','org','systemmaster','core');const testSource=path.join(workspace,packageRoot,'src','test','java','org','systemmaster','core','Fwp009QualificationTest.java');const sources=['RecoveryEligibilityContracts.java','RecoveryCoordinator.java'].map(x=>path.join(srcBase,x));const compileOut=run('javac',['-encoding','UTF-8','-d',classes,...sources,testSource]);write('compile.txt',compileOut||'javac=PASS');const testOut=run('java',['-cp',classes,'org.systemmaster.core.Fwp009QualificationTest']);write('qualification.txt',testOut);if(!testOut.includes('PASS F-WP-009 tests=40 requirements=4'))throw new Error(`QUALIFICATION_SENTINEL_MISSING:${testOut}`);
 write('subject.txt',[`objective=SYSTEM-MASTER-F-WP-009-CONTRACT-GATE-VERIFY-A01-IMPLEMENT-QUALIFY-001`,`commit=${head}`,`branch=${process.env.GITHUB_REF_NAME||''}`,`runner=${process.env.RUNNER_NAME||''}`,`machine=${process.env.COMPUTERNAME||''}`,`lineage_predecessor_commit=${baseline.lineage_predecessor.qualified_commit}`,`lineage_predecessor_run=${baseline.lineage_predecessor.workflow_run_id}`,`lineage_predecessor_evidence_sha256=${baseline.lineage_predecessor.evidence_artifact_sha256}`].join('\n'));
 write('result.txt','result=PASS\ntests=40\nrequirements=4\nfwp008_regression=PASS\ncontract_gate_021K_P_R=PASS\ncontract_gate_021Y=BOUNDED_PASS_WITH_PARENT_BUILD_SPEC_RESIDUAL');console.log('PASS F-WP-009 tests=40 requirements=4');console.log(`evidence_dir=${evidenceDir}`);
}catch(error){const detail=error&&error.stack?error.stack:String(error);write('failure.txt',detail);write('result.txt','result=FAIL_OR_INCOMPLETE');console.error(detail);process.exit(1);}
