'use strict';
const crypto=require('crypto'),fs=require('fs'),path=require('path');const {spawnSync}=require('child_process');
const ws=process.env.GITHUB_WORKSPACE||process.cwd(),root='system-master/g-wp-006',runId=process.env.GITHUB_RUN_ID||'local';
const evidenceDir=path.join(process.env.RUNNER_TEMP||path.join(ws,'.tmp'),`system-master-gwp006-${runId}`);fs.mkdirSync(evidenceDir,{recursive:true});
const write=(n,v)=>fs.writeFileSync(path.join(evidenceDir,n),String(v).endsWith('\n')?String(v):String(v)+'\n','utf8');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function git(args,encoding='utf8',cwd=ws){const r=spawnSync('git',['-c',`safe.directory=${cwd}`,...args],{cwd,encoding,shell:false,windowsHide:true});if(r.error||r.status!==0)throw new Error(`GIT_FAILED:${args.join(' ')}:${r.error?r.error.message:String(r.stderr||r.stdout)}`);return r.stdout;}
function run(cmd,args,cwd=ws,env=process.env){const r=spawnSync(cmd,args,{cwd,encoding:'utf8',shell:false,windowsHide:true,env});const out=`${r.stdout||''}${r.stderr||''}`;if(r.error||r.status!==0)throw new Error(`${cmd.toUpperCase()}_FAILED:${r.error?r.error.message:out}`);return out;}
function seteq(a,b,n){a=[...a].sort();b=[...b].sort();if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(`${n}_MISMATCH:${a}:${b}`);}
try{
 const head=git(['rev-parse','HEAD']).trim();const base=JSON.parse(fs.readFileSync(path.join(ws,root,'control','BASELINE-BINDING.json'),'utf8'));const pred=base.qualified_predecessor.qualified_commit;
 if(pred!=='b4046b6eb6e8813c8dc5860d549d56c27daf574e'||base.qualified_predecessor.workflow_run_id!==34255660317||base.qualified_predecessor.evidence_artifact_id!==10068201260||base.qualified_predecessor.evidence_artifact_sha256!=='0ca666dd650c3706e8843f7b286f34d853cb9da82d64be95427de38e0a675edb')throw new Error('G_WP_005_BASELINE_MISMATCH');git(['merge-base','--is-ancestor',pred,'HEAD']);
 const pkg=JSON.parse(fs.readFileSync(path.join(ws,root,'control','PACKAGE-CONTRACT.json'),'utf8'));if(pkg.id!=='G-WP-006')throw new Error('PACKAGE_ID_DRIFT');seteq(pkg.components,['ResumeCoordinator','RecoveryPlanner'],'PACKAGE_COMPONENTS');seteq(pkg.data,['RecoveryPlan','ExecutionAttemptRef','RecordedDecision'],'PACKAGE_DATA');seteq(pkg.contracts,['StartResume','RecordResumeOutcome','MarkRecovered'],'PACKAGE_CONTRACTS');seteq(pkg.tests,['REPLAY','STATE_MACHINE','PROCESS_KILL','SOAK'],'PACKAGE_TESTS');
 const req=JSON.parse(fs.readFileSync(path.join(ws,root,'control','REQUIREMENTS.json'),'utf8'));seteq(req.requirements.map(x=>x.id),['G-RQ-003','G-RQ-033','G-RQ-034'],'G_WP_006_REQUIREMENTS');
 const mf=JSON.parse(fs.readFileSync(path.join(ws,root,'control','SOURCE-SLICE-MANIFEST.json'),'utf8'));if(mf.expected_test_count!==50||mf.expected_requirement_count!==3||mf.production_authorized!==false)throw new Error('MANIFEST_METADATA_MISMATCH');for(const e of mf.files){const bytes=git(['show',`HEAD:${root}/${e.path}`],null);if(bytes.length!==e.size)throw new Error(`SEALED_SIZE_MISMATCH:${e.path}:${bytes.length}:${e.size}`);const h=hash(bytes);if(h!==e.sha256)throw new Error(`SEALED_HASH_MISMATCH:${e.path}:${h}:${e.sha256}`);}
 const dep=path.join(process.env.RUNNER_TEMP||path.join(ws,'.tmp'),`system-master-gwp005-dependency-${runId}`);try{if(fs.existsSync(dep))git(['worktree','remove','--force',dep]);git(['worktree','add','--detach',dep,pred]);const r=spawnSync('node',['.github/scripts/gwp005-qualify.js'],{cwd:dep,encoding:'utf8',shell:false,windowsHide:true,env:{...process.env,GITHUB_WORKSPACE:dep,GITHUB_REF_NAME:'dependency-gwp005'}});const out=`${r.stdout||''}${r.stderr||''}`;if(r.error||r.status!==0||!out.includes('PASS G-WP-005 tests=50 requirements=4'))throw new Error(`G_WP_005_REGRESSION_NOT_PROVEN:${r.error?r.error.message:out}`);write('dependency-gwp005.txt',out);}finally{try{git(['worktree','remove','--force',dep]);}catch(_){}}
 const classes=path.join(evidenceDir,'classes');fs.mkdirSync(classes,{recursive:true});let sources=[];for(const id of ['g-wp-002','g-wp-003','g-wp-004','g-wp-005','g-wp-006']){const d=path.join(ws,'system-master',id,'src','main','java','org','systemmaster','continuity');sources.push(...fs.readdirSync(d).filter(x=>x.endsWith('.java')).sort().map(x=>path.join(d,x)));}const test=path.join(ws,root,'src','test','java','org','systemmaster','continuity','Gwp006QualificationTest.java');write('compile.txt',run('javac',['-encoding','UTF-8','-d',classes,...sources,test])||'javac=PASS');const out=run('java',['-cp',classes,'org.systemmaster.continuity.Gwp006QualificationTest']);write('qualification.txt',out);if(!out.includes('PASS G-WP-006 tests=50 requirements=3'))throw new Error(`QUALIFICATION_SENTINEL_MISSING:${out}`);
 write('subject.txt',[`objective=${base.objective}`,`commit=${head}`,`branch=${process.env.GITHUB_REF_NAME||''}`,`runner=${process.env.RUNNER_NAME||''}`,`machine=${process.env.COMPUTERNAME||''}`,`predecessor_commit=${pred}`,`predecessor_run=${base.qualified_predecessor.workflow_run_id}`,`predecessor_artifact=${base.qualified_predecessor.evidence_artifact_id}`,`predecessor_evidence_sha256=${base.qualified_predecessor.evidence_artifact_sha256}`].join('\n'));write('result.txt','result=PASS\ntests=50\nrequirements=3\ngwp005_regression=PASS\nreplay=PASS\nstate_machine=PASS\nprocess_kill=PASS\nsoak=PASS\nmilestone_testing=true\nproduction_authorized=false');console.log('PASS G-WP-006 tests=50 requirements=3');console.log(`evidence_dir=${evidenceDir}`);
}catch(e){const d=e&&e.stack?e.stack:String(e);write('failure.txt',d);write('result.txt','result=FAIL_OR_INCOMPLETE');console.error(d);process.exit(1);}
