'use strict';
const fs=require('fs'),path=require('path'); const {spawnSync}=require('child_process');
const ws=process.env.GITHUB_WORKSPACE||process.cwd(), root='system-master/g-wp-007', runId=process.env.GITHUB_RUN_ID||'local';
const evidenceDir=path.join(process.env.RUNNER_TEMP||path.join(ws,'.tmp'),`system-master-gwp007-${runId}`); fs.mkdirSync(evidenceDir,{recursive:true});
const write=(n,v)=>fs.writeFileSync(path.join(evidenceDir,n),String(v).endsWith('\n')?String(v):String(v)+'\n','utf8');
function git(args,encoding='utf8',cwd=ws){const r=spawnSync('git',['-c',`safe.directory=${cwd}`,...args],{cwd,encoding,shell:false,windowsHide:true});if(r.error||r.status!==0)throw new Error(`GIT_FAILED:${args.join(' ')}:${r.error?r.error.message:String(r.stderr||r.stdout)}`);return r.stdout;}
function run(cmd,args,cwd=ws,env=process.env){const r=spawnSync(cmd,args,{cwd,encoding:'utf8',shell:false,windowsHide:true,env});const out=`${r.stdout||''}${r.stderr||''}`;if(r.error||r.status!==0)throw new Error(`${cmd.toUpperCase()}_FAILED:${r.error?r.error.message:out}`);return out;}
function seteq(a,b,n){a=[...a].sort();b=[...b].sort();if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(`${n}_MISMATCH:${a}:${b}`);}
try{
 const head=git(['rev-parse','HEAD']).trim(); const base=JSON.parse(fs.readFileSync(path.join(ws,root,'control','BASELINE-BINDING.json'),'utf8')); const pred=base.qualified_lineage_predecessor.qualified_commit;
 if(pred!=='fd87083d0c83abf66c4673db6aea30b3607ad562')throw new Error('G_WP_006_BASELINE_MISMATCH'); if(base.qualified_lineage_predecessor.workflow_run_id!==34264388488)throw new Error('G_WP_006_RUN_MISMATCH'); if(base.qualified_lineage_predecessor.evidence_artifact_id!==10071826917)throw new Error('G_WP_006_ARTIFACT_MISMATCH'); if(base.qualified_lineage_predecessor.evidence_artifact_sha256!=='aee4cd7ffcec8044ff7bf7468555da7fbe408c988111c6817567e980a74f8d60')throw new Error('G_WP_006_EVIDENCE_SHA_MISMATCH'); git(['merge-base','--is-ancestor',pred,'HEAD']);
 const pkg=JSON.parse(fs.readFileSync(path.join(ws,root,'control','PACKAGE-CONTRACT.json'),'utf8')); if(pkg.id!=='G-WP-007')throw new Error('PACKAGE_ID'); seteq(pkg.components,['ExternalEffectRecoveryCoordinator'],'PACKAGE_COMPONENTS'); seteq(pkg.contracts,['ReconcileExternalEffect','ListUnknownExternalEffects'],'PACKAGE_CONTRACTS'); seteq(pkg.tests,['IDEMPOTENCY','UNKNOWN_COMMIT','INTEGRATION','ADVERSARIAL'],'PACKAGE_TESTS');
 const req=JSON.parse(fs.readFileSync(path.join(ws,root,'control','REQUIREMENTS.json'),'utf8')); seteq(req.requirements.map(x=>x.id),['G-RQ-031','G-RQ-036','G-RQ-037','G-RQ-038','G-RQ-039','G-RQ-040'],'G_WP_007_REQUIREMENTS');
 const boundary=JSON.parse(fs.readFileSync(path.join(ws,root,'control','BOUNDARY-CONTRACT.json'),'utf8')); if(boundary.production_authorized!==false||!String(boundary.authority_boundaries.provider_calls||'').includes('No provider execution'))throw new Error('BOUNDARY_CONTRACT_DRIFT');
 const mf=JSON.parse(fs.readFileSync(path.join(ws,root,'control','SOURCE-SLICE-MANIFEST.json'),'utf8')); if(mf.expected_test_count!==50||mf.expected_requirement_count!==6||mf.production_authorized!==false)throw new Error('MANIFEST_METADATA_MISMATCH'); for(const e of mf.files){const repoPath=`${root}/${e.path}`;const actual=git(['rev-parse',`HEAD:${repoPath}`]).trim();if(actual!==e.git_blob_sha)throw new Error(`SEALED_BLOB_MISMATCH:${e.path}:${actual}:${e.git_blob_sha}`);}
 const depWorktree=path.join(process.env.RUNNER_TEMP||path.join(ws,'.tmp'),`system-master-gwp006-dependency-${runId}`); try{if(fs.existsSync(depWorktree))git(['worktree','remove','--force',depWorktree]);git(['worktree','add','--detach',depWorktree,pred]);const dep=spawnSync('node',['.github/scripts/gwp006-qualify.js'],{cwd:depWorktree,encoding:'utf8',shell:false,windowsHide:true,env:{...process.env,GITHUB_WORKSPACE:depWorktree,GITHUB_REF_NAME:'dependency-gwp006'}});const out=`${dep.stdout||''}${dep.stderr||''}`;if(dep.error||dep.status!==0||!out.includes('PASS G-WP-006 tests=50 requirements=3'))throw new Error(`G_WP_006_REGRESSION_NOT_PROVEN:${dep.error?dep.error.message:out}`);write('dependency-gwp006.txt',out);}finally{try{git(['worktree','remove','--force',depWorktree]);}catch(_){}}
 const classes=path.join(evidenceDir,'classes');fs.mkdirSync(classes,{recursive:true});const dirs=['g-wp-002','g-wp-003','g-wp-004','g-wp-005','g-wp-006','g-wp-007'].map(x=>path.join(ws,'system-master',x,'src','main','java','org','systemmaster','continuity'));let sources=[];for(const d of dirs)sources.push(...fs.readdirSync(d).filter(x=>x.endsWith('.java')).sort().map(x=>path.join(d,x)));const test=path.join(ws,root,'src','test','java','org','systemmaster','continuity','Gwp007QualificationTest.java');write('compile.txt',run('javac',['-encoding','UTF-8','-d',classes,...sources,test])||'javac=PASS');const out=run('java',['-cp',classes,'org.systemmaster.continuity.Gwp007QualificationTest']);write('qualification.txt',out);if(!out.includes('PASS G-WP-007 tests=50 requirements=6'))throw new Error(`QUALIFICATION_SENTINEL_MISSING:${out}`);
 write('subject.txt',[`objective=${base.objective}`,`commit=${head}`,`branch=${process.env.GITHUB_REF_NAME||''}`,`runner=${process.env.RUNNER_NAME||''}`,`machine=${process.env.COMPUTERNAME||''}`,`predecessor_commit=${pred}`,`predecessor_run=${base.qualified_lineage_predecessor.workflow_run_id}`,`predecessor_artifact=${base.qualified_lineage_predecessor.evidence_artifact_id}`,`predecessor_evidence_sha256=${base.qualified_lineage_predecessor.evidence_artifact_sha256}`].join('\n'));write('result.txt','result=PASS\ntests=50\nrequirements=6\ngwp006_regression=PASS\nidempotency=PASS\nunknown_commit=PASS\nintegration=PASS\nadversarial=PASS\nmilestone_testing=true\nproduction_authorized=false');console.log('PASS G-WP-007 tests=50 requirements=6');console.log(`evidence_dir=${evidenceDir}`);
}catch(e){const d=e&&e.stack?e.stack:String(e);write('failure.txt',d);write('result.txt','result=FAIL_OR_INCOMPLETE');console.error(d);process.exit(1);}
