import test from 'node:test';
import assert from 'node:assert/strict';
import { createAuthoritativeGitHubControlState } from '../src/authoritative-github-control-state.js';
import { EmptyAnchorHead, GitHubAnchorPaths } from '../src/github-checkpoint-anchor.js';
import { GitHubJournalPaths } from '../src/github-durable-journal.js';
import { canonicalize } from '../src/canonical.js';
import { FakeGitTransport } from '../test-support/fake-git-transport.js';

const CONFIG={mode:'authoritative',subjectRepository:'BFochtman746/system-master',controlStateRepository:'BFochtman746/system-master-control-state',controlStateRepositoryId:404,journal:{branch:'controller-journal/v1',principal:{kind:'github-app',id:101}},anchor:{branch:'controller-anchor/v1',principal:{kind:'github-app',id:202}}};
function writer(id){return {enforcement:'active',rules:[{type:'update'}],bypass_actors:[{actor_type:'Integration',actor_id:id,bypass_mode:'always'}]};}
function integrity(){return {enforcement:'active',rules:[{type:'deletion'},{type:'non_fast_forward'}],bypass_actors:[]};}
function observation(){return {repository_exists:true,repository_full_name:'BFochtman746/system-master-control-state',repository_id:404,journal:{branch_exists:true,writer_rulesets:[writer(101)],integrity_rulesets:[integrity()]},anchor:{branch_exists:true,writer_rulesets:[writer(202)],integrity_rulesets:[integrity()]}};}
function bind(base,appId,{repo='system-master-control-state',repositoryId=404}={}){const tokenProvider=async()=>`token-${appId}`;tokenProvider.principal={kind:'github-app',id:String(appId)};tokenProvider.repositoryId=repositoryId;return new Proxy(base,{get(target,prop,receiver){if(prop==='owner')return 'BFochtman746';if(prop==='repo')return repo;if(prop==='tokenProvider')return tokenProvider;const value=Reflect.get(target,prop,receiver);return typeof value==='function'?value.bind(target):value;}});}
function provision(){const base=new FakeGitTransport();const emptyCheckpoint={protocol_version:'controller-journal.v1',size:0,head_digest:null,last_batch_path:null,last_batch_digest:null};const journalCommit=base.seedCommit({[GitHubJournalPaths.checkpoint]:canonicalize(emptyCheckpoint)},base.genesisSha);const anchorCommit=base.seedCommit({[GitHubAnchorPaths.head]:canonicalize(EmptyAnchorHead)},base.genesisSha);base.refs.set('controller-journal/v1',journalCommit);base.refs.set('controller-anchor/v1',anchorCommit);return {base,journalTransport:bind(base,101),anchorTransport:bind(base,202)};}

async function build(overrides={}){const p=provision();return {p,result:await createAuthoritativeGitHubControlState({config:CONFIG,observation:observation(),journalTransport:p.journalTransport,anchorTransport:p.anchorTransport,genesisSha:p.base.genesisSha,...overrides})};}

test('ACG-T001 properly provisioned empty protected authority constructs as zero-event/zero-anchor runtime',async()=>{const {result}=await build();assert.equal(result.journalVerification.entries.length,0);assert.equal(result.anchorCount,0);assert.equal(result.anchoredExtension.anchored,false);assert.equal(result.authority.authoritative,true);});
test('ACG-T002 runtime transport is update-only and refuses ref creation',async()=>{const {result}=await build();await assert.rejects(result.journal.transport.createRef('x','0'.repeat(40)),e=>e.code==='AUTH_RUNTIME_REF_CREATION_DENIED');});
test('ACG-T003 journal ref deleted after preflight fails runtime activation instead of silently becoming genesis',async()=>{const p=provision();p.base.refs.delete('controller-journal/v1');await assert.rejects(createAuthoritativeGitHubControlState({config:CONFIG,observation:observation(),journalTransport:p.journalTransport,anchorTransport:p.anchorTransport,genesisSha:p.base.genesisSha}),e=>e.code==='JOURNAL_REF_MISSING');});
test('ACG-T004 anchor ref deleted after preflight fails runtime activation',async()=>{const p=provision();p.base.refs.delete('controller-anchor/v1');await assert.rejects(createAuthoritativeGitHubControlState({config:CONFIG,observation:observation(),journalTransport:p.journalTransport,anchorTransport:p.anchorTransport,genesisSha:p.base.genesisSha}),e=>e.code==='ANCHOR_REF_MISSING');});
test('ACG-T005 runtime transport repository name, numeric scope and App principal must match activated authority',async()=>{for(const mutate of [p=>{p.journalTransport=bind(p.base,101,{repo:'system-master'});},p=>{p.journalTransport=bind(p.base,101,{repositoryId:999});},p=>{p.journalTransport=bind(p.base,999);}]){const p=provision();mutate(p);await assert.rejects(createAuthoritativeGitHubControlState({config:CONFIG,observation:observation(),journalTransport:p.journalTransport,anchorTransport:p.anchorTransport,genesisSha:p.base.genesisSha}),e=>['AUTH_RUNTIME_REPOSITORY_MISMATCH','AUTH_RUNTIME_TOKEN_SCOPE_MISMATCH','AUTH_RUNTIME_PRINCIPAL_MISMATCH'].includes(e.code));}});
test('ACG-T006 malformed provisioned journal checkpoint prevents activation',async()=>{const p=provision();p.base.corruptFileAtRef('controller-journal/v1',GitHubJournalPaths.checkpoint,'{}');await assert.rejects(createAuthoritativeGitHubControlState({config:CONFIG,observation:observation(),journalTransport:p.journalTransport,anchorTransport:p.anchorTransport,genesisSha:p.base.genesisSha}),e=>e.code==='JOURNAL_CHECKPOINT_INVALID');});
test('ACG-T007 malformed nonempty sequence-zero anchor head prevents activation',async()=>{const p=provision();p.base.corruptFileAtRef('controller-anchor/v1',GitHubAnchorPaths.head,JSON.stringify({...EmptyAnchorHead,anchor_digest:'0'.repeat(64)}));await assert.rejects(createAuthoritativeGitHubControlState({config:CONFIG,observation:observation(),journalTransport:p.journalTransport,anchorTransport:p.anchorTransport,genesisSha:p.base.genesisSha}),e=>e.code==='ANCHOR_HEAD_INVALID');});
