import test from 'node:test';
import assert from 'node:assert/strict';
import { ControllerKernel, ControllerError } from '../src/kernel.js';
import { MemoryDurableJournal, publishPendingOutbox } from '../src/durable-journal.js';
import { uuidv7 } from '../src/canonical.js';

const SUBJECT={algorithm:'sha1',oid:'0123456789abcdef0123456789abcdef01234567'};
function command(){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'user:test',source:'chatgpt'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject:{...SUBJECT}},preconditions:{},intent:{task:'journal'},constraints:{},required_policy_version:null};}
function kernelWithEvent(){const k=new ControllerKernel(':memory:');k.acceptCommand(command());return k;}
function oneEvent(){const k=kernelWithEvent();const event=k.exportEvents()[0];k.close();return event;}

test('DJ-T001 publisher seals an exact event only after journal confirms digest',async()=>{const k=kernelWithEvent(),j=new MemoryDurableJournal();assert.equal(k.pendingOutbox().length,1);const result=await publishPendingOutbox(k,j);assert.equal(result.length,1);assert.equal(result[0].sealed,true);assert.equal((await j.list()).length,1);assert.equal(k.pendingOutbox().length,0);k.close();});
test('DJ-T002 failure before durable write leaves outbox pending',async()=>{const k=kernelWithEvent(),j=new MemoryDurableJournal({failBefore:1});const result=await publishPendingOutbox(k,j);assert.equal(result[0].sealed,false);assert.equal(result[0].code,'JOURNAL_UNAVAILABLE');assert.equal(k.pendingOutbox().length,1);assert.equal(k.pendingOutbox()[0].attempts,1);assert.equal((await j.list()).length,0);k.close();});
test('DJ-T003 lost acknowledgement after durable write is observed and sealed without duplicate',async()=>{const k=kernelWithEvent(),j=new MemoryDurableJournal({failAfter:1});const result=await publishPendingOutbox(k,j);assert.equal(result[0].sealed,true);assert.equal(result[0].recovered_after_error,true);assert.equal((await j.list()).length,1);assert.equal(k.pendingOutbox().length,0);k.close();});
test('DJ-T004 repeated publication of already stored identical event is idempotent',async()=>{const k=kernelWithEvent(),j=new MemoryDurableJournal();const row=k.pendingOutbox()[0];await j.putIfAbsent({event_id:row.event_id,event_schema:row.event_schema,stream_id:row.stream_id,stream_version:Number(row.stream_version),event_type:row.event_type,occurred_at:row.occurred_at,data:JSON.parse(row.data_json),prev_event_digest:row.prev_event_digest,event_digest:row.event_digest});const result=await publishPendingOutbox(k,j);assert.equal(result[0].sealed,true);assert.equal(result[0].created,false);assert.equal((await j.list()).length,1);k.close();});
test('DJ-T005 same event id with different digest is a hard conflict',async()=>{const j=new MemoryDurableJournal(),e=oneEvent();await j.putIfAbsent(e);await assert.rejects(()=>j.putIfAbsent({...e,event_digest:'b'.repeat(64)}),e=>e instanceof ControllerError&&e.code==='JOURNAL_CONFLICT');});
test('DJ-T006 journal list returns clones, not mutable authority references',async()=>{const j=new MemoryDurableJournal(),e=oneEvent();await j.putIfAbsent(e);const list=await j.list();list[0].data.command_id='mutated';assert.notEqual((await j.get(e.event_id)).data.command_id,'mutated');});
test('DJ-T007 corrupted semantic bytes cannot be admitted as durable history',async()=>{const j=new MemoryDurableJournal(),e=oneEvent();e.data.command_id='tampered';await assert.rejects(()=>j.putIfAbsent(e),e=>e instanceof ControllerError&&e.code==='JOURNAL_EVENT_INTEGRITY_FAILURE');assert.equal((await j.getCheckpoint()).size,0);});
test('DJ-T008 semantic stream version two cannot be durably appended before version one',async()=>{const k=new ControllerKernel(':memory:');const tx=k.acceptCommand(command()).transaction_id;k.admitTransaction(tx);const events=k.exportEvents().filter(e=>e.stream_id===`transaction:${tx}`).sort((a,b)=>a.stream_version-b.stream_version);k.close();const j=new MemoryDurableJournal();await assert.rejects(()=>j.putIfAbsent(events[1]),e=>e instanceof ControllerError&&e.code==='JOURNAL_STREAM_GAP');assert.equal((await j.getCheckpoint()).size,0);});
