import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ControllerKernel, ControllerError } from '../src/kernel.js';
import { uuidv7 } from '../src/canonical.js';
import { MemoryDurableJournal, publishPendingOutbox } from '../src/durable-journal.js';
import { rebuildControllerStore, reconcileRecoveredStore } from '../src/recovery.js';
import {
  prepareExternalEffect,
  getExternalEffect,
  authorizeExternalEffectDispatch,
  beginExternalEffectReconciliation,
  resolveExternalEffect,
  cancelExternalEffect
} from '../src/external-effect-authority.js';

const SUBJECT={algorithm:'sha1',oid:'0123456789abcdef0123456789abcdef01234567'};
function command(){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'user:test',source:'chatgpt'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject:{...SUBJECT}},preconditions:{},intent:{task:'external-effect'},constraints:{},required_policy_version:null};}
function assertCode(fn,code){assert.throws(fn,e=>e instanceof ControllerError&&e.code===code);}
function activeTx(k){const tx=k.acceptCommand(command()).transaction_id;k.admitTransaction(tx,{operations:'all_succeeded'});k.activateTransaction(tx);return tx;}
function readyOperation(k,resource='repo:main'){const tx=activeTx(k),op=k.createOperation(tx,{resourceId:resource});k.transitionOperation(op,'READY');return {tx,op};}
function runningOperation(k,resource='repo:main',nowMs=Date.now()){const {tx,op}=readyOperation(k,resource);const lease=k.acquireLease(op,resource,'worker-ee',60000,nowMs);k.startLeasedOperation({leaseId:lease.lease_id,generation:lease.generation,operationId:op,nowMs});return {tx,op,lease};}
function effectSpec(tx,op,overrides={}){return {transaction_id:tx,operation_id:op,provider:'github',effect_type:'git.ref.update',target_key:'refs/heads/main',idempotency_key:`effect-${uuidv7()}`,request:{ref:'refs/heads/main',sha:'a'.repeat(40),force:false},expected_remote_version:'b'.repeat(40),...overrides};}
function evidence(overrides={}){return {kind:'provider-observation',reference:'github:ref:main',observed_version:'a'.repeat(40),...overrides};}
function tempDb(){const dir=mkdtempSync(join(tmpdir(),'controller-v2-effect-'));return {dir,db:join(dir,'controller.sqlite')};}
async function durableSnapshot(kernel){const journal=new MemoryDurableJournal();const results=await publishPendingOutbox(kernel,journal);assert.ok(results.every(r=>r.sealed));return {entries:await journal.list(),checkpoint:await journal.getCheckpoint()};}

// Schema / preparation denominator.
test('EE-T001 fresh store reaches schema v4',()=>{const k=new ControllerKernel(':memory:');assert.equal(k.db.prepare('SELECT MAX(version) v FROM schema_migrations').get().v,4);k.close();});
test('EE-T002 v3-shaped store upgrades append-only to v4 tables',()=>{const {dir,db}=tempDb();try{let k=new ControllerKernel(db);k.close();const raw=new DatabaseSync(db);raw.exec('DROP TABLE external_effect_attempts; DROP TABLE external_effects; DELETE FROM schema_migrations WHERE version=4;');raw.close();k=new ControllerKernel(db);assert.equal(k.db.prepare('SELECT MAX(version) v FROM schema_migrations').get().v,4);assert.ok(k.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='external_effects'").get());k.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('EE-T003 prepare writes PREPARED effect and semantic event',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));assert.equal(getExternalEffect(k,r.effect_id).state,'PREPARED');assert.ok(k.exportEvents().some(e=>e.event_type==='external-effect.prepared'&&e.data.effect_id===r.effect_id));k.close();});
test('EE-T004 raw request payload is not persisted in effect row or event',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),spec=effectSpec(tx,op,{request:{secret_marker:'DO_NOT_STORE',value:7}}),r=prepareExternalEffect(k,spec),row=k.db.prepare('SELECT * FROM external_effects WHERE effect_id=?').get(r.effect_id);assert.equal(Object.values(row).some(v=>String(v).includes('DO_NOT_STORE')),false);assert.equal(JSON.stringify(k.exportEvents().filter(e=>e.stream_id===`external-effect:${r.effect_id}`)).includes('DO_NOT_STORE'),false);k.close();});
test('EE-T005 semantic duplicate returns same effect',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),spec=effectSpec(tx,op),a=prepareExternalEffect(k,spec),b=prepareExternalEffect(k,structuredClone(spec));assert.equal(a.effect_id,b.effect_id);assert.equal(b.duplicate,true);k.close();});
test('EE-T006 changed request under same provider/key conflicts',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),spec=effectSpec(tx,op);prepareExternalEffect(k,spec);assertCode(()=>prepareExternalEffect(k,{...spec,request:{changed:true}}),'IDEMPOTENCY_CONFLICT');k.close();});
test('EE-T007 changed target under same provider/key conflicts',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),spec=effectSpec(tx,op);prepareExternalEffect(k,spec);assertCode(()=>prepareExternalEffect(k,{...spec,target_key:'refs/heads/other'}),'IDEMPOTENCY_CONFLICT');k.close();});
test('EE-T008 changed expected remote version conflicts',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),spec=effectSpec(tx,op);prepareExternalEffect(k,spec);assertCode(()=>prepareExternalEffect(k,{...spec,expected_remote_version:'c'.repeat(40)}),'IDEMPOTENCY_CONFLICT');k.close();});
test('EE-T009 changed operation under same key conflicts',()=>{const k=new ControllerKernel(':memory:'),tx=activeTx(k),op1=k.createOperation(tx,{resourceId:'r1'}),op2=k.createOperation(tx,{resourceId:'r2'});k.transitionOperation(op1,'READY');k.transitionOperation(op2,'READY');const spec=effectSpec(tx,op1);prepareExternalEffect(k,spec);assertCode(()=>prepareExternalEffect(k,{...spec,operation_id:op2}),'IDEMPOTENCY_CONFLICT');k.close();});
test('EE-T010 operation must belong to transaction',()=>{const k=new ControllerKernel(':memory:'),a=readyOperation(k,'r1'),b=readyOperation(k,'r2');assertCode(()=>prepareExternalEffect(k,effectSpec(a.tx,b.op)),'EXTERNAL_EFFECT_OPERATION_MISMATCH');k.close();});

// Fencing / dispatch denominator.
test('EE-T011 current live lease authorizes exactly one immutable attempt',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op)),attempt=authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);assert.equal(attempt.attempt_number,1);assert.equal(k.db.prepare('SELECT COUNT(*) n FROM external_effect_attempts WHERE effect_id=?').get(r.effect_id).n,1);assert.equal(getExternalEffect(k,r.effect_id).state,'UNKNOWN');k.close();});
test('EE-T012 lease for another operation is rejected',()=>{const k=new ControllerKernel(':memory:'),a=runningOperation(k,'r1'),b=runningOperation(k,'r2'),r=prepareExternalEffect(k,effectSpec(a.tx,a.op));assertCode(()=>authorizeExternalEffectDispatch(k,r.effect_id,b.lease.lease_id),'STALE_LEASE');k.close();});
test('EE-T013 expired lease is rejected',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),lease=k.acquireLease(op,'repo:main','worker',1,1000);k.startLeasedOperation({leaseId:lease.lease_id,generation:lease.generation,operationId:op,nowMs:1000});const r=prepareExternalEffect(k,effectSpec(tx,op));assertCode(()=>authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id,1002),'STALE_LEASE');k.close();});
test('EE-T014 released lease is rejected',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));k.releaseLease(lease.lease_id,lease.generation);assertCode(()=>authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id),'STALE_LEASE');k.close();});
test('EE-T015 stale resource generation is rejected',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));k.db.prepare('UPDATE resource_generations SET generation=generation+1 WHERE resource_id=?').run('repo:main');assertCode(()=>authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id),'STALE_LEASE');k.close();});
test('EE-T016 dispatch requires RUNNING operation',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),lease=k.acquireLease(op,'repo:main','worker'),r=prepareExternalEffect(k,effectSpec(tx,op));assertCode(()=>authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id),'EXTERNAL_EFFECT_OPERATION_NOT_RUNNING');k.close();});
test('EE-T017 duplicate dispatch authorization cannot create second attempt',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);assert.throws(()=>authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id));assert.equal(k.db.prepare('SELECT COUNT(*) n FROM external_effect_attempts WHERE effect_id=?').get(r.effect_id).n,1);k.close();});
test('EE-T018 dispatch authorization records UNKNOWN before network work exists',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);assert.equal(getExternalEffect(k,r.effect_id).state,'UNKNOWN');assert.ok(k.exportEvents().some(e=>e.event_type==='external-effect.dispatch-authorized'));k.close();});
test('EE-T019 attempt evidence survives lease release unchanged',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op)),attempt=authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);k.releaseLease(lease.lease_id,lease.generation);const row=k.db.prepare('SELECT * FROM external_effect_attempts WHERE attempt_id=?').get(attempt.attempt_id);assert.equal(row.lease_id,lease.lease_id);assert.equal(row.generation,lease.generation);k.close();});
test('EE-T020 portable v1 never returns effect to PREPARED for redispatch',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);resolveExternalEffect(k,r.effect_id,{state:'UNKNOWN',evidence:evidence({detail_code:'still-uncertain'})});assert.equal(getExternalEffect(k,r.effect_id).state,'UNKNOWN');assert.throws(()=>authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id));k.close();});

// Reconciliation / outcomes denominator.
test('EE-T021 UNKNOWN begins reconciliation',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);assert.equal(beginExternalEffectReconciliation(k,r.effect_id),'RECONCILING');k.close();});
test('EE-T022 repeated begin reconciliation is idempotent',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);const before=k.exportEvents().length;assert.equal(beginExternalEffectReconciliation(k,r.effect_id),'RECONCILING');assert.equal(k.exportEvents().length,before);k.close();});
test('EE-T023 success without evidence is rejected',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);assertCode(()=>resolveExternalEffect(k,r.effect_id,{state:'SUCCEEDED'}),'EXTERNAL_EFFECT_EVIDENCE_REQUIRED');k.close();});
test('EE-T024 failure requires classified error code',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);assertCode(()=>resolveExternalEffect(k,r.effect_id,{state:'FAILED',evidence:evidence()}),'EXTERNAL_EFFECT_ERROR_CODE_REQUIRED');k.close();});
test('EE-T025 reconciliation can prove success with bounded evidence',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);assert.equal(resolveExternalEffect(k,r.effect_id,{state:'SUCCEEDED',evidence:evidence()}),'SUCCEEDED');assert.equal(getExternalEffect(k,r.effect_id).terminal_evidence.kind,'provider-observation');k.close();});
test('EE-T026 reconciliation can prove permanent failure',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);assert.equal(resolveExternalEffect(k,r.effect_id,{state:'FAILED',evidence:evidence({detail_code:'protected'}),error_code:'REMOTE_PRECONDITION_FAILED'}),'FAILED');assert.equal(getExternalEffect(k,r.effect_id).last_error_code,'REMOTE_PRECONDITION_FAILED');k.close();});
test('EE-T027 unresolved observation returns to UNKNOWN with no redispatch authority',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);resolveExternalEffect(k,r.effect_id,{state:'UNKNOWN',evidence:evidence({detail_code:'provider-unavailable'}),error_code:'OBSERVATION_UNAVAILABLE'});assert.equal(getExternalEffect(k,r.effect_id).state,'UNKNOWN');assert.equal(k.db.prepare('SELECT COUNT(*) n FROM external_effect_attempts WHERE effect_id=?').get(r.effect_id).n,1);k.close();});
test('EE-T028 cancellation before dispatch is terminal and evidenced',()=>{const k=new ControllerKernel(':memory:'),{tx,op}=readyOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));assert.equal(cancelExternalEffect(k,r.effect_id,'user-cancelled'),'CANCELLED');assert.equal(getExternalEffect(k,r.effect_id).state,'CANCELLED');k.close();});
test('EE-T029 cancellation after dispatch authorization is rejected',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),r=prepareExternalEffect(k,effectSpec(tx,op));authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);assertCode(()=>cancelExternalEffect(k,r.effect_id,'too-late'),'EXTERNAL_EFFECT_CANCEL_FORBIDDEN');k.close();});

// Recovery / ownership / cumulative boundary denominator.
test('EE-T030 event replay reconstructs exact effect and attempt state',()=>{const k=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(k),spec=effectSpec(tx,op),r=prepareExternalEffect(k,spec),attempt=authorizeExternalEffectDispatch(k,r.effect_id,lease.lease_id);beginExternalEffectReconciliation(k,r.effect_id);resolveExternalEffect(k,r.effect_id,{state:'SUCCEEDED',evidence:evidence()});const replay=ControllerKernel.replay(k.exportEvents());assert.equal(replay.external_effects[r.effect_id].state,'SUCCEEDED');assert.equal(replay.external_effects[r.effect_id].request_digest,r.request_digest);assert.equal(replay.external_effect_attempts[attempt.attempt_id].lease_id,lease.lease_id);k.close();});
test('EE-T031 durable rebuild restores unknown effect but never resurrects dispatch lease',async()=>{const source=new ControllerKernel(':memory:'),{tx,op,lease}=runningOperation(source),r=prepareExternalEffect(source,effectSpec(tx,op));authorizeExternalEffectDispatch(source,r.effect_id,lease.lease_id);const durable=await durableSnapshot(source);source.close();const {dir,db}=tempDb();try{const recovered=rebuildControllerStore(db,durable.entries,{expectedCheckpoint:durable.checkpoint});assert.equal(getExternalEffect(recovered,r.effect_id).state,'UNKNOWN');assert.equal(recovered.db.prepare('SELECT COUNT(*) n FROM external_effect_attempts WHERE effect_id=?').get(r.effect_id).n,1);assert.equal(recovered.db.prepare('SELECT COUNT(*) n FROM leases').get().n,0);const report=reconcileRecoveredStore(recovered);assert.deepEqual(report.external_effects_requiring_observation,[{effect_id:r.effect_id,state:'UNKNOWN',required_action:'OBSERVE_EXTERNAL_STATE'}]);recovered.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('EE-T032 external-effect authority contains no provider/network SDK or retry loop',()=>{const source=readFileSync(fileURLToPath(new URL('../src/external-effect-authority.js',import.meta.url)),'utf8');assert.equal(/from ['"](?:node:https|node:http|@octokit|aws-sdk|stripe)['"]/.test(source),false);assert.equal(/setTimeout\s*\(|fetch\s*\(|\.request\s*\(/.test(source),false);});
