import test from 'node:test';
import assert from 'node:assert/strict';
import { ControllerKernel } from '../src/kernel.js';
import { ControllerError } from '../src/errors.js';
import { GitDataJournalAdapter } from '../src/git-data-journal.js';
import { SimulatedGitDataApi } from '../src/simulated-git-data.js';
import { canonicalize, sha256, uuidv7 } from '../src/canonical.js';

const SUBJECT_REPO='repo:system-master:1360399247';
const JOURNAL_REPO='repo:controller-journal:999';
const SUBJECT={algorithm:'sha1',oid:'0123456789abcdef0123456789abcdef01234567'};
function command(task='faults'){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'user:test',source:'chatgpt'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject:{...SUBJECT}},preconditions:{},intent:{task},constraints:{},required_policy_version:null};}
function dbEvents(k){return k.db.prepare('SELECT * FROM events ORDER BY rowid').all().map(r=>({event_id:r.event_id,event_schema:r.event_schema,stream_id:r.stream_id,stream_version:Number(r.stream_version),event_type:r.event_type,occurred_at:r.occurred_at,data:JSON.parse(r.data_json),prev_event_digest:r.prev_event_digest,event_digest:r.event_digest}));}
function singleEvent(task='one'){const k=new ControllerKernel(':memory:');k.acceptCommand(command(task));const [e]=dbEvents(k);k.close();return e;}
function transactionEvents(task='tx'){const k=new ControllerKernel(':memory:');const tx=k.acceptCommand(command(task)).transaction_id;k.admitTransaction(tx);k.activateTransaction(tx);const events=dbEvents(k).filter(e=>e.stream_id===`transaction:${tx}`);k.close();return events;}
function code(e,c){return e instanceof ControllerError&&e.code===c;}
async function env(extra={}){const client=new SimulatedGitDataApi();const journal=new GitDataJournalAdapter(client,{repositoryIdentity:JOURNAL_REPO,subjectRepositoryIdentity:SUBJECT_REPO,...extra});const root=await journal.initialize();return {client,journal,root};}
async function appendOne(e=singleEvent(),extra={}){const x=await env(extra);const result=await x.journal.append([e]);return {...x,result};}
async function maliciousCheckpointChild(client,journal,mutate,{extraFiles={}}={}){const state=await journal.readHead();const cp=structuredClone(state.checkpoint);mutate(cp,state);if(cp.size>0)cp.previous_git_commit_oid=cp.previous_git_commit_oid??state.commit_oid;const cpBlob=await client.createBlob(typeof cp==='string'?cp:canonicalize(cp));const tree=await client.createTree(state.commit.tree,{'checkpoint.json':cpBlob,...extraFiles});const commit=await client.createCommit({message:'simulated malicious checkpoint',tree,parents:[state.commit_oid]});client.forceSetRef('heads/journal',commit);return {state,commit,tree,cp};}

test('GJ-T026 failure before segment blob leaves ref unchanged',async()=>{const {client,journal,root}=await env();client.injectFault({method:'createBlob',when:'before'});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);});
test('GJ-T027 failure after segment blob leaves only unreachable object',async()=>{const {client,journal,root}=await env();const before=client.blobs.size;client.injectFault({method:'createBlob',when:'after'});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);assert.equal(client.blobs.size,before+1);});
test('GJ-T028 failure before checkpoint blob leaves ref unchanged',async()=>{const {client,journal,root}=await env();client.injectFault({method:'createBlob',when:'before',skip:1});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);});
test('GJ-T029 failure after checkpoint blob leaves ref unchanged',async()=>{const {client,journal,root}=await env();client.injectFault({method:'createBlob',when:'after',skip:1});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);});
test('GJ-T030 failure before tree creation leaves ref unchanged',async()=>{const {client,journal,root}=await env();client.injectFault({method:'createTree',when:'before'});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);});
test('GJ-T031 failure after tree creation leaves ref unchanged',async()=>{const {client,journal,root}=await env();client.injectFault({method:'createTree',when:'after'});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);});
test('GJ-T032 failure before commit creation leaves ref unchanged',async()=>{const {client,journal,root}=await env();client.injectFault({method:'createCommit',when:'before'});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);});
test('GJ-T033 failure after commit creation leaves ref unchanged',async()=>{const {client,journal,root}=await env();const before=client.commits.size;client.injectFault({method:'createCommit',when:'after'});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);assert.equal(client.commits.size,before+1);});
test('GJ-T034 permission failure on ref update never publishes candidate',async()=>{const {client,journal,root}=await env();client.injectFault({method:'updateRef',when:'before',status:403});await assert.rejects(()=>journal.append([singleEvent()]),e=>e.status===403);assert.equal(await client.getRef('heads/journal'),root.commit_oid);});
test('GJ-T035 read-head outage before append performs no mutation',async()=>{const {client,journal}=await env();client.resetCalls();client.injectFault({method:'getRef',when:'before',status:500});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(client.calls.some(c=>['createBlob','createTree','createCommit','updateRef'].includes(c.method)),false);});
test('GJ-T036 blob-read outage during verification performs no append mutation',async()=>{const {client,journal}=await env();client.resetCalls();client.injectFault({method:'getBlob',when:'before',status:500});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(client.calls.some(c=>['createBlob','createTree','createCommit','updateRef'].includes(c.method)),false);});
test('GJ-T037 missing checkpoint path is rejected',async()=>{const {client,journal}=await env();const state=await journal.readHead();client.mutateTreeForTest(state.commit.tree,files=>{delete files['checkpoint.json'];});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_JOURNAL_INCOMPLETE'));});
test('GJ-T038 malformed checkpoint JSON is rejected',async()=>{const {client,journal}=await appendOne();const state=await journal.readHead();const blob=await client.createBlob('{');const tree=await client.createTree(state.commit.tree,{'checkpoint.json':blob});const commit=await client.createCommit({message:'bad json',tree,parents:[state.commit_oid]});client.forceSetRef('heads/journal',commit);await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_CHECKPOINT_INVALID'));});
test('GJ-T039 checkpoint schema drift is rejected',async()=>{const {client,journal}=await appendOne();await maliciousCheckpointChild(client,journal,cp=>{cp.schema='controller.journal.checkpoint.v999';cp.previous_git_commit_oid=null;});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_CHECKPOINT_SCHEMA_MISMATCH'));});
test('GJ-T040 checkpoint size inconsistent with segments is rejected',async()=>{const {client,journal}=await appendOne();await maliciousCheckpointChild(client,journal,(cp,state)=>{cp.size+=1;cp.previous_git_commit_oid=state.commit_oid;});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'JOURNAL_CHECKPOINT_MISMATCH'));});
test('GJ-T041 checkpoint head digest inconsistent with segments is rejected',async()=>{const {client,journal}=await appendOne();await maliciousCheckpointChild(client,journal,(cp,state)=>{cp.head_digest='0'.repeat(64);cp.previous_git_commit_oid=state.commit_oid;});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'JOURNAL_CHECKPOINT_MISMATCH'));});
test('GJ-T042 checkpoint stream-head projection mismatch is rejected',async()=>{const {client,journal}=await appendOne();await maliciousCheckpointChild(client,journal,(cp,state)=>{const key=Object.keys(cp.stream_heads)[0];cp.stream_heads[key].version+=1;cp.previous_git_commit_oid=state.commit_oid;});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_STREAM_HEAD_MISMATCH'));});
test('GJ-T043 checkpoint last-segment metadata mismatch is rejected',async()=>{const {client,journal}=await appendOne();await maliciousCheckpointChild(client,journal,(cp,state)=>{cp.last_segment={...cp.last_segment,end:cp.last_segment.end+1};cp.previous_git_commit_oid=state.commit_oid;});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_CHECKPOINT_SEGMENT_MISMATCH'));});
test('GJ-T044 invalid segment filename is rejected',async()=>{const {client,journal}=await appendOne();const state=await journal.readHead();const valid=Object.keys(state.tree.files).find(p=>p.startsWith('segments/'));client.mutateTreeForTest(state.commit.tree,files=>{files['segments/not-a-segment.jsonl']=files[valid];});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_SEGMENT_PATH_INVALID'));});
test('GJ-T045 segment filename range must equal encoded positions',async()=>{const {client,journal}=await appendOne();const state=await journal.readHead();const valid=Object.keys(state.tree.files).find(p=>p.startsWith('segments/'));const blob=state.tree.files[valid],digest=valid.match(/-([0-9a-f]{64})\.jsonl$/)[1];client.mutateTreeForTest(state.commit.tree,files=>{files[`segments/${String(2).padStart(20,'0')}-${String(2).padStart(20,'0')}-${digest}.jsonl`]=blob;});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_SEGMENT_RANGE_MISMATCH'));});
test('GJ-T046 empty segment is rejected',async()=>{const {client,journal}=await appendOne();const state=await journal.readHead();const empty=await client.createBlob(''),digest=sha256('');const path=`segments/${String(2).padStart(20,'0')}-${String(2).padStart(20,'0')}-${digest}.jsonl`;client.mutateTreeForTest(state.commit.tree,files=>{files[path]=empty;});await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_SEGMENT_EMPTY'));});
test('GJ-T047 witness checkpoint values must match the witnessed commit',async()=>{const {journal}=await appendOne();const witness=journal.witnessFrom(await journal.verifyHead());witness.size+=1;await assert.rejects(()=>journal.verifyHead({expectedWitness:witness}),e=>code(e,'LOCAL_WITNESS_MISMATCH'));});
test('GJ-T048 missing witnessed commit fails closed',async()=>{const {journal}=await appendOne();const witness=journal.witnessFrom(await journal.verifyHead());witness.commit_oid='f'.repeat(40);await assert.rejects(()=>journal.verifyHead({expectedWitness:witness}),e=>code(e,'LOCAL_WITNESS_NOT_FOUND'));});
test('GJ-T049 deleted journal ref fails closed',async()=>{const {client,journal}=await appendOne();client.deleteRef('heads/journal');await assert.rejects(()=>journal.verifyHead(),e=>code(e,'JOURNAL_REF_MISSING'));});
test('GJ-T050 ref pointing to unavailable commit fails closed',async()=>{const {client,journal}=await env();client.refs.set('heads/journal','f'.repeat(40));await assert.rejects(()=>journal.verifyHead(),e=>e.status===404);});
test('GJ-T051 non-branch journal ref is rejected at construction',()=>{assert.throws(()=>new GitDataJournalAdapter(new SimulatedGitDataApi(),{repositoryIdentity:JOURNAL_REPO,ref:'tags/journal'}),e=>code(e,'JOURNAL_REF_INVALID'));});
test('GJ-T052 repeated non-fast-forward conflict exhausts with named failure',async()=>{const {client,journal}=await env({maxConflictRetries:1});client.injectFault({method:'updateRef',when:'before',times:2,status:409,code:'NON_FAST_FORWARD'});await assert.rejects(()=>journal.append([singleEvent()]),e=>code(e,'JOURNAL_CONFLICT_RETRY_EXHAUSTED'));});
test('GJ-T053 configured batch event limit is enforced before remote object creation',async()=>{const {client,journal}=await env({maxBatchEvents:1});client.resetCalls();await assert.rejects(()=>journal.append([singleEvent('a'),singleEvent('b')]),e=>code(e,'JOURNAL_BATCH_EVENT_LIMIT'));assert.equal(client.calls.some(c=>['createBlob','createTree','createCommit','updateRef'].includes(c.method)),false);});
test('GJ-T054 configured segment byte limit is enforced before remote object creation',async()=>{const {client,journal}=await env({maxSegmentBytes:1});client.resetCalls();await assert.rejects(()=>journal.append([singleEvent()]),e=>code(e,'JOURNAL_SEGMENT_BYTE_LIMIT'));assert.equal(client.calls.some(c=>['createBlob','createTree','createCommit','updateRef'].includes(c.method)),false);});
test('GJ-T055 journal position overflow has a named fail-closed error',async()=>{const {journal}=await env();await assert.rejects(async()=>journal._buildEntries([singleEvent()],{size:Number.MAX_SAFE_INTEGER,head_digest:'a'.repeat(64),stream_heads:{}}),e=>code(e,'JOURNAL_POSITION_OVERFLOW'));});
test('GJ-T056 already-committed prefix is reconciled and only new suffix is appended',async()=>{const {journal}=await env();const [v1,v2]=transactionEvents();await journal.append([v1]);const result=await journal.append([v1,v2]);assert.equal(result.duplicate,false);const state=await journal.verifyHead();assert.equal(state.checkpoint.size,2);assert.deepEqual(state.entries.map(e=>e.event_id),[v1.event_id,v2.event_id]);});
test('GJ-T057 old exact batch remains idempotent after later independent append',async()=>{const {journal}=await env();const first=[singleEvent('first')],second=[singleEvent('second')];await journal.append(first);await journal.append(second);const result=await journal.append(first);assert.equal(result.duplicate,true);assert.equal((await journal.verifyHead()).checkpoint.size,2);});
test('GJ-T058 identical concurrent appenders converge to one journal event',async()=>{const client=new SimulatedGitDataApi();const a=new GitDataJournalAdapter(client,{repositoryIdentity:JOURNAL_REPO}),b=new GitDataJournalAdapter(client,{repositoryIdentity:JOURNAL_REPO});await a.initialize();const event=singleEvent();const [x,y]=await Promise.all([a.append([event]),b.append([event])]);assert.ok(x.commit_oid&&y.commit_oid);assert.equal((await a.verifyHead()).checkpoint.size,1);});
test('GJ-T059 unexpected files in journal branch are rejected',async()=>{const {client,journal}=await appendOne();const state=await journal.readHead();const note=await client.createBlob('not journal data');const cp={...state.checkpoint,previous_git_commit_oid:state.commit_oid};const cpBlob=await client.createBlob(canonicalize(cp));const tree=await client.createTree(state.commit.tree,{'checkpoint.json':cpBlob,'notes.txt':note});const commit=await client.createCommit({message:'contaminate journal',tree,parents:[state.commit_oid]});client.forceSetRef('heads/journal',commit);await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_TREE_UNEXPECTED_PATH'));});
test('GJ-T060 semantic event schema rejects unknown top-level fields before publication',async()=>{const {journal}=await env();const event={...singleEvent(),unexpected:'hidden-data'};await assert.rejects(()=>journal.append([event]),e=>code(e,'JOURNAL_EVENT_UNKNOWN_FIELD'));});
