import test from 'node:test';
import assert from 'node:assert/strict';
import { ControllerKernel } from '../src/kernel.js';
import { ControllerError } from '../src/errors.js';
import { GitDataJournalAdapter } from '../src/git-data-journal.js';
import { SimulatedGitDataApi } from '../src/simulated-git-data.js';
import { canonicalize, sha256, uuidv7 } from '../src/canonical.js';

const SUBJECT_REPO='repo:system-master:1360399247';
const JOURNAL_REPO='repo:controller-journal:999';
const SUBJECT={algorithm:'sha1',oid:'0123456789abcdef0123456789abcdef01234567'};
function command(task='git-journal'){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'user:test',source:'chatgpt'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject:{...SUBJECT}},preconditions:{},intent:{task},constraints:{},required_policy_version:null};}
function dbEvents(k){return k.db.prepare('SELECT * FROM events ORDER BY rowid').all().map(r=>({event_id:r.event_id,event_schema:r.event_schema,stream_id:r.stream_id,stream_version:Number(r.stream_version),event_type:r.event_type,occurred_at:r.occurred_at,data:JSON.parse(r.data_json),prev_event_digest:r.prev_event_digest,event_digest:r.event_digest}));}
function singleEvent(task='one'){const k=new ControllerKernel(':memory:');k.acceptCommand(command(task));const [e]=dbEvents(k);k.close();return e;}
function eventSeries(task='series'){const k=new ControllerKernel(':memory:');const tx=k.acceptCommand(command(task)).transaction_id;k.admitTransaction(tx);k.activateTransaction(tx);const op=k.createOperation(tx,{resourceId:`resource:${task}`});k.transitionOperation(op,'READY');const events=dbEvents(k);k.close();return events;}
function adapter(client=new SimulatedGitDataApi(),extra={}){return {client,journal:new GitDataJournalAdapter(client,{repositoryIdentity:JOURNAL_REPO,subjectRepositoryIdentity:SUBJECT_REPO,...extra})};}
async function initialized(extra={}){const x=adapter(new SimulatedGitDataApi(),extra);const root=await x.journal.initialize();return {...x,root};}
function code(error,expected){return error instanceof ControllerError&&error.code===expected;}
function recomputeEvent(event,patch){const e=structuredClone({...event,...patch});const core={event_id:e.event_id,event_schema:e.event_schema,stream_id:e.stream_id,stream_version:e.stream_version,event_type:e.event_type,occurred_at:e.occurred_at,prev_event_digest:e.prev_event_digest,data:e.data};e.event_digest=sha256(core);return e;}

test('GJ-T001 explicit initialization creates parentless root with empty verified checkpoint',async()=>{const {journal,client,root}=await initialized();const state=await journal.verifyHead();assert.equal(state.commit_oid,root.commit_oid);assert.equal(state.checkpoint.size,0);assert.equal(state.entries.length,0);assert.deepEqual(client.commits.get(root.commit_oid).parents,[]);});
test('GJ-T002 initialization is explicit and refuses an existing journal ref',async()=>{const {journal}=await initialized();await assert.rejects(()=>journal.initialize(),e=>code(e,'JOURNAL_ALREADY_INITIALIZED'));});
test('GJ-T003 missing ref fails closed outside initialization',async()=>{const {journal}=adapter();await assert.rejects(()=>journal.verifyHead(),e=>code(e,'JOURNAL_REF_MISSING'));});
test('GJ-T004 journal repository may not equal subject repository identity',()=>{const client=new SimulatedGitDataApi();assert.throws(()=>new GitDataJournalAdapter(client,{repositoryIdentity:SUBJECT_REPO,subjectRepositoryIdentity:SUBJECT_REPO}),e=>code(e,'JOURNAL_SUBJECT_REPOSITORY_FORBIDDEN'));});
test('GJ-T005 stable journal repository identity is mandatory',()=>{assert.throws(()=>new GitDataJournalAdapter(new SimulatedGitDataApi()),e=>code(e,'JOURNAL_REPOSITORY_ID_REQUIRED'));});
test('GJ-T006 first append publishes immutable segment and checkpoint in one child commit',async()=>{const {journal,client,root}=await initialized();const result=await journal.append([singleEvent()]);const head=await journal.verifyHead();assert.equal(head.checkpoint.size,1);assert.equal(head.entries.length,1);assert.deepEqual(client.commits.get(result.commit_oid).parents,[root.commit_oid]);assert.equal(Object.keys(head.tree.files).filter(p=>p.startsWith('segments/')).length,1);assert.ok(head.tree.files['checkpoint.json']);});
test('GJ-T007 ref publication always requests force false and expected old head',async()=>{const {journal,client,root}=await initialized();client.resetCalls();await journal.append([singleEvent()]);const call=client.calls.find(c=>c.method==='updateRef');assert.equal(call.args.force,false);assert.equal(call.args.expectedOldOid,root.commit_oid);});
test('GJ-T008 duplicate batch delivery is idempotent and does not advance ref',async()=>{const {journal,client}=await initialized();const batch=[singleEvent()];const a=await journal.append(batch),before=await client.getRef('heads/journal');const b=await journal.append(batch),after=await client.getRef('heads/journal');assert.equal(before,after);assert.equal(b.duplicate,true);assert.equal(a.commit_oid,b.commit_oid);});
test('GJ-T009 same event id with different valid digest hard-conflicts',async()=>{const {journal}=await initialized();const original=singleEvent('a');await journal.append([original]);const other=singleEvent('b');const collision=recomputeEvent(other,{event_id:original.event_id});await assert.rejects(()=>journal.append([collision]),e=>code(e,'JOURNAL_CONFLICT'));});
test('GJ-T010 corrupted semantic event bytes fail before remote mutation',async()=>{const {journal,client}=await initialized();const event=singleEvent();event.data.command_id='tampered';client.resetCalls();await assert.rejects(()=>journal.append([event]),e=>code(e,'JOURNAL_EVENT_INTEGRITY_FAILURE'));assert.equal(client.calls.some(c=>c.method==='updateRef'),false);});
test('GJ-T011 semantic stream version two without one is rejected',async()=>{const {journal}=await initialized();const events=eventSeries();const stream=events.filter(e=>e.stream_id.startsWith('transaction:'));await assert.rejects(()=>journal.append([stream[1]]),e=>code(e,'JOURNAL_STREAM_GAP'));});
test('GJ-T012 lost ref-update acknowledgement is observed as success without second append',async()=>{const {journal,client}=await initialized();client.injectFault({method:'updateRef',when:'after',times:1,status:500,ambiguous:true});const result=await journal.append([singleEvent()]);assert.equal(result.recovered_after_error,true);assert.equal((await journal.verifyHead()).checkpoint.size,1);assert.equal(client.calls.filter(c=>c.method==='updateRef').length,1);});
test('GJ-T013 ambiguous failure before ref mutation fails REMOTE_STATE_UNKNOWN',async()=>{const {journal,client}=await initialized();client.injectFault({method:'updateRef',when:'before',times:1,status:500,ambiguous:true});await assert.rejects(()=>journal.append([singleEvent()]),e=>code(e,'REMOTE_STATE_UNKNOWN'));assert.equal((await journal.verifyHead()).checkpoint.size,0);});
test('GJ-T014 commit object created but ref update never happens is non-authoritative',async()=>{const {journal,client,root}=await initialized();client.injectFault({method:'createCommit',when:'after',times:1,status:500});await assert.rejects(()=>journal.append([singleEvent()]));assert.equal(await client.getRef('heads/journal'),root.commit_oid);assert.equal((await journal.verifyHead()).checkpoint.size,0);assert.ok(client.commits.size>1);});
test('GJ-T015 two independent writers racing an empty head converge without force',async()=>{const client=new SimulatedGitDataApi();const a=new GitDataJournalAdapter(client,{repositoryIdentity:JOURNAL_REPO,subjectRepositoryIdentity:SUBJECT_REPO});const b=new GitDataJournalAdapter(client,{repositoryIdentity:JOURNAL_REPO,subjectRepositoryIdentity:SUBJECT_REPO});await a.initialize();const [r1,r2]=await Promise.all([a.append([singleEvent('writer-a')]),b.append([singleEvent('writer-b')])]);assert.ok(r1.commit_oid);assert.ok(r2.commit_oid);const state=await a.verifyHead();assert.equal(state.checkpoint.size,2);assert.equal(new Set(state.entries.map(e=>e.event_id)).size,2);assert.equal(client.calls.filter(c=>c.method==='updateRef'&&c.args.force===true).length,0);});
test('GJ-T016 local witness accepts a genuine remote extension',async()=>{const {journal}=await initialized();await journal.append([singleEvent('first')]);const witness=journal.witnessFrom(await journal.verifyHead());await journal.append([singleEvent('second')],{witness});const state=await journal.verifyHead({expectedWitness:witness});assert.equal(state.checkpoint.size,2);});
test('GJ-T017 remote rollback behind local witness is detected',async()=>{const {journal,client,root}=await initialized();await journal.append([singleEvent('first')]);const witness=journal.witnessFrom(await journal.verifyHead());client.forceSetRef('heads/journal',root.commit_oid);await assert.rejects(()=>journal.verifyHead({expectedWitness:witness}),e=>code(e,'REMOTE_JOURNAL_ROLLBACK_OR_FORK'));});
test('GJ-T018 witness from another repository/ref is rejected before trust',async()=>{const {journal}=await initialized();const state=await journal.verifyHead();const witness={...journal.witnessFrom(state),repository_identity:'repo:other:1'};await assert.rejects(()=>journal.verifyHead({expectedWitness:witness}),e=>code(e,'LOCAL_WITNESS_IDENTITY_MISMATCH'));});
test('GJ-T019 deleting a referenced segment blob makes journal unverifiable',async()=>{const {journal,client}=await initialized();await journal.append([singleEvent()]);const state=await journal.readHead();const path=Object.keys(state.tree.files).find(p=>p.startsWith('segments/'));client.removeBlobForTest(state.tree.files[path]);await assert.rejects(()=>journal.verifyHead(),e=>e?.status===404);});
test('GJ-T020 changing bytes behind a simulated immutable blob OID is detected by path digest',async()=>{const {journal,client}=await initialized();await journal.append([singleEvent()]);const state=await journal.readHead();const path=Object.keys(state.tree.files).find(p=>p.startsWith('segments/'));client.mutateBlobForTest(state.tree.files[path],'tampered\n');await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_SEGMENT_DIGEST_MISMATCH'));});
test('GJ-T021 protocol descriptor cannot be silently changed in later Git history',async()=>{const {journal,client}=await initialized();const state=await journal.readHead();const bad=await client.createBlob(canonicalize({...journal.protocolDescriptor(),digest:'sha512'}));const tree=await client.createTree(state.commit.tree,{'controller-journal-v1.json':bad});const commit=await client.createCommit({message:'malicious protocol drift',tree,parents:[state.commit_oid]});client.forceSetRef('heads/journal',commit);await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_PROTOCOL_MISMATCH'));});
test('GJ-T022 multi-parent journal history is rejected',async()=>{const {journal,client,root}=await initialized();const append=await journal.append([singleEvent()]);const state=await journal.readHead();const merge=await client.createCommit({message:'bad merge',tree:state.commit.tree,parents:[append.commit_oid,root.commit_oid]});client.forceSetRef('heads/journal',merge);await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_JOURNAL_NONLINEAR'));});
test('GJ-T023 checkpoint previous commit must equal actual Git parent',async()=>{const {journal,client}=await initialized();await journal.append([singleEvent()]);const state=await journal.readHead();const cp={...state.checkpoint,previous_git_commit_oid:'0'.repeat(40)};const blob=await client.createBlob(canonicalize(cp));const tree=await client.createTree(state.commit.tree,{'checkpoint.json':blob});const commit=await client.createCommit({message:'bad checkpoint parent',tree,parents:[state.commit_oid]});client.forceSetRef('heads/journal',commit);await assert.rejects(()=>journal.verifyHead(),e=>code(e,'REMOTE_CHECKPOINT_PARENT_MISMATCH'));});
test('GJ-T024 empty append is explicitly rejected',async()=>{const {journal}=await initialized();await assert.rejects(()=>journal.append([]),e=>code(e,'EMPTY_JOURNAL_BATCH'));});
test('GJ-T025 checkpoint witness captures repo/ref/commit/size/head identity',async()=>{const {journal}=await initialized();await journal.append([singleEvent()]);const state=await journal.verifyHead(),w=journal.witnessFrom(state);assert.equal(w.repository_identity,JOURNAL_REPO);assert.equal(w.ref,'heads/journal');assert.equal(w.commit_oid,state.commit_oid);assert.equal(w.size,1);assert.equal(w.head_digest,state.checkpoint.head_digest);});
