import test from 'node:test';
import assert from 'node:assert/strict';
import { GitHubGitDataClient } from '../src/github-git-data-client.js';
import { ControllerError } from '../src/errors.js';

function response(status,body=null,headers={}){
  const text=body===null?'':typeof body==='string'?body:JSON.stringify(body);
  return {status,ok:status>=200&&status<300,headers:{get(name){const key=Object.keys(headers).find(k=>k.toLowerCase()===String(name).toLowerCase());return key?String(headers[key]):null;}},async text(){return text;}};
}
function mock(queue){const calls=[];const fetchImpl=async(url,options)=>{calls.push({url,options});const next=queue.shift();if(next instanceof Error)throw next;if(typeof next==='function')return next(url,options);return next;};return {fetchImpl,calls};}
function client(queue,tokenProvider=async()=>({token:'t'})){const m=mock(queue);return {client:new GitHubGitDataClient({owner:'o',repo:'journal',tokenProvider,fetchImpl:m.fetchImpl}),calls:m.calls};}
function code(e,c){return e instanceof ControllerError&&e.code===c;}

test('GH-T001 createBlob uses raw Git blob endpoint and UTF-8 encoding',async()=>{const {client:c,calls}=client([response(201,{sha:'abc'})]);assert.equal(await c.createBlob('hello'),'abc');assert.ok(calls[0].url.endsWith('/repos/o/journal/git/blobs'));assert.deepEqual(JSON.parse(calls[0].options.body),{content:'hello',encoding:'utf-8'});});
test('GH-T002 getBlob requests raw bytes rather than base64 JSON',async()=>{const {client:c,calls}=client([response(200,'raw-data')]);assert.equal(await c.getBlob('abc'),'raw-data');assert.equal(calls[0].options.headers.Accept,'application/vnd.github.raw+json');});
test('GH-T003 createTree emits non-executable blob entries and optional base tree',async()=>{const {client:c,calls}=client([response(201,{sha:'tree'})]);assert.equal(await c.createTree('base',{'segments/a.jsonl':'blob'}),'tree');assert.deepEqual(JSON.parse(calls[0].options.body),{tree:[{path:'segments/a.jsonl',mode:'100644',type:'blob',sha:'blob'}],base_tree:'base'});});
test('GH-T004 recursive tree truncation fails closed',async()=>{const {client:c}=client([response(200,{truncated:true,tree:[]})]);await assert.rejects(()=>c.getTree('x'),e=>code(e,'GITHUB_TREE_TRUNCATED'));});
test('GH-T005 getTree flattens only blob entries for journal verification',async()=>{const {client:c}=client([response(200,{truncated:false,tree:[{path:'segments',type:'tree',sha:'d'},{path:'checkpoint.json',type:'blob',sha:'b'}]})]);assert.deepEqual(await c.getTree('x'),{files:{'checkpoint.json':'b'}});});
test('GH-T006 commit request preserves exact parent list',async()=>{const {client:c,calls}=client([response(201,{sha:'commit'})]);await c.createCommit({message:'m',tree:'t',parents:['p']});assert.deepEqual(JSON.parse(calls[0].options.body),{message:'m',tree:'t',parents:['p']});});
test('GH-T007 ref create uses fully qualified refs/heads name',async()=>{const {client:c,calls}=client([response(201,{object:{sha:'c'}})]);await c.createRef('heads/journal','c');assert.deepEqual(JSON.parse(calls[0].options.body),{ref:'refs/heads/journal',sha:'c'});});
test('GH-T008 updateRef refuses force before any request',async()=>{const {client:c,calls}=client([]);await assert.rejects(()=>c.updateRef('heads/journal','n',{force:true}),e=>code(e,'GITHUB_FORCE_UPDATE_FORBIDDEN'));assert.equal(calls.length,0);});
test('GH-T009 expected-old mismatch fails before PATCH',async()=>{const {client:c,calls}=client([response(200,{object:{sha:'actual'}})]);await assert.rejects(()=>c.updateRef('heads/journal','next',{force:false,expectedOldOid:'expected'}),e=>code(e,'NON_FAST_FORWARD'));assert.equal(calls.length,1);assert.equal(calls[0].options.method,'GET');});
test('GH-T010 expected-old match still relies on force-false PATCH for race safety',async()=>{const {client:c,calls}=client([response(200,{object:{sha:'old'}}),response(200,{object:{sha:'next'}})]);assert.equal(await c.updateRef('heads/journal','next',{expectedOldOid:'old'}),'next');assert.equal(calls[1].options.method,'PATCH');assert.deepEqual(JSON.parse(calls[1].options.body),{sha:'next',force:false});});
test('GH-T011 401 refreshes installation token once',async()=>{let refreshes=0;const tokens=[];const tokenProvider=async({forceRefresh})=>{if(forceRefresh)refreshes+=1;const token=forceRefresh?'new':'old';tokens.push(token);return {token};};const {client:c,calls}=client([response(401,{message:'expired'}),response(200,{object:{sha:'x'}})],tokenProvider);assert.equal(await c.getRef('heads/journal'),'x');assert.equal(refreshes,1);assert.match(calls[0].options.headers.Authorization,/old/);assert.match(calls[1].options.headers.Authorization,/new/);});
test('GH-T012 repeated 401 after refresh becomes named authentication failure',async()=>{const {client:c}=client([response(401,{message:'expired'}),response(401,{message:'still expired'})],async({forceRefresh})=>({token:forceRefresh?'b':'a'}));await assert.rejects(()=>c.getRef('heads/journal'),e=>code(e,'GITHUB_AUTHENTICATION_FAILED'));});
test('GH-T013 Retry-After rate limit is surfaced without blind retry',async()=>{const {client:c,calls}=client([response(429,{message:'secondary rate limit'},{'retry-after':'60'})]);await assert.rejects(()=>c.getRef('heads/journal'),e=>code(e,'GITHUB_RATE_LIMITED')&&e.details.retry_after_seconds===60);assert.equal(calls.length,1);});
test('GH-T014 primary rate-limit reset is surfaced from 403 remaining zero',async()=>{const {client:c}=client([response(403,{message:'rate limit'},{'x-ratelimit-remaining':'0','x-ratelimit-reset':'200'})]);await assert.rejects(()=>c.getRef('heads/journal'),e=>code(e,'GITHUB_RATE_LIMITED')&&e.details.rate_limit_reset_epoch===200);});
test('GH-T015 ordinary 403 is permission denial and exposes accepted-permissions hint',async()=>{const {client:c}=client([response(403,{message:'forbidden'},{'x-accepted-github-permissions':'contents=write'})]);await assert.rejects(()=>c.createBlob('x'),e=>code(e,'GITHUB_PERMISSION_DENIED')&&e.details.accepted_permissions==='contents=write');});
test('GH-T016 mutating network failure is explicitly ambiguous',async()=>{const {client:c}=client([new Error('socket reset')]);await assert.rejects(()=>c.createBlob('x'),e=>code(e,'GITHUB_REMOTE_STATE_UNKNOWN')&&e.details.ambiguous===true);});
test('GH-T017 read network failure is unknown but marked non-mutating',async()=>{const {client:c}=client([new Error('socket reset')]);await assert.rejects(()=>c.getRef('heads/journal'),e=>code(e,'GITHUB_REMOTE_STATE_UNKNOWN')&&e.details.ambiguous===false);});
test('GH-T018 409 ref conflict maps to NON_FAST_FORWARD for journal retry logic',async()=>{const {client:c}=client([response(200,{object:{sha:'old'}}),response(409,{message:'conflict'})]);await assert.rejects(()=>c.updateRef('heads/journal','next',{expectedOldOid:'old'}),e=>code(e,'NON_FAST_FORWARD'));});
test('GH-T019 422 stays distinct until real GitHub integration proves safe classification',async()=>{const {client:c}=client([response(200,{object:{sha:'old'}}),response(422,{message:'Validation Failed'})]);await assert.rejects(()=>c.updateRef('heads/journal','next',{expectedOldOid:'old'}),e=>code(e,'GITHUB_VALIDATION_FAILED'));});
