import test from 'node:test';
import assert from 'node:assert/strict';
import { ControllerKernel, ControllerError } from '../src/kernel.js';
import { MemoryDurableJournal, publishPendingOutbox } from '../src/durable-journal.js';
import { verifyDurableJournal } from '../src/journal-integrity.js';
import { uuidv7 } from '../src/canonical.js';

const SUBJECT={algorithm:'sha1',oid:'0123456789abcdef0123456789abcdef01234567'};
function command(){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'user:test',source:'chatgpt'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject:{...SUBJECT}},preconditions:{},intent:{task:'journal-integrity'},constraints:{},required_policy_version:null};}
function assertCode(fn,code){assert.throws(fn,e=>e instanceof ControllerError&&e.code===code);}
async function committedHistory(){const k=new ControllerKernel(':memory:');const tx=k.acceptCommand(command()).transaction_id;k.admitTransaction(tx);k.activateTransaction(tx);const op=k.createOperation(tx,{resourceId:'r'});k.transitionOperation(op,'READY');k.waitTransaction(tx,'interleave after operation stream');const journal=new MemoryDurableJournal();const results=await publishPendingOutbox(k,journal);assert.ok(results.every(r=>r.sealed));const entries=await journal.list(),checkpoint=await journal.getCheckpoint();k.close();return {entries,checkpoint};}

test('JI-T001 committed journal verifies as one contiguous global history',async()=>{const {entries,checkpoint}=await committedHistory();const verified=verifyDurableJournal(entries,{expectedCheckpoint:checkpoint});assert.equal(verified.checkpoint.size,entries.length);assert.equal(verified.checkpoint.head_digest,checkpoint.head_digest);});
test('JI-T002 deleting an entire middle stream is detected by global position gap',async()=>{const {entries}=await committedHistory();const operationStream=entries.find(e=>e.stream_id.startsWith('operation:')).stream_id;const stripped=entries.filter(e=>e.stream_id!==operationStream);assertCode(()=>verifyDurableJournal(stripped),'JOURNAL_GAP');});
test('JI-T003 tail truncation requires anchored checkpoint and is detected against it',async()=>{const {entries,checkpoint}=await committedHistory();const truncated=entries.slice(0,-1);assert.equal(verifyDurableJournal(truncated).checkpoint.size,checkpoint.size-1);assertCode(()=>verifyDurableJournal(truncated,{expectedCheckpoint:checkpoint}),'JOURNAL_CHECKPOINT_MISMATCH');});
test('JI-T004 stale compare-and-swap checkpoint cannot fork journal head',async()=>{const k=new ControllerKernel(':memory:');const tx=k.acceptCommand(command()).transaction_id;k.admitTransaction(tx);const raw=k.exportEvents();k.close();const j=new MemoryDurableJournal();const empty=await j.getCheckpoint();await j.putIfAbsent(raw[0],{expectedCheckpoint:empty});const afterOne=await j.getCheckpoint();await j.putIfAbsent(raw[1],{expectedCheckpoint:afterOne});await assert.rejects(()=>j.putIfAbsent({...raw[1],event_id:uuidv7(),event_digest:'a'.repeat(64)},{expectedCheckpoint:empty}),e=>e instanceof ControllerError&&e.code==='JOURNAL_HEAD_CONFLICT');});
test('JI-T005 lost acknowledgement advances global checkpoint exactly once',async()=>{const k=new ControllerKernel(':memory:');k.acceptCommand(command());const j=new MemoryDurableJournal({failAfter:1});const result=await publishPendingOutbox(k,j);assert.equal(result.length,1);assert.equal(result[0].sealed,true);assert.equal(result[0].recovered_after_error,true);const checkpoint=await j.getCheckpoint();assert.equal(checkpoint.size,1);assert.equal((await j.list()).length,1);k.close();});
