import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { ControllerKernel } from '../src/kernel.js';
import { ControllerKernelV4, KERNEL_V4_INVARIANTS } from '../src/kernel-v4.js';
import { uuidv7 } from '../src/canonical.js';

const subject={algorithm:'sha1',oid:'a'.repeat(40)};
function command(){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'test',source:'test'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject:subject},preconditions:{},intent:{},constraints:{},required_policy_version:null};}
function plan(txId,opId=uuidv7(),overrides={}){return {plan_id:uuidv7(),transaction_id:txId,operation_id:opId,operation_type:'repository-change',subject_repository:'BFochtman746/system-master',subject,resource_id:'repo:system-master',allowed_actions:['checkout-subject','create-workspace','analyze','edit-candidate','build','test','collect-evidence','emit-result'],workspace:{kind:'git-worktree',candidate_ref:`refs/heads/controller-candidate/${opId}`},worker_requirements:{capabilities:['git','node']},dispatch:{priority:500,not_before:null,max_attempts:3,lease_ttl_ms:60000,execution_timeout_ms:3600000,retry:{mode:'transient',max_retries:2,base_delay_ms:1000,max_delay_ms:60000,jitter:'full'}},...structuredClone(overrides)};}
function admitted(k){const a=k.acceptCommand(command(),{controllerVersion:'c1',policyVersion:'p1'});k.admitTransaction(a.transaction_id,{operations:'all_succeeded'});return a.transaction_id;}

test('KV4-T001 new V4 kernel migrates cleanly to schema 4',()=>{const k=new ControllerKernelV4();assert.equal(k.schemaVersion(),4);k.close();});
test('KV4-T002 V4 database reopens idempotently with V4 kernel',()=>{const dir=mkdtempSync(join(tmpdir(),'controller-v4-'));const p=join(dir,'c.db');let k=new ControllerKernelV4(p);k.close();k=new ControllerKernelV4(p);assert.equal(k.schemaVersion(),4);k.close();rmSync(dir,{recursive:true,force:true});});
test('KV4-T003 older V3 kernel fails closed on V4 database',()=>{const dir=mkdtempSync(join(tmpdir(),'controller-v4-old-'));const p=join(dir,'c.db');const k=new ControllerKernelV4(p);k.close();assert.throws(()=>new ControllerKernel(p),e=>e.code==='SCHEMA_TOO_NEW');rmSync(dir,{recursive:true,force:true});});
test('KV4-T004 legacy createOperation is forbidden under V4',()=>{const k=new ControllerKernelV4();const tx=admitted(k);assert.throws(()=>k.createOperation(tx,{resourceId:'repo:system-master'}),e=>e.code==='OPERATION_PLAN_REQUIRED');k.close();});
test('KV4-T005 planned operation and immutable plan persist atomically',()=>{const k=new ControllerKernelV4();const tx=admitted(k),p=plan(tx);const r=k.createPlannedOperation(p);assert.equal(r.operation_id,p.operation_id);assert.equal(k.getOperationSnapshot(p.operation_id).state,'PLANNED');assert.equal(k.getOperationPlan(p.operation_id).plan_digest,r.plan_digest);k.close();});
test('KV4-T006 operation.planned semantic event contains full bound plan',()=>{const k=new ControllerKernelV4();const tx=admitted(k),p=plan(tx);k.createPlannedOperation(p);const row=k.db.prepare("SELECT data_json FROM events WHERE stream_id=? AND event_type='operation.planned'").get(`operation:${p.operation_id}`);const data=JSON.parse(row.data_json);assert.equal(data.plan.plan_id,p.plan_id);assert.equal(data.plan.plan_digest,k.getOperationPlan(p.operation_id).plan_digest);k.close();});
test('KV4-T007 plan subject must exactly match transaction subject',()=>{const k=new ControllerKernelV4();const tx=admitted(k),p=plan(tx,uuidv7(),{subject:{algorithm:'sha1',oid:'b'.repeat(40)}});assert.throws(()=>k.createPlannedOperation(p),e=>e.code==='OPERATION_PLAN_BINDING_MISMATCH');assert.equal(k.db.prepare('SELECT COUNT(*) n FROM operations').get().n,0);k.close();});
test('KV4-T008 plan transaction id must name an admitted transaction',()=>{const k=new ControllerKernelV4();const p=plan(uuidv7());assert.throws(()=>k.createPlannedOperation(p),e=>e.code==='NOT_FOUND');k.close();});
test('KV4-T009 READY transition requires bound noncorrupt plan',()=>{const k=new ControllerKernelV4();const tx=admitted(k),p=plan(tx);k.createPlannedOperation(p);k.transitionOperation(p.operation_id,'READY','PLANNED');assert.equal(k.getOperationSnapshot(p.operation_id).state,'READY');k.close();});
test('KV4-T010 stored plan corruption fails before READY transition',()=>{const k=new ControllerKernelV4();const tx=admitted(k),p=plan(tx);k.createPlannedOperation(p);k.db.prepare('UPDATE operation_plans SET plan_json=? WHERE operation_id=?').run('{}',p.operation_id);assert.throws(()=>k.transitionOperation(p.operation_id,'READY','PLANNED'));assert.equal(k.getOperationSnapshot(p.operation_id).state,'PLANNED');k.close();});
test('KV4-T011 ready listing returns only plan-bound READY operations',()=>{const k=new ControllerKernelV4();const tx=admitted(k),p1=plan(tx),p2=plan(tx);k.createPlannedOperation(p1);k.createPlannedOperation(p2);k.transitionOperation(p1.operation_id,'READY','PLANNED');const ready=k.listReadyOperationSnapshots();assert.equal(ready.length,1);assert.equal(ready[0].snapshot.operation_id,p1.operation_id);assert.equal(ready[0].plan.operation_id,p1.operation_id);k.close();});
test('KV4-T012 lease attempt count derives from durable lease history',()=>{const k=new ControllerKernelV4();const tx=admitted(k),p=plan(tx);k.createPlannedOperation(p);k.transitionOperation(p.operation_id,'READY','PLANNED');const l=k.acquireLease(p.operation_id,p.resource_id,'worker-1',1000,0);assert.equal(k.leaseAttemptCount(p.operation_id),1);k.releaseLease(l.lease_id,l.generation,1);const l2=k.acquireLease(p.operation_id,p.resource_id,'worker-2',1000,2);assert.equal(k.leaseAttemptCount(p.operation_id),2);k.releaseLease(l2.lease_id,l2.generation,3);k.close();});
test('KV4-T013 operation plan survives database restart exactly',()=>{const dir=mkdtempSync(join(tmpdir(),'controller-v4-plan-'));const db=join(dir,'c.db');let k=new ControllerKernelV4(db);const tx=admitted(k),p=plan(tx);const bound=k.createPlannedOperation(p);k.close();k=new ControllerKernelV4(db);assert.equal(k.getOperationPlan(p.operation_id).plan_digest,bound.plan_digest);assert.equal(k.getOperationPlan(p.operation_id).workspace.candidate_ref,p.workspace.candidate_ref);k.close();rmSync(dir,{recursive:true,force:true});});
test('KV4-T014 operation id cannot be rebound to a different plan',()=>{const k=new ControllerKernelV4();const tx=admitted(k),op=uuidv7();k.createPlannedOperation(plan(tx,op));assert.throws(()=>k.createPlannedOperation(plan(tx,op)),e=>e.code==='OPERATION_ID_CONFLICT');k.close();});
test('KV4-T015 V4 invariants explicitly make plans prerequisite to READY',()=>{assert.equal(KERNEL_V4_INVARIANTS.schema_version,4);assert.equal(KERNEL_V4_INVARIANTS.plan_bound_before_ready,true);assert.equal(KERNEL_V4_INVARIANTS.plan_in_semantic_event,true);assert.equal(KERNEL_V4_INVARIANTS.old_kernel_fails_closed_on_v4,true);});
