import test from 'node:test';
import assert from 'node:assert/strict';
import { ControllerKernel, ControllerError, commandFingerprint } from '../src/kernel.js';
import { canonicalize, uuidv7, isUuidV7 } from '../src/canonical.js';

const SHA='0123456789abcdef0123456789abcdef01234567';
function command(overrides={}){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'user:test',source:'chatgpt'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject_sha:SHA},preconditions:{},intent:{task:'x'},constraints:{},required_policy_version:null,...overrides};}
function kernel(){return new ControllerKernel(':memory:');}
function assertCode(fn,code){assert.throws(fn,e=>e instanceof ControllerError&&e.code===code);}
function activeTx(k,contract={operations:'all_succeeded'}){const tx=k.acceptCommand(command()).transaction_id;k.admitTransaction(tx,contract);k.activateTransaction(tx);return tx;}
function readyOp(k,resource='r'){const tx=activeTx(k),o=k.createOperation(tx,{resourceId:resource});k.transitionOperation(o,'READY');return {tx,o};}
function runningOp(k,resource='r',nowMs=Date.now()){const {tx,o}=readyOp(k,resource),l=k.acquireLease(o,resource,'worker',60000,nowMs);k.startLeasedOperation({leaseId:l.lease_id,generation:l.generation,operationId:o,nowMs});return {tx,o,l};}

test('CF-T001 duplicate delivery creates one transaction',()=>{const k=kernel(),c=command(),a=k.acceptCommand(c),b=k.acceptCommand(c);assert.equal(a.transaction_id,b.transaction_id);assert.equal(k.db.prepare('select count(*) n from transactions').get().n,1);k.close();});
test('CF-T002 same command id changed payload conflicts',()=>{const k=kernel(),c=command();k.acceptCommand(c);const d=structuredClone(c);d.intent.task='changed';assertCode(()=>k.acceptCommand(d),'IDEMPOTENCY_CONFLICT');k.close();});
test('CF-T003 DB uniqueness forbids second transaction for command',()=>{const k=kernel(),c=command();k.acceptCommand(c);assert.throws(()=>k.db.prepare('INSERT INTO transactions(transaction_id,command_id,state,controller_version,policy_version,subject_repo,subject_sha,completion_contract_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(uuidv7(),c.command_id,'OPEN','x','x','r',SHA,null,new Date().toISOString(),new Date().toISOString()));k.close();});
test('CF-T004 one active lease per resource',()=>{const k=kernel(),{o}=readyOp(k);k.acquireLease(o,'r','A');assertCode(()=>k.acquireLease(o,'r','B'),'LEASE_CONFLICT');k.close();});
test('CF-T005 new generation fences old worker',()=>{const k=kernel(),tx=activeTx(k),o1=k.createOperation(tx,{resourceId:'r'});k.transitionOperation(o1,'READY');const a=k.acquireLease(o1,'r','A',1,1000);k.startLeasedOperation({leaseId:a.lease_id,generation:a.generation,operationId:o1,nowMs:1000});k.transitionOperation(o1,'STALE');const o2=k.createOperation(tx,{resourceId:'r'});k.transitionOperation(o2,'READY');const b=k.acquireLease(o2,'r','B',1000,1002);assert.equal(b.generation,a.generation+1);assertCode(()=>k.submitWorkerResult({leaseId:a.lease_id,generation:a.generation,operationId:o1,result:'SUCCEEDED',nowMs:1003}),'STALE_LEASE');k.close();});
test('CF-T006 released lease cannot reactivate',()=>{const k=kernel(),{o}=readyOp(k),l=k.acquireLease(o,'r','A',1000,1000);k.releaseLease(l.lease_id,l.generation,1001);assertCode(()=>k.heartbeatLease(l.lease_id,l.generation,1002),'STALE_LEASE');k.close();});
test('CF-T007 heartbeat does not create semantic event',()=>{const k=kernel(),{o}=readyOp(k),l=k.acquireLease(o,'r','A',1000,1000),n=k.db.prepare('select count(*) n from events').get().n;k.heartbeatLease(l.lease_id,l.generation,1001);assert.equal(k.db.prepare('select count(*) n from events').get().n,n);k.close();});
test('CF-T008 clock/order independence via canonical content',()=>{assert.equal(canonicalize({b:1,a:2}),canonicalize({a:2,b:1}));});
test('CF-T009 optimistic event concurrency allows one N+1',()=>{const k=kernel();k.atomic(()=>k.appendEvent('x',0,'a',{}));assertCode(()=>k.atomic(()=>k.appendEvent('x',0,'b',{})),'CONCURRENCY_CONFLICT');k.close();});
test('CF-T010 event gap detected',()=>{const k=kernel();k.db.prepare('insert into events values (?,?,?,?,?,?,?,?,?)').run(uuidv7(),'controller.event.v1','x',2,'a',new Date().toISOString(),'{}',null,'bad');assertCode(()=>k.verifyStream('x'),'EVENT_GAP');k.close();});
test('CF-T011 changed event byte fails digest',()=>{const k=kernel();k.atomic(()=>k.appendEvent('x',0,'a',{x:1}));k.db.prepare("update events set data_json=? where stream_id='x'").run('{"x":2}');assertCode(()=>k.verifyStream('x'),'EVENT_INTEGRITY_FAILURE');k.close();});
test('CF-T012 canonical fingerprint ignores key insertion order',()=>{const c=command(),d={...c,intent:{z:1,a:2}},e={...c,intent:{a:2,z:1}};assert.equal(commandFingerprint(d),commandFingerprint(e));});
test('CF-T013 unknown command property rejected',()=>{const k=kernel(),c=command();c.typo=true;assertCode(()=>k.acceptCommand(c),'SCHEMA_UNKNOWN_FIELD');k.close();});
test('CF-T014 malformed timestamp rejected',()=>{const k=kernel(),c=command({created_at:'2026-99-99T99:99:99Z'});assertCode(()=>k.acceptCommand(c),'SCHEMA_INVALID');k.close();});
test('CF-T015 outbox survives publication failure',()=>{const k=kernel();k.acceptCommand(command());const o=k.pendingOutbox()[0];k.recordOutboxFailure(o.outbox_id,'offline');assert.equal(k.pendingOutbox()[0].attempts,1);k.close();});
test('CF-T016 duplicate sealing is idempotent',()=>{const k=kernel();k.acceptCommand(command());const o=k.pendingOutbox()[0];k.markOutboxSealed(o.outbox_id);k.markOutboxSealed(o.outbox_id);assert.equal(k.pendingOutbox().length,0);k.close();});
test('CF-T017 promotion cannot execute before durable authorization seal',()=>{const k=kernel(),tx=activeTx(k,{operations:'none',qualification:'required',promotion:'required'}),q=k.createQualification(tx,SHA,'p');k.finishQualification(q,'PASSED');const p=k.requestPromotion(tx,q,SHA);k.authorizePromotion(p);let applied=0;assertCode(()=>k.executePromotion(p,{apply(){applied++;},observe(){return false;}}),'DURABILITY_BARRIER_NOT_MET');assert.equal(applied,0);k.close();});
test('CF-T018 timeout after applied promotion reconciles without reapply',()=>{const k=kernel(),tx=activeTx(k,{operations:'none',qualification:'required',promotion:'required'}),q=k.createQualification(tx,SHA,'p');k.finishQualification(q,'PASSED');const p=k.requestPromotion(tx,q,SHA);k.authorizePromotion(p);k.sealAllOutbox();let applied=0,exists=false;const a={apply(){applied++;exists=true;throw new Error('timeout');},observe(){return exists;}};assert.equal(k.executePromotion(p,a),'RECONCILIATION_REQUIRED');assert.equal(k.executePromotion(p,a),'SUCCEEDED');assert.equal(applied,1);k.close();});
test('CF-T019 PASS for S1 cannot authorize S2',()=>{const k=kernel(),tx=activeTx(k,{operations:'none',qualification:'required'}),q=k.createQualification(tx,SHA,'p');k.finishQualification(q,'PASSED');assertCode(()=>k.requestPromotion(tx,q,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'),'SUBJECT_MISMATCH');k.close();});
test('CF-T020 qualifier surface has no subject-write path',()=>{const qualifierView=Object.freeze({subject:{repository:'r',sha:SHA},read:()=>Buffer.from('x')});assert.equal('write' in qualifierView,false);assert.ok(Object.isFrozen(qualifierView));});
test('CF-T021 worker cannot request promotion or arbitrary DB mutation',()=>{const k=kernel(),{o,l}=runningOp(k);assertCode(()=>k.submitWorkerResult({leaseId:l.lease_id,generation:l.generation,operationId:o,result:'PROMOTE'}),'WORKER_AUTHORITY_DENIED');k.close();});
test('CF-T022 late old-lease result rejected after replacement operation',()=>{const k=kernel(),tx=activeTx(k),o1=k.createOperation(tx,{resourceId:'r'});k.transitionOperation(o1,'READY');const a=k.acquireLease(o1,'r','A',1,1000);k.startLeasedOperation({leaseId:a.lease_id,generation:a.generation,operationId:o1,nowMs:1000});k.transitionOperation(o1,'STALE');const o2=k.createOperation(tx,{resourceId:'r'});k.transitionOperation(o2,'READY');const b=k.acquireLease(o2,'r','B',1000,1002);k.startLeasedOperation({leaseId:b.lease_id,generation:b.generation,operationId:o2,nowMs:1002});k.submitWorkerResult({leaseId:b.lease_id,generation:b.generation,operationId:o2,result:'SUCCEEDED',nowMs:1003});assertCode(()=>k.submitWorkerResult({leaseId:a.lease_id,generation:a.generation,operationId:o1,result:'FAILED',nowMs:1004}),'STALE_LEASE');k.close();});
test('CF-T023 qualification rerun gets new identity',()=>{const k=kernel(),tx=activeTx(k,{operations:'none',qualification:'required'}),q1=k.createQualification(tx,SHA,'p'),q2=k.createQualification(tx,SHA,'p');assert.notEqual(q1,q2);k.close();});
test('CF-T024 projection regenerates from event journal',()=>{const k=kernel(),tx=activeTx(k),o=k.createOperation(tx);k.transitionOperation(o,'READY');const events=k.exportEvents();const p=ControllerKernel.replay(events);assert.equal(p.transactions[tx].state,'ACTIVE');assert.equal(p.operations[o].state,'READY');k.close();});
test('CF-T025 stale projection reports STALE not guessed freshness',()=>{const k=kernel();k.acceptCommand(command({created_at:'2026-01-01T00:00:00.000Z'}));const p=k.projection(1,Date.now()+10000);assert.equal(p.freshness,'STALE');k.close();});
test('CF-T026 semantic state survives local DB loss via event replay',()=>{const k=kernel(),tx=activeTx(k),o=k.createOperation(tx);k.transitionOperation(o,'READY');const events=k.exportEvents();k.close();const recovered=ControllerKernel.replay(events);assert.equal(recovered.operations[o].state,'READY');assert.equal(recovered.transactions[tx].subject_sha,SHA);});
test('CF-T027 unsupported historic event schema fails closed',()=>{const k=kernel();k.acceptCommand(command());const events=k.exportEvents();events[0].event_schema='controller.event.v999';assertCode(()=>ControllerKernel.replay(events),'UNSUPPORTED_EVENT_SCHEMA');k.close();});
test('CF-T028 ambiguous external mutation is observed before any retry',()=>{const k=kernel(),tx=activeTx(k,{operations:'none',qualification:'required',promotion:'required'}),q=k.createQualification(tx,SHA,'p');k.finishQualification(q,'PASSED');const p=k.requestPromotion(tx,q,SHA);k.authorizePromotion(p);k.sealAllOutbox();let apply=0,observe=0,exists=false;const a={apply(){apply++;exists=true;throw new Error('lost response');},observe(){observe++;return exists;}};k.executePromotion(p,a);k.executePromotion(p,a);assert.equal(apply,1);assert.equal(observe,2);k.close();});
test('CF-T029 out-of-order transport replay reconstructs stream by version',()=>{const k=kernel(),tx=activeTx(k),o=k.createOperation(tx);k.transitionOperation(o,'READY');const events=k.exportEvents().reverse();const state=ControllerKernel.replay(events);assert.equal(state.operations[o].state,'READY');k.close();});
test('CF-T030 historic semantic version mismatch cannot be reinterpreted',()=>{const k=kernel();k.acceptCommand(command());const events=k.exportEvents();events[0].event_schema='controller.event.v2';assertCode(()=>ControllerKernel.replay(events),'UNSUPPORTED_EVENT_SCHEMA');k.close();});

test('extra: operation state machine rejects direct success',()=>{const k=kernel(),tx=activeTx(k),o=k.createOperation(tx);assertCode(()=>k.transitionOperation(o,'SUCCEEDED'),'WORKER_RESULT_REQUIRED');k.close();});
test('extra: terminal operation cannot transition',()=>{const k=kernel(),{o,l}=runningOp(k);k.submitWorkerResult({leaseId:l.lease_id,generation:l.generation,operationId:o,result:'SUCCEEDED'});assertCode(()=>k.transitionOperation(o,'FAILED'),'ILLEGAL_TRANSITION');k.close();});
test('extra: command supplied fingerprint must match',()=>{const k=kernel(),c=command();c.fingerprint='0'.repeat(64);assertCode(()=>k.acceptCommand(c),'FINGERPRINT_MISMATCH');k.close();});
test('extra: UUIDv7 generator marks version 7',()=>{assert.ok(isUuidV7(uuidv7()));});
test('extra: canonicalizer rejects non-finite and lone surrogate',()=>{assert.throws(()=>canonicalize(NaN));assert.throws(()=>canonicalize('\ud800'));});
test('extra: operation cannot run without live fenced lease',()=>{const k=kernel(),{o}=readyOp(k);assertCode(()=>k.transitionOperation(o,'RUNNING'),'LEASE_REQUIRED');k.close();});
test('extra: lease resource must equal planned resource',()=>{const k=kernel(),{o}=readyOp(k,'planned');assertCode(()=>k.acquireLease(o,'other','worker'),'LEASE_RESOURCE_MISMATCH');k.close();});
test('extra: lease cannot be acquired for non-READY operation',()=>{const k=kernel(),tx=activeTx(k),o=k.createOperation(tx,{resourceId:'r'});assertCode(()=>k.acquireLease(o,'r','worker'),'LEASE_STATE_INVALID');k.close();});
test('extra: transaction cannot succeed before completion contract is satisfied',()=>{const k=kernel(),tx=activeTx(k),o=k.createOperation(tx,{resourceId:'r'});k.transitionOperation(o,'READY');assertCode(()=>k.completeTransaction(tx),'TRANSACTION_INCOMPLETE');k.close();});
test('extra: transaction completes only after required operation succeeds',()=>{const k=kernel(),{tx,o,l}=runningOp(k);k.submitWorkerResult({leaseId:l.lease_id,generation:l.generation,operationId:o,result:'SUCCEEDED'});assert.equal(k.completeTransaction(tx),'SUCCEEDED');assert.equal(k.db.prepare('SELECT state FROM transactions WHERE transaction_id=?').get(tx).state,'SUCCEEDED');k.close();});
test('extra: promotion-required contract implies qualification-required',()=>{const k=kernel(),tx=k.acceptCommand(command()).transaction_id;assertCode(()=>k.admitTransaction(tx,{operations:'none',promotion:'required'}),'COMPLETION_CONTRACT_INVALID');k.close();});
test('extra: command schema URI is enforced',()=>{const k=kernel(),c=command({schema:'controller://schemas/command/v999'});assertCode(()=>k.acceptCommand(c),'UNSUPPORTED_SCHEMA');k.close();});
