import test from 'node:test';
import assert from 'node:assert/strict';
import { CANONICAL_JOURNAL_REPOSITORY, CANONICAL_SUBJECT_REPOSITORY, validateLiveQualificationConfig, preflightLiveJournalQualification } from '../src/live-journal-qualification.js';
import { ControllerError } from '../src/errors.js';

function code(e,c){return e instanceof ControllerError&&e.code===c;}
function config(overrides={}){return {journalRepository:'BFochtman746/system-master-controller-journal',subjectRepository:'BFochtman746/system-master',destructiveQualification:true,expectedOwner:'BFochtman746',qualificationId:'002C-C-test',...overrides};}
function metadata(overrides={}){return {id:24680,full_name:'BFochtman746/system-master-controller-journal',name:'system-master-controller-journal',owner:{login:'BFochtman746'},private:true,default_branch:'main',archived:false,permissions:{push:true},...overrides};}
const seedHead='1'.repeat(40),seedTree='2'.repeat(40);
function freshClient({journalRef=null,parents=[],paths=['README.md']}={}){return {
  async getRef(ref){if(ref==='heads/main')return seedHead;if(ref==='heads/journal'){if(journalRef!==null)return journalRef;const e=new ControllerError('GITHUB_NOT_FOUND','missing',{status:404});e.status=404;throw e;}throw new Error(`unexpected ref ${ref}`);},
  async getCommit(sha){assert.equal(sha,seedHead);return {message:'seed',tree:seedTree,parents};},
  async getTree(sha){assert.equal(sha,seedTree);return {files:Object.fromEntries(paths.map((p,i)=>[p,String(i+3).repeat(40)]))};}
};}

test('LQ-T001 System Master is forbidden as journal even if subject config is changed',()=>{assert.throws(()=>validateLiveQualificationConfig(config({journalRepository:'BFochtman746/system-master',subjectRepository:'BFochtman746/other'})),e=>code(e,'LIVE_SYSTEM_MASTER_JOURNAL_FORBIDDEN'));});
test('LQ-T002 subject and journal repositories must be distinct',()=>{assert.throws(()=>validateLiveQualificationConfig(config({subjectRepository:'BFochtman746/system-master-controller-journal'})),e=>code(e,'LIVE_JOURNAL_SUBJECT_COLLISION'));});
test('LQ-T003 destructive live qualification requires explicit boolean opt-in',()=>{assert.throws(()=>validateLiveQualificationConfig(config({destructiveQualification:false})),e=>code(e,'LIVE_DESTRUCTIVE_OPT_IN_REQUIRED'));});
test('LQ-T004 expected owner mismatch fails before repository lookup',()=>{assert.throws(()=>validateLiveQualificationConfig(config({expectedOwner:'someoneelse'})),e=>code(e,'LIVE_REPOSITORY_OWNER_MISMATCH'));});
test('LQ-T005 qualification identity is mandatory',()=>{assert.throws(()=>validateLiveQualificationConfig(config({qualificationId:''})),e=>code(e,'LIVE_QUALIFICATION_ID_REQUIRED'));});
test('LQ-T006 resolved repository identity must equal configured dedicated repository',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata({full_name:'BFochtman746/not-the-journal'}),journalClient:freshClient()}),e=>code(e,'LIVE_REPOSITORY_IDENTITY_MISMATCH'));});
test('LQ-T007 archived repository is rejected',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata({archived:true}),journalClient:freshClient()}),e=>code(e,'LIVE_REPOSITORY_ARCHIVED'));});
test('LQ-T008 branchless repository is rejected before seed ref lookup',async()=>{let refReads=0;const client=freshClient();const wrapped={...client,async getRef(ref){refReads+=1;return client.getRef(ref);}};await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata({default_branch:null}),journalClient:wrapped}),e=>code(e,'LIVE_REPOSITORY_UNSEEDED'));assert.equal(refReads,0);});
test('LQ-T009 known missing write permission is rejected',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata({permissions:{push:false}}),journalClient:freshClient()}),e=>code(e,'LIVE_REPOSITORY_WRITE_PERMISSION_MISSING'));});
test('LQ-T010 preexisting heads/journal is rejected for destructive fresh-repo qualification',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata(),journalClient:freshClient({journalRef:'abc'})}),e=>code(e,'LIVE_JOURNAL_REF_ALREADY_EXISTS'));});
test('LQ-T011 canonical private root-seeded dedicated repository passes preflight without mutation',async()=>{let reads=0;const result=await preflightLiveJournalQualification({config:config(),repositoryReader:async()=>{reads+=1;return metadata();},journalClient:freshClient()});assert.equal(reads,1);assert.equal(result.qualified_for_mutation,true);assert.equal(result.journalRepository,CANONICAL_JOURNAL_REPOSITORY);assert.equal(result.journalRepositoryId,24680);assert.equal(result.subjectRepository,CANONICAL_SUBJECT_REPOSITORY);assert.equal(result.defaultBranch,'main');assert.equal(result.seedHead,seedHead);});
test('LQ-T012 noncanonical journal repository is rejected before repository lookup',()=>{assert.throws(()=>validateLiveQualificationConfig(config({journalRepository:'BFochtman746/controller-journal'})),e=>code(e,'LIVE_JOURNAL_REPOSITORY_NOT_CANONICAL'));});
test('LQ-T013 noncanonical subject repository is rejected before repository lookup',()=>{assert.throws(()=>validateLiveQualificationConfig(config({subjectRepository:'BFochtman746/other-subject'})),e=>code(e,'LIVE_SUBJECT_REPOSITORY_NOT_CANONICAL'));});
test('LQ-T014 public journal repository is rejected',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata({private:false}),journalClient:freshClient()}),e=>code(e,'LIVE_REPOSITORY_MUST_BE_PRIVATE'));});
test('LQ-T015 non-main default branch is rejected',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata({default_branch:'master'}),journalClient:freshClient()}),e=>code(e,'LIVE_DEFAULT_BRANCH_MISMATCH'));});
test('LQ-T016 non-root seed history is rejected',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata(),journalClient:freshClient({parents:['f'.repeat(40)]})}),e=>code(e,'LIVE_SEED_HISTORY_NOT_MINIMAL'));});
test('LQ-T017 seed tree must contain only README.md',async()=>{await assert.rejects(()=>preflightLiveJournalQualification({config:config(),repositoryReader:async()=>metadata(),journalClient:freshClient({paths:['README.md','extra.txt']})}),e=>code(e,'LIVE_SEED_TREE_NOT_MINIMAL'));});
