import test from 'node:test';
import assert from 'node:assert/strict';
import { digestC1Receipt } from '../src/live-c1-runner.js';
import { authorizeC2Initialization, validateC1ReceiptForC2 } from '../src/live-c2-admission.js';

const controllerCommit='a'.repeat(40),policyDigest='b'.repeat(64),seedHead='1'.repeat(40),seedTree='2'.repeat(40);
function receipt(overrides={}){const r={schema:'controller://qualification/c1-preflight/v2',qualification_id:'C1-LIVE-001',result:'PASS',qualified_for_live_journal_mutation:true,controller_commit:controllerCommit,policy_digest:policyDigest,journal_repository:'bfochtman746/system-master-controller-journal',journal_repository_id:24680,subject_repository:'bfochtman746/system-master',default_branch:'main',seed_head:seedHead,...overrides};return {...r,receipt_digest:digestC1Receipt(r)};}
function repo(overrides={}){return {id:24680,full_name:'BFochtman746/system-master-controller-journal',name:'system-master-controller-journal',owner:{login:'BFochtman746'},private:true,archived:false,default_branch:'main',permissions:{push:true},...overrides};}
function client({head=seedHead,journalExists=false,parents=[],paths=['README.md']}={}){return {async getRef(ref){if(ref==='heads/main')return head;if(ref==='heads/journal'){if(journalExists)return 'f'.repeat(40);const e=Object.assign(new Error('missing'),{code:'GITHUB_NOT_FOUND',status:404});throw e;}throw new Error(`unexpected ${ref}`);},async getCommit(sha){return {message:'seed',tree:seedTree,parents};},async getTree(sha){return {files:Object.fromEntries(paths.map((p,i)=>[p,String(i+3).repeat(40)]))};}};}
const expected={expectedControllerCommit:controllerCommit,expectedPolicyDigest:policyDigest};

test('C2A-T001 exact C1 PASS and unchanged live seed authorize C2 initialization',async()=>{const r=receipt();const result=await authorizeC2Initialization({receipt:r,...expected,repositoryReader:async()=>repo(),journalClient:client()});assert.equal(result.authorized,true);assert.equal(result.c1_receipt_digest,r.receipt_digest);assert.equal(result.seed_head,seedHead);});
test('C2A-T002 modified C1 receipt is rejected by digest before live reads',async()=>{const r=receipt();r.seed_head='e'.repeat(40);let reads=0;await assert.rejects(()=>authorizeC2Initialization({receipt:r,...expected,repositoryReader:async()=>{reads++;return repo();},journalClient:client()}),e=>e.code==='C2_C1_RECEIPT_DIGEST_MISMATCH');assert.equal(reads,0);});
test('C2A-T003 different controller commit rejects old C1 PASS',()=>{assert.throws(()=>validateC1ReceiptForC2(receipt(),{expectedControllerCommit:'c'.repeat(40),expectedPolicyDigest:policyDigest}),e=>e.code==='C2_CONTROLLER_VERSION_MISMATCH');});
test('C2A-T004 different policy digest rejects old C1 PASS',()=>{assert.throws(()=>validateC1ReceiptForC2(receipt(),{expectedControllerCommit:controllerCommit,expectedPolicyDigest:'d'.repeat(64)}),e=>e.code==='C2_POLICY_VERSION_MISMATCH');});
test('C2A-T005 repository numeric identity replacement is rejected',async()=>{await assert.rejects(()=>authorizeC2Initialization({receipt:receipt(),...expected,repositoryReader:async()=>repo({id:99999}),journalClient:client()}),e=>e.code==='C2_REPOSITORY_ID_CHANGED');});
test('C2A-T006 seed head movement after C1 is rejected',async()=>{await assert.rejects(()=>authorizeC2Initialization({receipt:receipt(),...expected,repositoryReader:async()=>repo(),journalClient:client({head:'9'.repeat(40)})}),e=>e.code==='C2_SEED_HEAD_CHANGED');});
test('C2A-T007 journal ref appearing after C1 blocks C2',async()=>{await assert.rejects(()=>authorizeC2Initialization({receipt:receipt(),...expected,repositoryReader:async()=>repo(),journalClient:client({journalExists:true})}),e=>e.code==='LIVE_JOURNAL_REF_ALREADY_EXISTS');});
test('C2A-T008 unsupported receipt schema fails closed',()=>{const r=receipt({schema:'controller://qualification/c1-preflight/v99'});assert.throws(()=>validateC1ReceiptForC2(r,expected),e=>e.code==='C2_C1_RECEIPT_SCHEMA_MISMATCH');});
test('C2A-T009 unknown receipt field fails closed even with recomputed digest',()=>{const r=receipt({surprise:true});assert.throws(()=>validateC1ReceiptForC2(r,expected),e=>e.code==='C2_C1_RECEIPT_UNKNOWN_FIELD');});
test('C2A-T010 non-PASS receipt cannot be promoted into C2 authority',()=>{const r=receipt({result:'FAIL',qualified_for_live_journal_mutation:false});assert.throws(()=>validateC1ReceiptForC2(r,expected),e=>e.code==='C2_C1_RECEIPT_NOT_PASS');});
test('C2A-T011 C2 admission rechecks minimal root seed rather than trusting C1 narrative',async()=>{await assert.rejects(()=>authorizeC2Initialization({receipt:receipt(),...expected,repositoryReader:async()=>repo(),journalClient:client({parents:['8'.repeat(40)]})}),e=>e.code==='LIVE_SEED_HISTORY_NOT_MINIMAL');});
test('C2A-T012 admission object contains no token and no mutation capability',async()=>{const result=await authorizeC2Initialization({receipt:receipt(),...expected,repositoryReader:async()=>repo(),journalClient:client()});assert.deepEqual(Object.keys(result).sort(),['authorized','c1_qualification_id','c1_receipt_digest','controller_commit','journal_repository','journal_repository_id','policy_digest','schema','seed_head','subject_repository'].sort());});
