import test from 'node:test';
import assert from 'node:assert/strict';
import { uuidv7 } from '../src/canonical.js';
import { createOperationPlan, operationPlanDigest, validateOperationPlan, assertPlanMatchesTransaction, schedulerEligibility, OPERATION_PLAN_INVARIANTS } from '../src/operation-plan.js';

const subject={algorithm:'sha1',oid:'a'.repeat(40)};
function input(overrides={}){const base={plan_id:uuidv7(),transaction_id:uuidv7(),operation_id:uuidv7(),operation_type:'repository-change',subject_repository:'BFochtman746/system-master',subject,resource_id:'repo:system-master',allowed_actions:['checkout-subject','create-workspace','analyze','edit-candidate','build','test','collect-evidence','emit-result'],workspace:{kind:'git-worktree',candidate_ref:'refs/heads/controller-candidate/example'},worker_requirements:{capabilities:['git','node']},dispatch:{priority:500,not_before:null,max_attempts:3,lease_ttl_ms:60000,execution_timeout_ms:3600000,retry:{mode:'transient',max_retries:2,base_delay_ms:1000,max_delay_ms:60000,jitter:'full'}}};return {...base,...structuredClone(overrides)};}

test('OP-T001 valid plan is immutable, schema-bound and digested',()=>{const p=createOperationPlan(input());assert.equal(p.schema,'controller://schemas/operation-plan/v1');assert.equal(p.plan_digest,operationPlanDigest(p));assert.equal(Object.isFrozen(p),true);});
test('OP-T002 semantic mutation invalidates digest',()=>{const p=structuredClone(createOperationPlan(input()));p.dispatch.priority+=1;assert.notEqual(p.plan_digest,operationPlanDigest(p));assert.throws(()=>validateOperationPlan(p),e=>e.code==='OPERATION_PLAN_DIGEST_MISMATCH');});
test('OP-T003 unknown fields fail closed',()=>{assert.throws(()=>createOperationPlan(input({surprise:true})),e=>e.code==='OPERATION_PLAN_UNKNOWN_FIELD');});
test('OP-T004 promotion can never be assigned by an operation plan',()=>{assert.throws(()=>createOperationPlan(input({allowed_actions:['promote']})),e=>e.code==='OPERATION_PLAN_AUTHORITY_DENIED');});
test('OP-T005 controller-state mutation can never be assigned by an operation plan',()=>{assert.throws(()=>createOperationPlan(input({allowed_actions:['write-controller-state']})),e=>e.code==='OPERATION_PLAN_AUTHORITY_DENIED');});
test('OP-T006 exact SubjectRef is required',()=>{assert.throws(()=>createOperationPlan(input({subject:{algorithm:'sha1',oid:'A'.repeat(40)}})));});
test('OP-T007 lease TTL may not exceed execution timeout',()=>{const x=input();x.dispatch.lease_ttl_ms=5000;x.dispatch.execution_timeout_ms=4000;assert.throws(()=>createOperationPlan(x),e=>e.code==='OPERATION_PLAN_INVALID');});
test('OP-T008 retry none requires zero retry budget and no jitter',()=>{const x=input();x.dispatch.max_attempts=1;x.dispatch.retry={mode:'none',max_retries:0,base_delay_ms:0,max_delay_ms:0,jitter:'none'};assert.doesNotThrow(()=>createOperationPlan(x));x.dispatch.retry.base_delay_ms=1;assert.throws(()=>createOperationPlan(x),e=>e.code==='OPERATION_PLAN_INVALID');});
test('OP-T009 transient retry count must match total attempt budget',()=>{const x=input();x.dispatch.retry.max_retries=1;assert.throws(()=>createOperationPlan(x),e=>e.code==='OPERATION_PLAN_INVALID');});
test('OP-T010 future not_before makes plan temporarily ineligible',()=>{const p=createOperationPlan(input({dispatch:{...input().dispatch,not_before:'2030-01-01T00:00:00.000Z'}}));assert.deepEqual(schedulerEligibility(p,{nowMs:0,attempts:0,workerCapabilities:['git','node']}),{eligible:false,reason:'NOT_BEFORE'});});
test('OP-T011 attempt budget exhaustion is ineligible',()=>{const p=createOperationPlan(input());assert.deepEqual(schedulerEligibility(p,{attempts:3,workerCapabilities:['git','node']}),{eligible:false,reason:'ATTEMPT_BUDGET_EXHAUSTED'});});
test('OP-T012 missing required worker capability is ineligible',()=>{const p=createOperationPlan(input());assert.deepEqual(schedulerEligibility(p,{attempts:0,workerCapabilities:['git']}),{eligible:false,reason:'WORKER_CAPABILITY_MISMATCH'});});
test('OP-T013 matching worker and policy are eligible',()=>{const p=createOperationPlan(input());assert.deepEqual(schedulerEligibility(p,{attempts:0,workerCapabilities:['node','git','extra']}),{eligible:true,reason:null});});
test('OP-T014 plan binding detects a different transaction',()=>{const p=createOperationPlan(input());assert.throws(()=>assertPlanMatchesTransaction(p,{transactionId:uuidv7(),operationId:p.operation_id,subjectRepository:p.subject_repository,subject:p.subject,resourceId:p.resource_id}),e=>e.code==='OPERATION_PLAN_BINDING_MISMATCH');});
test('OP-T015 plan binding detects a different operation',()=>{const p=createOperationPlan(input());assert.throws(()=>assertPlanMatchesTransaction(p,{transactionId:p.transaction_id,operationId:uuidv7(),subjectRepository:p.subject_repository,subject:p.subject,resourceId:p.resource_id}),e=>e.code==='OPERATION_PLAN_BINDING_MISMATCH');});
test('OP-T016 plan binding detects subject substitution',()=>{const p=createOperationPlan(input());assert.throws(()=>assertPlanMatchesTransaction(p,{transactionId:p.transaction_id,operationId:p.operation_id,subjectRepository:p.subject_repository,subject:{algorithm:'sha1',oid:'b'.repeat(40)},resourceId:p.resource_id}),e=>e.code==='OPERATION_PLAN_BINDING_MISMATCH');});
test('OP-T017 plan binding detects resource substitution',()=>{const p=createOperationPlan(input());assert.throws(()=>assertPlanMatchesTransaction(p,{transactionId:p.transaction_id,operationId:p.operation_id,subjectRepository:p.subject_repository,subject:p.subject,resourceId:'other'}),e=>e.code==='OPERATION_PLAN_BINDING_MISMATCH');});
test('OP-T018 duplicate worker requirements are rejected',()=>{assert.throws(()=>createOperationPlan(input({worker_requirements:{capabilities:['git','git']}})),e=>e.code==='OPERATION_PLAN_INVALID');});
test('OP-T019 dispatch priority is bounded',()=>{const x=input();x.dispatch.priority=1001;assert.throws(()=>createOperationPlan(x),e=>e.code==='OPERATION_PLAN_INVALID');});
test('OP-T020 retry policy lives at scheduler layer and worker authority may only narrow',()=>{assert.equal(OPERATION_PLAN_INVARIANTS.retry_layer,'scheduler');assert.equal(OPERATION_PLAN_INVARIANTS.scheduler_may_only_narrow_authority,true);assert.equal(OPERATION_PLAN_INVARIANTS.worker_cannot_expand_actions,true);});
