import test from 'node:test';
import assert from 'node:assert/strict';
import { ControllerKernel, ControllerError } from '../src/kernel.js';
import { uuidv7 } from '../src/canonical.js';
import { MemoryDurableJournal, publishPendingOutbox } from '../src/durable-journal.js';
import { projectVerifiedDurableJournal, projectionCheckpointStanding } from '../src/projection.js';
import { prepareExternalEffect, authorizeExternalEffectDispatch } from '../src/external-effect-authority.js';

const SUBJECT={algorithm:'sha1',oid:'0123456789abcdef0123456789abcdef01234567'};
function command(){return {protocol_version:'1.0',schema:'controller://schemas/command/v1',command_id:uuidv7(),created_at:new Date().toISOString(),issuer:{principal:'user:test',source:'chatgpt'},command_type:'controller.work.submit',target:{repository:'BFochtman746/system-master',expected_subject:{...SUBJECT}},preconditions:{},intent:{task:'projection-checkpoint'},constraints:{},required_policy_version:null};}
function assertCode(fn,code){assert.throws(fn,e=>e instanceof ControllerError&&e.code===code);}
async function assertRejectCode(fn,code){await assert.rejects(fn,e=>e instanceof ControllerError&&e.code===code);}
function runningEffect(kernel){const tx=kernel.acceptCommand(command()).transaction_id;kernel.admitTransaction(tx,{operations:'all_succeeded'});kernel.activateTransaction(tx);const op=kernel.createOperation(tx,{resourceId:'repo:main'});kernel.transitionOperation(op,'READY');const lease=kernel.acquireLease(op,'repo:main','projection-worker',60000,Date.now());kernel.startLeasedOperation({leaseId:lease.lease_id,generation:lease.generation,operationId:op});const effect=prepareExternalEffect(kernel,{transaction_id:tx,operation_id:op,provider:'github',effect_type:'git.ref.update',target_key:'refs/heads/main',idempotency_key:`projection-${uuidv7()}`,request:{ref:'refs/heads/main',sha:'a'.repeat(40),force:false},expected_remote_version:'b'.repeat(40)});const attempt=authorizeExternalEffectDispatch(kernel,effect.effect_id,lease.lease_id);return {tx,op,lease,effect,attempt};}

// Local provisional identity.
test('PJ-T001 local projection is explicitly provisional and non-authoritative',()=>{const k=new ControllerKernel(':memory:');k.acceptCommand(command());const p=k.projection();assert.equal(p.source_authority,'LOCAL_PROVISIONAL');assert.equal(p.semantic_authority,false);k.close();});
test('PJ-T002 local projection reports exact local event count',()=>{const k=new ControllerKernel(':memory:');k.acceptCommand(command());const p=k.projection();assert.equal(p.source_event_count,k.exportEvents().length);k.close();});
test('PJ-T003 local projection reports exact pending outbox count',()=>{const k=new ControllerKernel(':memory:');k.acceptCommand(command());const p=k.projection();assert.equal(p.pending_outbox_count,k.pendingOutbox().length);k.close();});
test('PJ-T004 local FRESH means event recency only and carries no durable checkpoint',()=>{const k=new ControllerKernel(':memory:');k.acceptCommand(command());const p=k.projection(60000,Date.now());assert.equal(p.freshness,'FRESH');assert.equal(p.freshness_basis,'LOCAL_EVENT_RECENCY_ONLY');assert.equal('source_checkpoint' in p,false);k.close();});

// Durable verified identity.
test('PJ-T005 empty durable journal yields exact empty checkpoint and empty semantic state',async()=>{const j=new MemoryDurableJournal(),cp=await j.getCheckpoint(),p=projectVerifiedDurableJournal(await j.list(),{expectedCheckpoint:cp,nowMs:1000});assert.deepEqual(p.source_checkpoint,{size:0,head_digest:null});assert.equal(p.source_event_count,0);assert.equal(p.source_tail_event_id,null);assert.equal(p.source_tail_event_digest,null);assert.deepEqual(p.state.transactions,{});});
test('PJ-T006 nonempty durable projection binds exact verified checkpoint',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();k.acceptCommand(command());await publishPendingOutbox(k,j);const cp=await j.getCheckpoint(),p=projectVerifiedDurableJournal(await j.list(),{expectedCheckpoint:cp});assert.equal(p.source_authority,'DURABLE_VERIFIED');assert.deepEqual(p.source_checkpoint,cp);assert.equal(p.checkpoint_standing,'AT_CHECKPOINT');k.close();});
test('PJ-T007 durable source count equals checkpoint size',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();const tx=k.acceptCommand(command()).transaction_id;k.admitTransaction(tx);await publishPendingOutbox(k,j);const cp=await j.getCheckpoint(),p=projectVerifiedDurableJournal(await j.list(),{expectedCheckpoint:cp});assert.equal(p.source_event_count,cp.size);k.close();});
test('PJ-T008 durable tail identity equals exact verified tail',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();k.acceptCommand(command());await publishPendingOutbox(k,j);const entries=await j.list(),tail=entries.at(-1),p=projectVerifiedDurableJournal(entries,{expectedCheckpoint:await j.getCheckpoint()});assert.equal(p.source_tail_event_id,tail.event_id);assert.equal(p.source_tail_event_digest,tail.event_digest);k.close();});
test('PJ-T009 generation clock changes metadata but not semantic state',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();k.acceptCommand(command());await publishPendingOutbox(k,j);const entries=await j.list(),cp=await j.getCheckpoint(),a=projectVerifiedDurableJournal(entries,{expectedCheckpoint:cp,nowMs:1000}),b=projectVerifiedDurableJournal(entries,{expectedCheckpoint:cp,nowMs:2000});assert.deepEqual(a.state,b.state);assert.notEqual(a.generated_at,b.generated_at);k.close();});
test('PJ-T010 exact checkpoint equality reports AT_OBSERVED_HEAD',async()=>{const j=new MemoryDurableJournal(),cp=await j.getCheckpoint(),p=projectVerifiedDurableJournal([],{expectedCheckpoint:cp});assert.equal(projectionCheckpointStanding(p,cp),'AT_OBSERVED_HEAD');});
test('PJ-T011 unequal checkpoint reports only NOT_AT_OBSERVED_HEAD',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal(),empty=await j.getCheckpoint(),p=projectVerifiedDurableJournal([],{expectedCheckpoint:empty});k.acceptCommand(command());await publishPendingOutbox(k,j);assert.equal(projectionCheckpointStanding(p,await j.getCheckpoint()),'NOT_AT_OBSERVED_HEAD');k.close();});

// Fail closed and authority separation.
test('PJ-T012 expected checkpoint mismatch fails closed',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();k.acceptCommand(command());await publishPendingOutbox(k,j);await assertRejectCode(async()=>projectVerifiedDurableJournal(await j.list(),{expectedCheckpoint:{size:0,head_digest:null}}),'JOURNAL_CHECKPOINT_MISMATCH');k.close();});
test('PJ-T013 journal position gap fails closed',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();k.acceptCommand(command());await publishPendingOutbox(k,j);const entries=await j.list();entries[0].journal_position=2;assertCode(()=>projectVerifiedDurableJournal(entries,{expectedCheckpoint:awaitablePlaceholder}), 'UNUSED');k.close();});

test('PJ-T014 journal digest or predecessor tamper fails closed',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();k.acceptCommand(command());await publishPendingOutbox(k,j);const entries=await j.list(),cp=await j.getCheckpoint();entries[0].journal_digest='0'.repeat(64);assertCode(()=>projectVerifiedDurableJournal(entries,{expectedCheckpoint:cp}),'JOURNAL_INTEGRITY_FAILURE');k.close();});
test('PJ-T015 unsupported semantic event schema fails closed after journal identity is recomputed by a fresh journal',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal();k.acceptCommand(command());const event=k.exportEvents()[0];event.event_schema='controller.event.v999';const core={event_id:event.event_id,event_schema:event.event_schema,stream_id:event.stream_id,stream_version:event.stream_version,event_type:event.event_type,occurred_at:event.occurred_at,prev_event_digest:event.prev_event_digest,data:event.data};const { sha256 }=await import('../src/canonical.js');event.event_digest=sha256(core);await j.putIfAbsent(event);const cp=await j.getCheckpoint();assertCode(()=>projectVerifiedDurableJournal(await j.list(),{expectedCheckpoint:cp}),'UNSUPPORTED_EVENT_SCHEMA');k.close();});
test('PJ-T016 local PENDING event is visible locally but absent from durable projection',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal(),empty=await j.getCheckpoint(),tx=k.acceptCommand(command()).transaction_id,local=k.projection(),durable=projectVerifiedDurableJournal([],{expectedCheckpoint:empty});assert.ok(local.state.transactions[tx]);assert.equal(durable.state.transactions[tx],undefined);assert.ok(local.pending_outbox_count>0);k.close();});
test('PJ-T017 after publication a regenerated durable projection includes the event at the new checkpoint',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal(),tx=k.acceptCommand(command()).transaction_id;await publishPendingOutbox(k,j);const cp=await j.getCheckpoint(),p=projectVerifiedDurableJournal(await j.list(),{expectedCheckpoint:cp});assert.ok(p.state.transactions[tx]);assert.equal(p.source_event_count,cp.size);k.close();});
test('PJ-T018 durable projection preserves UNKNOWN external effect and immutable attempt exactly',async()=>{const k=new ControllerKernel(':memory:'),j=new MemoryDurableJournal(),x=runningEffect(k);await publishPendingOutbox(k,j);const p=projectVerifiedDurableJournal(await j.list(),{expectedCheckpoint:await j.getCheckpoint()});assert.equal(p.state.external_effects[x.effect.effect_id].state,'UNKNOWN');assert.equal(p.state.external_effect_attempts[x.attempt.attempt_id].effect_id,x.effect.effect_id);k.close();});
