package org.systemmaster.tools.ocr;

import java.util.*;

/** Frozen Tool Vault full-lane disposition ledger for MOD-OCR-001. */
public final class OcrFullLaneCapabilities {
 public record Disposition(String capabilityId,String domain,String capability,String disposition) {}
 private static final List<Disposition> ALL=build();
 private OcrFullLaneCapabilities(){}
 public static List<Disposition> all(){return ALL;}
 public static long portable(){return ALL.stream().filter(d->d.disposition().startsWith("PORTABLE_")).count();}
 public static long delegated(){return ALL.stream().filter(d->d.disposition().startsWith("DELEGATED_")).count();}
 public static long pending(){return ALL.stream().filter(d->d.disposition().contains("PENDING")||d.disposition().contains("REQUIRED")).count();}
 private static List<Disposition> build(){ArrayList<Disposition> out=new ArrayList<>();
  out.add(new Disposition("OCR-CAP-001","SOURCE_CAPTURE","immutable source image","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-002","SOURCE_CAPTURE","PDF page-render input binding","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-003","SOURCE_CAPTURE","native-text bypass decision","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-004","SOURCE_CAPTURE","page identity","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-005","SOURCE_CAPTURE","capture artifact identity","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-006","SOURCE_CAPTURE","page/crop source selector","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-007","SOURCE_CAPTURE","image orientation inventory","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-008","SOURCE_CAPTURE","DPI/pixel-density inventory","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-009","SOURCE_CAPTURE","color profile inventory","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-010","SOURCE_CAPTURE","EXIF/capture metadata inventory","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-011","SOURCE_CAPTURE","multi-page source sequencing","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-012","SOURCE_CAPTURE","source-format security classification","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-013","SOURCE_CAPTURE","source hash verification","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-014","PREPROCESSING","rotation correction","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-015","PREPROCESSING","deskew","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-016","PREPROCESSING","perspective correction","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-017","PREPROCESSING","dewarp","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-018","PREPROCESSING","binarization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-019","PREPROCESSING","adaptive thresholding","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-020","PREPROCESSING","denoise","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-021","PREPROCESSING","despeckle","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-022","PREPROCESSING","background normalization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-023","PREPROCESSING","contrast/exposure normalization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-024","PREPROCESSING","border removal","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-025","PREPROCESSING","crop/ROI","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-026","PREPROCESSING","alpha handling","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-027","PREPROCESSING","scale/resample","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-028","PREPROCESSING","screen-photo normalization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-029","PREPROCESSING","preprocessing ensemble","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-030","PREPROCESSING","preprocessing transformation ledger","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-031","RECOGNITION","printed text recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-032","RECOGNITION","handwriting recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-033","RECOGNITION","multilingual recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-034","RECOGNITION","script detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-035","RECOGNITION","language detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-036","RECOGNITION","rare-character recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-037","RECOGNITION","ancient/degraded text recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-038","RECOGNITION","scene/industrial text recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-039","RECOGNITION","text spotting","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-040","RECOGNITION","alternative candidate generation","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-041","RECOGNITION","word recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-042","RECOGNITION","line recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-043","RECOGNITION","single-character recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-044","RECOGNITION","model/language mismatch detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-045","RECOGNITION","unsupported-language abstention","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-046","LAYOUT_STRUCTURE","region detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-047","LAYOUT_STRUCTURE","polygon localization","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-048","LAYOUT_STRUCTURE","line geometry","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-049","LAYOUT_STRUCTURE","word geometry","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-050","LAYOUT_STRUCTURE","glyph geometry optional","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-051","LAYOUT_STRUCTURE","paragraph grouping","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-052","LAYOUT_STRUCTURE","reading order","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-053","LAYOUT_STRUCTURE","title/heading role","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-054","LAYOUT_STRUCTURE","header/footer role","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-055","LAYOUT_STRUCTURE","list structure","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-056","LAYOUT_STRUCTURE","multi-column structure","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-057","LAYOUT_STRUCTURE","figure region","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-058","LAYOUT_STRUCTURE","caption relation","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-059","LAYOUT_STRUCTURE","page-number role","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-060","LAYOUT_STRUCTURE","hierarchical section structure","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-061","LAYOUT_STRUCTURE","cross-page continuation","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-062","LAYOUT_STRUCTURE","layout confidence","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-063","SPECIAL_ELEMENTS","table detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-064","SPECIAL_ELEMENTS","table row/column reconstruction","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-065","SPECIAL_ELEMENTS","merged-cell structure","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-066","SPECIAL_ELEMENTS","cross-page tables","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-067","SPECIAL_ELEMENTS","table header/footer","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-068","SPECIAL_ELEMENTS","formula detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-069","SPECIAL_ELEMENTS","formula recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-070","SPECIAL_ELEMENTS","chart detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-071","SPECIAL_ELEMENTS","chart description","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-072","SPECIAL_ELEMENTS","chart exact-value extraction","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-073","SPECIAL_ELEMENTS","seal/stamp detection","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-074","SPECIAL_ELEMENTS","seal/stamp text recognition","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-075","SPECIAL_ELEMENTS","signature location","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-076","SPECIAL_ELEMENTS","checkbox/selection state","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-077","SPECIAL_ELEMENTS","form key-value extraction","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-078","SPECIAL_ELEMENTS","barcode decode handoff","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-079","SPECIAL_ELEMENTS","image/figure annotation","PORTABLE_ORCHESTRATION_QUALIFIED_ENGINE_REQUIRED"));
  out.add(new Disposition("OCR-CAP-080","EVIDENCE_PROVENANCE","engine identity","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-081","EVIDENCE_PROVENANCE","model artifact identity","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-082","EVIDENCE_PROVENANCE","provider processorVersion identity","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-083","EVIDENCE_PROVENANCE","configuration identity","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-084","EVIDENCE_PROVENANCE","preprocessing lineage","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-085","EVIDENCE_PROVENANCE","source-region binding","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-086","EVIDENCE_PROVENANCE","text alternative lineage","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-087","EVIDENCE_PROVENANCE","geometry lineage","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-088","EVIDENCE_PROVENANCE","reading-order lineage","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-089","EVIDENCE_PROVENANCE","provider raw-response preservation","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-090","EVIDENCE_PROVENANCE","correction lineage","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-091","EVIDENCE_PROVENANCE","disagreement record","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-092","EVIDENCE_PROVENANCE","semantic-extraction lineage","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-093","EVIDENCE_PROVENANCE","derivative-publication lineage","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-094","EVIDENCE_PROVENANCE","model-alias resolution receipt","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-095","EVIDENCE_PROVENANCE","evidence hash/seal","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-096","CONFIDENCE_REVIEW","raw provider confidence preservation","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-097","CONFIDENCE_REVIEW","confidence-unit typing","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-098","CONFIDENCE_REVIEW","confidence-scale typing","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-099","CONFIDENCE_REVIEW","content confidence","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-100","CONFIDENCE_REVIEW","geometry confidence","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-101","CONFIDENCE_REVIEW","structure-type confidence","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-102","CONFIDENCE_REVIEW","perception confidence","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-103","CONFIDENCE_REVIEW","reasoning/semantic confidence","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-104","CONFIDENCE_REVIEW","held-out calibration","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-105","CONFIDENCE_REVIEW","risk/coverage policy","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-106","CONFIDENCE_REVIEW","abstention","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-107","CONFIDENCE_REVIEW","human review routing","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-108","CONFIDENCE_REVIEW","high-risk-field override","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-109","CONFIDENCE_REVIEW","review receipt","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-110","CONFIDENCE_REVIEW","calibration drift detection","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-111","ROUTING_ORACLES","native-text primary route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-112","ROUTING_ORACLES","local conventional OCR route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-113","ROUTING_ORACLES","local structured VLM route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-114","ROUTING_ORACLES","cloud GA route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-115","ROUTING_ORACLES","cloud preview experiment route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-116","ROUTING_ORACLES","residency-compatible route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-117","ROUTING_ORACLES","offline-only route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-118","ROUTING_ORACLES","ensemble route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-119","ROUTING_ORACLES","differential route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-120","ROUTING_ORACLES","human-review route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-121","ROUTING_ORACLES","searchable-PDF derivative route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-122","ROUTING_ORACLES","mobile assist route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-123","ROUTING_ORACLES","oracle selection","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-124","ROUTING_ORACLES","fail-closed unsupported route","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-125","ROUTING_ORACLES","fallback fidelity enforcement","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-126","SECURITY_PRIVACY","document prompt-injection containment","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-127","SECURITY_PRIVACY","no source-granted tool authority","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-128","SECURITY_PRIVACY","network egress policy","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-129","SECURITY_PRIVACY","secret isolation","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-130","SECURITY_PRIVACY","provider region binding","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-131","SECURITY_PRIVACY","provider retention binding","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-132","SECURITY_PRIVACY","early deletion receipt","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-133","SECURITY_PRIVACY","model/traineddata supply-chain verification","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-134","SECURITY_PRIVACY","plugin/code-data separation","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-135","SECURITY_PRIVACY","malformed image containment","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-136","SECURITY_PRIVACY","resource limit enforcement","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-137","SECURITY_PRIVACY","timeout/cancellation","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-138","SECURITY_PRIVACY","cloud free-form secret minimization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-139","SECURITY_PRIVACY","audit logging","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-140","SECURITY_PRIVACY","privacy classification","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-141","SECURITY_PRIVACY","data minimization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-142","OUTPUT_INTEROP","canonical OCR graph","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-143","OUTPUT_INTEROP","PAGE XML import","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-144","OUTPUT_INTEROP","PAGE XML export","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-145","OUTPUT_INTEROP","ALTO import","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-146","OUTPUT_INTEROP","ALTO export","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-147","OUTPUT_INTEROP","hOCR import","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-148","OUTPUT_INTEROP","TSV import","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-149","OUTPUT_INTEROP","provider JSON normalization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-150","OUTPUT_INTEROP","coordinate-system normalization","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-151","OUTPUT_INTEROP","loss ledger","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-152","OUTPUT_INTEROP","round-trip fidelity classification","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-153","OUTPUT_INTEROP","searchable PDF publication","PORTABLE_IMPLEMENTED"));
  out.add(new Disposition("OCR-CAP-154","BENCHMARK_QUALIFICATION","CER","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-155","BENCHMARK_QUALIFICATION","WER","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-156","BENCHMARK_QUALIFICATION","exact critical-field metric","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-157","BENCHMARK_QUALIFICATION","detection precision/recall","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-158","BENCHMARK_QUALIFICATION","geometry IoU","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-159","BENCHMARK_QUALIFICATION","reading-order metric","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-160","BENCHMARK_QUALIFICATION","table structural metric","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-161","BENCHMARK_QUALIFICATION","table cell exact/numeric validation","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-162","BENCHMARK_QUALIFICATION","formula CDM/canonical metric","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-163","BENCHMARK_QUALIFICATION","chart-value validation","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-164","BENCHMARK_QUALIFICATION","handwriting strata","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-165","BENCHMARK_QUALIFICATION","multilingual/script strata","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-166","BENCHMARK_QUALIFICATION","mobile/photo robustness strata","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-167","BENCHMARK_QUALIFICATION","confidence ECE/Brier/NLL","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-168","BENCHMARK_QUALIFICATION","selective risk/AURC","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-169","BENCHMARK_QUALIFICATION","human-review workload","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-170","BENCHMARK_QUALIFICATION","latency/throughput","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-171","BENCHMARK_QUALIFICATION","RAM/VRAM","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-172","BENCHMARK_QUALIFICATION","restart/recovery","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-173","BENCHMARK_QUALIFICATION","security mutation","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-174","BENCHMARK_QUALIFICATION","provider drift canary","PORTABLE_QUALIFICATION_ORCHESTRATION"));
  out.add(new Disposition("OCR-CAP-175","MOBILE_EDGE","Apple Vision text route","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-176","MOBILE_EDGE","Apple Vision document route","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-177","MOBILE_EDGE","request revision binding","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-178","MOBILE_EDGE","recognition level binding","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-179","MOBILE_EDGE","language configuration binding","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-180","MOBILE_EDGE","live-scan observation","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-181","MOBILE_EDGE","high-resolution capture artifact","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-182","MOBILE_EDGE","live-vs-capture separation","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-183","MOBILE_EDGE","capture quality scoring","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-184","MOBILE_EDGE","camera/capture provenance","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-185","MOBILE_EDGE","HEIF/JPEG conversion ledger","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-186","MOBILE_EDGE","orientation transform ledger","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-187","MOBILE_EDGE","mobile/offline operation","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-188","MOBILE_EDGE","mobile-server disagreement","DELEGATED_MOBILE_NATIVE_PENDING"));
  out.add(new Disposition("OCR-CAP-189","MOBILE_EDGE","physical-device qualification","DELEGATED_MOBILE_NATIVE_PENDING"));
  return List.copyOf(out);
 }
}
