package org.systemmaster.tools.ocr;
import javax.imageio.ImageIO;import java.awt.*;import java.awt.image.*;import java.io.*;import java.security.*;import java.util.List;import java.util.*;
/** Portable source/preprocess/normalize/confidence/correction/differential authority around replaceable OCR engines. */
public final class OcrFullLaneEngine {
 public record Source(String sha256,int width,int height,String format,boolean imageReadable){}
 public record CanonicalRegion(String id,String text,double x,double y,double width,double height,double rawConfidence,String confidenceState,String type,String engineId,String engineVersion){}
 public record PageGraph(String sourceSha256,List<CanonicalRegion> regions,List<String> readingOrder,Map<String,String> facts,List<String> diagnostics) {public PageGraph{regions=List.copyOf(regions);readingOrder=List.copyOf(readingOrder);facts=Map.copyOf(facts);diagnostics=List.copyOf(diagnostics);}}
 public Source inspect(byte[] image)throws IOException{BufferedImage b=ImageIO.read(new ByteArrayInputStream(image));if(b==null)return new Source(sha(image),0,0,"UNKNOWN",false);return new Source(sha(image),b.getWidth(),b.getHeight(),"RASTER",true);}
 public byte[] grayscaleThreshold(byte[] image,int threshold)throws IOException{if(threshold<0||threshold>255)throw new IllegalArgumentException("threshold");BufferedImage in=ImageIO.read(new ByteArrayInputStream(image));if(in==null)throw new IOException("unsupported image");BufferedImage out=new BufferedImage(in.getWidth(),in.getHeight(),BufferedImage.TYPE_BYTE_BINARY);for(int y=0;y<in.getHeight();y++)for(int x=0;x<in.getWidth();x++){Color c=new Color(in.getRGB(x,y),true);int g=(299*c.getRed()+587*c.getGreen()+114*c.getBlue())/1000;out.setRGB(x,y,g>=threshold?Color.WHITE.getRGB():Color.BLACK.getRGB());}ByteArrayOutputStream baos=new ByteArrayOutputStream();ImageIO.write(out,"png",baos);return baos.toByteArray();}
 public byte[] rotate90(byte[] image)throws IOException{BufferedImage in=ImageIO.read(new ByteArrayInputStream(image));if(in==null)throw new IOException("unsupported image");BufferedImage out=new BufferedImage(in.getHeight(),in.getWidth(),BufferedImage.TYPE_INT_ARGB);Graphics2D g=out.createGraphics();g.translate(out.getWidth(),0);g.rotate(Math.PI/2);g.drawImage(in,0,0,null);g.dispose();ByteArrayOutputStream baos=new ByteArrayOutputStream();ImageIO.write(out,"png",baos);return baos.toByteArray();}
 public PageGraph normalize(byte[] source,OcrEnginePort.Identity id,OcrEnginePort.Result result){ArrayList<CanonicalRegion> regs=new ArrayList<>();for(var r:result.regions()){String state=r.confidence()>=.95?"HIGH":r.confidence()>=.75?"MEDIUM":r.confidence()>=0?"LOW":"UNASSESSED";regs.add(new CanonicalRegion(r.id(),r.text(),r.x(),r.y(),r.width(),r.height(),r.confidence(),state,r.type(),id.engineId(),id.version()));}regs.sort(Comparator.comparingDouble(CanonicalRegion::y).thenComparingDouble(CanonicalRegion::x));return new PageGraph(sha(source),regs,regs.stream().map(CanonicalRegion::id).toList(),result.facts(),result.diagnostics());}
 public PageGraph correct(PageGraph graph,String regionId,String correctedText,String reviewer){ArrayList<CanonicalRegion> out=new ArrayList<>(graph.regions());for(int i=0;i<out.size();i++){var r=out.get(i);if(r.id().equals(regionId))out.set(i,new CanonicalRegion(r.id(),correctedText,r.x(),r.y(),r.width(),r.height(),r.rawConfidence(),"HUMAN_CORRECTED",r.type(),r.engineId(),r.engineVersion()));}Map<String,String> facts=new LinkedHashMap<>(graph.facts());facts.put("lastReviewer",Objects.requireNonNullElse(reviewer,"UNKNOWN"));return new PageGraph(graph.sourceSha256(),out,graph.readingOrder(),facts,graph.diagnostics());}
 public List<String> differential(PageGraph a,PageGraph b){ArrayList<String>d=new ArrayList<>();if(!a.sourceSha256().equals(b.sourceSha256()))d.add("SOURCE_MISMATCH");int n=Math.max(a.regions().size(),b.regions().size());for(int i=0;i<n;i++){if(i>=a.regions().size()||i>=b.regions().size())d.add("REGION_COUNT_MISMATCH");else if(!Objects.equals(a.regions().get(i).text(),b.regions().get(i).text()))d.add("TEXT_MISMATCH:"+i);}return List.copyOf(d);}
 private static String sha(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
