package org.systemmaster.tools.ocr;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.Duration;import java.util.*;import java.util.concurrent.TimeUnit;
/** Bounded argv-only Tesseract adapter. Raw engine confidence remains observation evidence only. */
public final class TesseractOcrEnginePort implements OcrEnginePort {
 private final Path executable;private final Duration timeout;private final String language;
 public TesseractOcrEnginePort(Path executable,Duration timeout,String language){this.executable=real(executable);this.timeout=Objects.requireNonNull(timeout);this.language=language==null||language.isBlank()?"eng":language;}
 public Identity identity(){String v;try{v=run(List.of(executable.toString(),"--version")).lines().findFirst().orElse("UNKNOWN");}catch(Exception e){v="UNKNOWN";}return new Identity("TESSERACT",v,Integer.toHexString(executable.toString().hashCode()),Set.of("ocr.run.recognize"),true,false);}
 public Result recognize(byte[] image,String action,Map<String,String> options)throws Exception{if(!action.equals("ocr.run.recognize"))throw new IllegalArgumentException("unsupported Tesseract action");Path dir=Files.createTempDirectory("systemmaster-ocr-");try{Path in=dir.resolve("input.png");Files.write(in,image);String tsv=run(List.of(executable.toString(),in.toString(),"stdout","-l",options.getOrDefault("language",language),"tsv"));ArrayList<Region> regions=new ArrayList<>();String[] lines=tsv.split("\\R");for(int i=1;i<lines.length;i++){String[] c=lines[i].split("\\t",12);if(c.length<12||c[11].isBlank())continue;double conf=parse(c[10])/100.0;if(conf<0)conf=-1;regions.add(new Region("w"+regions.size(),c[11],parse(c[6]),parse(c[7]),parse(c[8]),parse(c[9]),conf,"WORD",Map.of("level",c[0],"page",c[1],"block",c[2],"paragraph",c[3],"line",c[4])));}return new Result(regions,Map.of("language",options.getOrDefault("language",language)),List.of());}finally{deleteTree(dir);}}
 private String run(List<String> argv)throws Exception{Process p=new ProcessBuilder(argv).redirectErrorStream(true).start();ByteArrayOutputStream out=new ByteArrayOutputStream();Thread reader=Thread.ofVirtual().start(()->{try{p.getInputStream().transferTo(out);}catch(IOException ignored){}});boolean done=p.waitFor(timeout.toMillis(),TimeUnit.MILLISECONDS);if(!done){p.destroyForcibly();throw new IOException("OCR engine timeout");}reader.join();if(out.size()>64*1024*1024)throw new IOException("OCR output ceiling exceeded");if(p.exitValue()!=0)throw new IOException("OCR engine failed exit="+p.exitValue()+" output="+out.toString(StandardCharsets.UTF_8).substring(0,Math.min(2048,out.size())));return out.toString(StandardCharsets.UTF_8);}
 private static double parse(String s){try{return Double.parseDouble(s);}catch(NumberFormatException e){return 0;}}
 private static Path real(Path p){Objects.requireNonNull(p);if(!Files.isRegularFile(p)||!Files.isExecutable(p))throw new IllegalArgumentException("executable unavailable: "+p);return p.toAbsolutePath().normalize();}
 private static void deleteTree(Path root){if(root==null)return;try(var s=Files.walk(root)){s.sorted(Comparator.reverseOrder()).forEach(x->{try{Files.deleteIfExists(x);}catch(IOException ignored){}});}catch(IOException ignored){}}
}
