import { DatabaseSync } from 'node:sqlite';
import { canonicalize, sha256, uuidv7, isUuidV7, isSha1, isRfc3339 } from './canonical.js';

export class ControllerError extends Error {
  constructor(code, message, details = {}) { super(message); this.name = 'ControllerError'; this.code = code; this.details = details; }
}

const OP_STATES = new Set(['PLANNED','READY','RUNNING','VERIFYING','SUCCEEDED','FAILED','BLOCKED','CANCELLED','STALE']);
const OP_TRANSITIONS = new Map([
  ['PLANNED', new Set(['READY','CANCELLED','STALE'])],
  ['READY', new Set(['RUNNING','BLOCKED','CANCELLED','STALE'])],
  ['RUNNING', new Set(['VERIFYING','SUCCEEDED','FAILED','BLOCKED','CANCELLED','STALE'])],
  ['VERIFYING', new Set(['SUCCEEDED','FAILED','BLOCKED','STALE'])],
  ['BLOCKED', new Set(['READY','CANCELLED','STALE'])]
]);
const TERMINAL_OP = new Set(['SUCCEEDED','FAILED','CANCELLED','STALE']);
const EVENT_SCHEMA = 'controller.event.v1';

function strictKeys(obj, allowed, required = allowed) {
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) throw new ControllerError('SCHEMA_INVALID', 'object required');
  for (const k of Object.keys(obj)) if (!allowed.includes(k)) throw new ControllerError('SCHEMA_UNKNOWN_FIELD', `unknown field ${k}`);
  for (const k of required) if (!(k in obj)) throw new ControllerError('SCHEMA_MISSING_FIELD', `missing field ${k}`);
}

export function validateCommand(c) {
  const allowed = ['protocol_version','schema','command_id','created_at','issuer','command_type','target','preconditions','intent','constraints','required_policy_version','fingerprint'];
  const required = ['protocol_version','schema','command_id','created_at','issuer','command_type','target','preconditions','intent','constraints','required_policy_version'];
  strictKeys(c, allowed, required);
  if (c.protocol_version !== '1.0') throw new ControllerError('UNSUPPORTED_PROTOCOL','protocol_version must be 1.0');
  if (c.schema !== 'controller://schemas/command/v1') throw new ControllerError('UNSUPPORTED_SCHEMA','unsupported command schema');
  if (!isUuidV7(c.command_id)) throw new ControllerError('SCHEMA_INVALID','command_id must be UUIDv7');
  if (!isRfc3339(c.created_at)) throw new ControllerError('SCHEMA_INVALID','created_at must be RFC3339 UTC');
  strictKeys(c.issuer, ['principal','source']);
  strictKeys(c.target, ['repository','expected_subject_sha']);
  if (!isSha1(c.target.expected_subject_sha)) throw new ControllerError('SCHEMA_INVALID','expected_subject_sha must be 40 hex chars');
  return true;
}

export function commandFingerprint(c) { const x = structuredClone(c); delete x.fingerprint; return sha256(x); }

export class ControllerKernel {
  constructor(path = ':memory:', options = {}) {
    this.db = new DatabaseSync(path, { timeout: options.timeout ?? 5000 });
    this.db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL;');
    this.migrate();
  }
  close() { this.db.close(); }
  migrate() {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS commands(command_id TEXT PRIMARY KEY, fingerprint TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS transactions(transaction_id TEXT PRIMARY KEY, command_id TEXT NOT NULL UNIQUE REFERENCES commands(command_id), state TEXT NOT NULL CHECK(state IN ('OPEN','ADMITTED','ACTIVE','WAITING','SUCCEEDED','REJECTED','FAILED','CANCELLED','SUPERSEDED')), controller_version TEXT NOT NULL, policy_version TEXT NOT NULL, subject_repo TEXT NOT NULL, subject_sha TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS operations(operation_id TEXT PRIMARY KEY, transaction_id TEXT NOT NULL REFERENCES transactions(transaction_id), state TEXT NOT NULL CHECK(state IN ('PLANNED','READY','RUNNING','VERIFYING','SUCCEEDED','FAILED','BLOCKED','CANCELLED','STALE')), resource_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS resource_generations(resource_id TEXT PRIMARY KEY, generation INTEGER NOT NULL CHECK(generation >= 0));
      CREATE TABLE IF NOT EXISTS leases(lease_id TEXT PRIMARY KEY, operation_id TEXT NOT NULL REFERENCES operations(operation_id), resource_id TEXT NOT NULL, worker_id TEXT NOT NULL, generation INTEGER NOT NULL CHECK(generation > 0), status TEXT NOT NULL CHECK(status IN ('ACTIVE','RELEASED','EXPIRED','REVOKED')), issued_at TEXT NOT NULL, expires_at TEXT NOT NULL, last_heartbeat_at TEXT NOT NULL);
      CREATE UNIQUE INDEX IF NOT EXISTS one_active_lease_per_resource ON leases(resource_id) WHERE status='ACTIVE';
      CREATE TABLE IF NOT EXISTS events(event_id TEXT PRIMARY KEY, event_schema TEXT NOT NULL, stream_id TEXT NOT NULL, stream_version INTEGER NOT NULL CHECK(stream_version > 0), event_type TEXT NOT NULL, occurred_at TEXT NOT NULL, data_json TEXT NOT NULL, prev_event_digest TEXT, event_digest TEXT NOT NULL, UNIQUE(stream_id, stream_version));
      CREATE TABLE IF NOT EXISTS outbox(outbox_id TEXT PRIMARY KEY, event_id TEXT NOT NULL UNIQUE REFERENCES events(event_id), status TEXT NOT NULL CHECK(status IN ('PENDING','SEALED')), attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT, created_at TEXT NOT NULL, sealed_at TEXT);
      CREATE TABLE IF NOT EXISTS qualifications(qualification_id TEXT PRIMARY KEY, transaction_id TEXT NOT NULL REFERENCES transactions(transaction_id), subject_sha TEXT NOT NULL, policy_version TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('REQUESTED','RUNNING','PASSED','FAILED','INDETERMINATE','CANCELLED')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS promotions(promotion_id TEXT PRIMARY KEY, transaction_id TEXT NOT NULL REFERENCES transactions(transaction_id), subject_sha TEXT NOT NULL, qualification_id TEXT NOT NULL REFERENCES qualifications(qualification_id), state TEXT NOT NULL CHECK(state IN ('REQUESTED','AUTHORIZED','EXECUTING','SUCCEEDED','FAILED','CANCELLED','RECONCILIATION_REQUIRED')), authorization_event_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      INSERT OR IGNORE INTO schema_migrations(version, applied_at) VALUES (1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
    `);
  }
  atomic(fn) {
    this.db.exec('BEGIN IMMEDIATE');
    try { const r = fn(); this.db.exec('COMMIT'); return r; }
    catch (e) { if (this.db.isTransaction) this.db.exec('ROLLBACK'); throw e; }
  }
  currentStreamVersion(streamId) { return Number(this.db.prepare('SELECT COALESCE(MAX(stream_version),0) v FROM events WHERE stream_id=?').get(streamId).v); }
  appendEvent(streamId, expectedVersion, eventType, data, occurredAt = new Date().toISOString(), eventSchema = EVENT_SCHEMA) {
    if (eventSchema !== EVENT_SCHEMA) throw new ControllerError('UNSUPPORTED_EVENT_SCHEMA', `unsupported event schema ${eventSchema}`);
    const row = this.db.prepare('SELECT stream_version,event_digest FROM events WHERE stream_id=? ORDER BY stream_version DESC LIMIT 1').get(streamId);
    const current = row ? Number(row.stream_version) : 0;
    if (current !== expectedVersion) throw new ControllerError('CONCURRENCY_CONFLICT', `expected stream version ${expectedVersion}, got ${current}`);
    const version = current + 1, eventId = uuidv7(), prev = row?.event_digest ?? null;
    const core = { event_id:eventId, event_schema:eventSchema, stream_id:streamId, stream_version:version, event_type:eventType, occurred_at:occurredAt, prev_event_digest:prev, data };
    const digest = sha256(core);
    this.db.prepare('INSERT INTO events VALUES (?,?,?,?,?,?,?,?,?)').run(eventId,eventSchema,streamId,version,eventType,occurredAt,canonicalize(data),prev,digest);
    const outboxId=uuidv7(); this.db.prepare("INSERT INTO outbox(outbox_id,event_id,status,created_at) VALUES (?,?,'PENDING',?)").run(outboxId,eventId,occurredAt);
    return {...core,event_digest:digest,outbox_id:outboxId};
  }
  acceptCommand(command,{controllerVersion='dev',policyVersion='dev'}={}) {
    validateCommand(command); const fp=commandFingerprint(command);
    if(command.fingerprint&&command.fingerprint!==fp) throw new ControllerError('FINGERPRINT_MISMATCH','command fingerprint mismatch');
    return this.atomic(()=>{
      const prior=this.db.prepare('SELECT fingerprint FROM commands WHERE command_id=?').get(command.command_id);
      if(prior){ if(prior.fingerprint!==fp) throw new ControllerError('IDEMPOTENCY_CONFLICT','command id reused with different semantic contents'); const tx=this.db.prepare('SELECT transaction_id FROM transactions WHERE command_id=?').get(command.command_id); return {duplicate:true,transaction_id:tx.transaction_id,fingerprint:fp}; }
      this.db.prepare('INSERT INTO commands VALUES (?,?,?,?)').run(command.command_id,fp,canonicalize({...command,fingerprint:fp}),command.created_at);
      const txId=uuidv7(),now=new Date().toISOString();
      this.db.prepare('INSERT INTO transactions VALUES (?,?,?,?,?,?,?,?,?)').run(txId,command.command_id,'OPEN',controllerVersion,policyVersion,command.target.repository,command.target.expected_subject_sha,now,now);
      this.appendEvent(`transaction:${txId}`,0,'command.accepted',{transaction_id:txId,command_id:command.command_id,fingerprint:fp,command:{...command,fingerprint:fp},controller_version:controllerVersion,policy_version:policyVersion},now);
      return {duplicate:false,transaction_id:txId,fingerprint:fp};
    });
  }
  createOperation(transactionId,{resourceId=null}={}) { return this.atomic(()=>{const now=new Date().toISOString(),id=uuidv7(); this.db.prepare('INSERT INTO operations VALUES (?,?,?,?,?,?)').run(id,transactionId,'PLANNED',resourceId,now,now); this.appendEvent(`operation:${id}`,0,'operation.planned',{operation_id:id,transaction_id:transactionId,resource_id:resourceId},now); return id;}); }
  transitionOperation(operationId,to,expectedFrom=null) {
    if(!OP_STATES.has(to)) throw new ControllerError('INVALID_STATE','unknown operation state');
    return this.atomic(()=>{const op=this.db.prepare('SELECT * FROM operations WHERE operation_id=?').get(operationId); if(!op) throw new ControllerError('NOT_FOUND','operation not found'); if(expectedFrom&&op.state!==expectedFrom) throw new ControllerError('STATE_CONFLICT',`expected ${expectedFrom}, got ${op.state}`); if(TERMINAL_OP.has(op.state)) throw new ControllerError('ILLEGAL_TRANSITION','terminal operation cannot transition'); const allowed=OP_TRANSITIONS.get(op.state)??new Set(); if(!allowed.has(to)) throw new ControllerError('ILLEGAL_TRANSITION',`${op.state} -> ${to} not allowed`); const now=new Date().toISOString(); this.db.prepare('UPDATE operations SET state=?,updated_at=? WHERE operation_id=?').run(to,now,operationId); this.appendEvent(`operation:${operationId}`,this.currentStreamVersion(`operation:${operationId}`),`operation.${to.toLowerCase()}`,{operation_id:operationId,transaction_id:op.transaction_id,from:op.state,to},now); return to;});
  }
  acquireLease(operationId,resourceId,workerId,ttlMs=60000,nowMs=Date.now()) {
    return this.atomic(()=>{const op=this.db.prepare('SELECT * FROM operations WHERE operation_id=?').get(operationId); if(!op) throw new ControllerError('NOT_FOUND','operation not found'); const active=this.db.prepare("SELECT * FROM leases WHERE resource_id=? AND status='ACTIVE'").get(resourceId); if(active){if(Date.parse(active.expires_at)>nowMs) throw new ControllerError('LEASE_CONFLICT','resource already leased'); this.db.prepare("UPDATE leases SET status='EXPIRED' WHERE lease_id=?").run(active.lease_id);} const g=this.db.prepare('SELECT generation FROM resource_generations WHERE resource_id=?').get(resourceId),generation=(g?Number(g.generation):0)+1; this.db.prepare('INSERT INTO resource_generations(resource_id,generation) VALUES (?,?) ON CONFLICT(resource_id) DO UPDATE SET generation=excluded.generation').run(resourceId,generation); const leaseId=uuidv7(nowMs),issued=new Date(nowMs).toISOString(),expires=new Date(nowMs+ttlMs).toISOString(); this.db.prepare("INSERT INTO leases VALUES (?,?,?,?,?,'ACTIVE',?,?,?)").run(leaseId,operationId,resourceId,workerId,generation,issued,expires,issued); this.appendEvent(`operation:${operationId}`,this.currentStreamVersion(`operation:${operationId}`),'lease.granted',{lease_id:leaseId,operation_id:operationId,resource_id:resourceId,worker_id:workerId,generation,expires_at:expires},issued); return {lease_id:leaseId,generation,expires_at:expires};});
  }
  heartbeatLease(leaseId,generation,nowMs=Date.now()) { return this.atomic(()=>{const l=this.db.prepare('SELECT * FROM leases WHERE lease_id=?').get(leaseId); if(!l) throw new ControllerError('NOT_FOUND','lease not found'); const rg=this.db.prepare('SELECT generation FROM resource_generations WHERE resource_id=?').get(l.resource_id); if(l.status!=='ACTIVE'||Number(rg.generation)!==generation||Number(l.generation)!==generation||Date.parse(l.expires_at)<=nowMs) throw new ControllerError('STALE_LEASE','lease cannot heartbeat'); this.db.prepare('UPDATE leases SET last_heartbeat_at=? WHERE lease_id=?').run(new Date(nowMs).toISOString(),leaseId); return true;}); }
  releaseLease(leaseId,generation,nowMs=Date.now()) { return this.atomic(()=>{const l=this.db.prepare('SELECT * FROM leases WHERE lease_id=?').get(leaseId); if(!l) throw new ControllerError('NOT_FOUND','lease not found'); const rg=this.db.prepare('SELECT generation FROM resource_generations WHERE resource_id=?').get(l.resource_id); if(l.status!=='ACTIVE'||Number(l.generation)!==generation||Number(rg.generation)!==generation) throw new ControllerError('STALE_LEASE','lease cannot release'); this.db.prepare("UPDATE leases SET status='RELEASED',last_heartbeat_at=? WHERE lease_id=?").run(new Date(nowMs).toISOString(),leaseId); this.appendEvent(`operation:${l.operation_id}`,this.currentStreamVersion(`operation:${l.operation_id}`),'lease.released',{lease_id:leaseId,operation_id:l.operation_id,resource_id:l.resource_id,generation},new Date(nowMs).toISOString()); return true;}); }
  assertWorkerLease({leaseId,generation,operationId},nowMs=Date.now()) { const l=this.db.prepare('SELECT * FROM leases WHERE lease_id=?').get(leaseId); if(!l) throw new ControllerError('NOT_FOUND','lease not found'); const rg=this.db.prepare('SELECT generation FROM resource_generations WHERE resource_id=?').get(l.resource_id); if(l.status!=='ACTIVE'||l.operation_id!==operationId||Number(l.generation)!==generation||Number(rg.generation)!==generation||Date.parse(l.expires_at)<=nowMs) throw new ControllerError('STALE_LEASE','stale fenced worker'); return l; }
  submitWorkerResult({leaseId,generation,operationId,result,evidence=null,nowMs=Date.now()}) {
    if(!['SUCCEEDED','FAILED','BLOCKED'].includes(result)) throw new ControllerError('WORKER_AUTHORITY_DENIED','worker may only submit bounded execution results');
    return this.atomic(()=>{const lease=this.assertWorkerLease({leaseId,generation,operationId},nowMs); const op=this.db.prepare('SELECT * FROM operations WHERE operation_id=?').get(operationId); if(!['RUNNING','VERIFYING'].includes(op.state)) throw new ControllerError('ILLEGAL_TRANSITION','worker result not legal from current state'); const now=new Date(nowMs).toISOString(); this.db.prepare('UPDATE operations SET state=?,updated_at=? WHERE operation_id=?').run(result,now,operationId); this.appendEvent(`operation:${operationId}`,this.currentStreamVersion(`operation:${operationId}`),`operation.${result.toLowerCase()}`,{operation_id:operationId,transaction_id:op.transaction_id,result,evidence},now); this.db.prepare("UPDATE leases SET status='RELEASED',last_heartbeat_at=? WHERE lease_id=?").run(now,leaseId); this.appendEvent(`operation:${operationId}`,this.currentStreamVersion(`operation:${operationId}`),'lease.released',{lease_id:leaseId,operation_id:operationId,resource_id:lease.resource_id,generation,reason:'worker-terminal-result'},now); return result;});
  }
  pendingOutbox(){return this.db.prepare("SELECT o.*,e.event_schema,e.stream_id,e.stream_version,e.event_type,e.occurred_at,e.data_json,e.prev_event_digest,e.event_digest FROM outbox o JOIN events e ON e.event_id=o.event_id WHERE o.status='PENDING' ORDER BY o.created_at,o.outbox_id").all();}
  markOutboxSealed(outboxId,now=new Date().toISOString()){this.db.prepare("UPDATE outbox SET status='SEALED',sealed_at=? WHERE outbox_id=? AND status='PENDING'").run(now,outboxId);}
  sealAllOutbox(){for(const o of this.pendingOutbox()) this.markOutboxSealed(o.outbox_id);}
  recordOutboxFailure(outboxId,message){this.db.prepare("UPDATE outbox SET attempts=attempts+1,last_error=? WHERE outbox_id=? AND status='PENDING'").run(String(message),outboxId);}
  verifyStream(streamId){const rows=this.db.prepare('SELECT * FROM events WHERE stream_id=? ORDER BY stream_version').all(streamId); let prev=null,v=0; for(const r of rows){if(r.event_schema!==EVENT_SCHEMA) throw new ControllerError('UNSUPPORTED_EVENT_SCHEMA','unsupported historic event schema'); if(Number(r.stream_version)!==v+1) throw new ControllerError('EVENT_GAP','event stream version gap'); const data=JSON.parse(r.data_json); const core={event_id:r.event_id,event_schema:r.event_schema,stream_id:r.stream_id,stream_version:Number(r.stream_version),event_type:r.event_type,occurred_at:r.occurred_at,prev_event_digest:r.prev_event_digest,data}; const d=sha256(core); if(r.prev_event_digest!==prev||r.event_digest!==d) throw new ControllerError('EVENT_INTEGRITY_FAILURE','event chain invalid'); prev=d;v+=1;} return {events:v,last_digest:prev};}
  exportEvents(){return this.db.prepare('SELECT * FROM events ORDER BY stream_id,stream_version').all().map(r=>({event_id:r.event_id,event_schema:r.event_schema,stream_id:r.stream_id,stream_version:Number(r.stream_version),event_type:r.event_type,occurred_at:r.occurred_at,data:JSON.parse(r.data_json),prev_event_digest:r.prev_event_digest,event_digest:r.event_digest}));}
  static replay(events){const grouped=new Map(); for(const e of events){if(e.event_schema!==EVENT_SCHEMA) throw new ControllerError('UNSUPPORTED_EVENT_SCHEMA','unsupported historic event schema'); if(!grouped.has(e.stream_id)) grouped.set(e.stream_id,[]); grouped.get(e.stream_id).push(e);} const state={transactions:{},operations:{},qualifications:{},promotions:{},resource_generations:{},last_event:null}; for(const [,list] of grouped){list.sort((a,b)=>a.stream_version-b.stream_version); let prev=null,v=0; for(const e of list){if(e.stream_version!==v+1) throw new ControllerError('EVENT_GAP','event stream version gap'); const core={event_id:e.event_id,event_schema:e.event_schema,stream_id:e.stream_id,stream_version:e.stream_version,event_type:e.event_type,occurred_at:e.occurred_at,prev_event_digest:e.prev_event_digest,data:e.data}; if(e.prev_event_digest!==prev||sha256(core)!==e.event_digest) throw new ControllerError('EVENT_INTEGRITY_FAILURE','event chain invalid'); prev=e.event_digest;v+=1; state.last_event=e.event_id; const d=e.data; if(e.event_type==='command.accepted') state.transactions[d.transaction_id]={state:'OPEN',command_id:d.command_id,subject_sha:d.command.target.expected_subject_sha}; if(e.event_type==='operation.planned') state.operations[d.operation_id]={state:'PLANNED',transaction_id:d.transaction_id}; if(e.event_type.startsWith('operation.')&&d.operation_id&&(d.to||d.result)) state.operations[d.operation_id]={...(state.operations[d.operation_id]||{}),state:d.to||d.result}; if(e.event_type==='lease.granted') state.resource_generations[d.resource_id]=Math.max(state.resource_generations[d.resource_id]||0,Number(d.generation)); if(e.event_type.startsWith('qualification.')&&d.qualification_id) state.qualifications[d.qualification_id]={state:d.state,subject_sha:d.subject_sha}; if(e.event_type.startsWith('promotion.')&&d.promotion_id) state.promotions[d.promotion_id]={state:d.state,subject_sha:d.subject_sha}; }} return state;}
  projection(maxAgeMs=300000,nowMs=Date.now()){const events=this.exportEvents(),state=ControllerKernel.replay(events),last=events.reduce((m,e)=>Math.max(m,Date.parse(e.occurred_at)||0),0); return {generated_at:new Date(nowMs).toISOString(),freshness:last&&nowMs-last<=maxAgeMs?'FRESH':'STALE',state};}
  createQualification(transactionId,subjectSha,policyVersion){return this.atomic(()=>{const id=uuidv7(),now=new Date().toISOString();this.db.prepare("INSERT INTO qualifications VALUES (?,?,?,?,'REQUESTED',?,?)").run(id,transactionId,subjectSha,policyVersion,now,now);this.appendEvent(`qualification:${id}`,0,'qualification.requested',{qualification_id:id,transaction_id:transactionId,subject_sha:subjectSha,policy_version:policyVersion,state:'REQUESTED'},now);return id;});}
  finishQualification(id,result){if(!['PASSED','FAILED','INDETERMINATE','CANCELLED'].includes(result)) throw new ControllerError('INVALID_STATE','bad qualification result');return this.atomic(()=>{const q=this.db.prepare('SELECT * FROM qualifications WHERE qualification_id=?').get(id);if(!q||!['REQUESTED','RUNNING'].includes(q.state)) throw new ControllerError('ILLEGAL_TRANSITION','qualification terminal or missing');const now=new Date().toISOString();this.db.prepare('UPDATE qualifications SET state=?,updated_at=? WHERE qualification_id=?').run(result,now,id);this.appendEvent(`qualification:${id}`,this.currentStreamVersion(`qualification:${id}`),`qualification.${result.toLowerCase()}`,{qualification_id:id,transaction_id:q.transaction_id,subject_sha:q.subject_sha,policy_version:q.policy_version,state:result},now);return result;});}
  requestPromotion(transactionId,qualificationId,subjectSha){return this.atomic(()=>{const q=this.db.prepare('SELECT * FROM qualifications WHERE qualification_id=?').get(qualificationId);if(!q) throw new ControllerError('NOT_FOUND','qualification not found');if(q.state!=='PASSED') throw new ControllerError('PROMOTION_NOT_QUALIFIED','qualification is not PASSED');if(q.subject_sha!==subjectSha) throw new ControllerError('SUBJECT_MISMATCH','promotion subject differs from qualification');const id=uuidv7(),now=new Date().toISOString();this.db.prepare("INSERT INTO promotions(promotion_id,transaction_id,subject_sha,qualification_id,state,created_at,updated_at) VALUES (?,?,?,?,'REQUESTED',?,?)").run(id,transactionId,subjectSha,qualificationId,now,now);this.appendEvent(`promotion:${id}`,0,'promotion.requested',{promotion_id:id,transaction_id:transactionId,subject_sha:subjectSha,qualification_id:qualificationId,state:'REQUESTED'},now);return id;});}
  authorizePromotion(id){return this.atomic(()=>{const p=this.db.prepare('SELECT * FROM promotions WHERE promotion_id=?').get(id);if(!p||p.state!=='REQUESTED') throw new ControllerError('ILLEGAL_TRANSITION','promotion not requestable');const now=new Date().toISOString(),e=this.appendEvent(`promotion:${id}`,this.currentStreamVersion(`promotion:${id}`),'promotion.authorized',{promotion_id:id,transaction_id:p.transaction_id,subject_sha:p.subject_sha,qualification_id:p.qualification_id,state:'AUTHORIZED'},now);this.db.prepare("UPDATE promotions SET state='AUTHORIZED',authorization_event_id=?,updated_at=? WHERE promotion_id=?").run(e.event_id,now,id);return e.event_id;});}
  executePromotion(id,adapter){const p=this.db.prepare('SELECT * FROM promotions WHERE promotion_id=?').get(id);if(!p||!['AUTHORIZED','EXECUTING','RECONCILIATION_REQUIRED'].includes(p.state)) throw new ControllerError('ILLEGAL_TRANSITION','promotion not executable');const seal=this.db.prepare("SELECT o.status FROM outbox o WHERE o.event_id=?").get(p.authorization_event_id);if(!seal||seal.status!=='SEALED') throw new ControllerError('DURABILITY_BARRIER_NOT_MET','promotion authorization is not durably sealed'); if(p.state==='RECONCILIATION_REQUIRED'||p.state==='EXECUTING') return this.reconcilePromotion(id,adapter); try{this.db.prepare("UPDATE promotions SET state='EXECUTING',updated_at=? WHERE promotion_id=?").run(new Date().toISOString(),id); adapter.apply({promotion_id:id,subject_sha:p.subject_sha}); return this.atomic(()=>{const now=new Date().toISOString();this.db.prepare("UPDATE promotions SET state='SUCCEEDED',updated_at=? WHERE promotion_id=?").run(now,id);this.appendEvent(`promotion:${id}`,this.currentStreamVersion(`promotion:${id}`),'promotion.succeeded',{promotion_id:id,transaction_id:p.transaction_id,subject_sha:p.subject_sha,state:'SUCCEEDED'},now);return 'SUCCEEDED';});}catch(e){return this.atomic(()=>{const now=new Date().toISOString();this.db.prepare("UPDATE promotions SET state='RECONCILIATION_REQUIRED',updated_at=? WHERE promotion_id=?").run(now,id);this.appendEvent(`promotion:${id}`,this.currentStreamVersion(`promotion:${id}`),'promotion.reconciliation-required',{promotion_id:id,transaction_id:p.transaction_id,subject_sha:p.subject_sha,qualification_id:p.qualification_id,state:'RECONCILIATION_REQUIRED',reason:String(e.message||e)},now);return 'RECONCILIATION_REQUIRED';});}}
  reconcilePromotion(id,adapter){const p=this.db.prepare('SELECT * FROM promotions WHERE promotion_id=?').get(id);if(!p) throw new ControllerError('NOT_FOUND','promotion not found');const observed=adapter.observe({promotion_id:id,subject_sha:p.subject_sha});if(observed===true)return this.atomic(()=>{const now=new Date().toISOString();this.db.prepare("UPDATE promotions SET state='SUCCEEDED',updated_at=? WHERE promotion_id=?").run(now,id);this.appendEvent(`promotion:${id}`,this.currentStreamVersion(`promotion:${id}`),'promotion.succeeded',{promotion_id:id,transaction_id:p.transaction_id,subject_sha:p.subject_sha,qualification_id:p.qualification_id,state:'SUCCEEDED',recovered:true},now);return 'SUCCEEDED';});if(observed===false)return this.atomic(()=>{const now=new Date().toISOString();this.db.prepare("UPDATE promotions SET state='AUTHORIZED',updated_at=? WHERE promotion_id=?").run(now,id);this.appendEvent(`promotion:${id}`,this.currentStreamVersion(`promotion:${id}`),'promotion.reconciled-not-applied',{promotion_id:id,transaction_id:p.transaction_id,subject_sha:p.subject_sha,qualification_id:p.qualification_id,state:'AUTHORIZED'},now);return 'AUTHORIZED';});throw new ControllerError('EXTERNAL_STATE_UNKNOWN','promotion reality remains unknown');}
}
