package org.systemmaster.continuity;

import java.nio.file.*;
import java.time.Instant;
import java.util.*;

public final class Gwp003QualificationTest{
 static int n=0;
 public static void main(String[] args)throws Exception{
  Path dir=Files.createTempDirectory("gwp003-test-"); FakeAuthority a=new FakeAuthority(); a.register("work-1");
  InterruptionDetector d=new InterruptionDetector(dir,a);
  var cmd=new InterruptionDetector.ReportCommand("work-1",1,"attempt-1","LEASE_MONITOR","heartbeat missing","dedupe-1",true,Instant.parse("2026-09-08T00:00:00Z"),Instant.parse("2026-09-07T23:59:00Z"),"EXPIRED","proc-1","UNKNOWN",List.of("ev-1"));
  var r1=d.report(cmd); eq(false,r1.deduped()); eq("DETECTED",r1.recovery().state()); eq("work-1",r1.observation().workUnitId()); eq("dedupe-1",r1.observation().dedupeKey()); yes(r1.observation().observationDigest().matches("[0-9a-f]{64}"));
  var r2=d.report(cmd); eq(true,r2.deduped()); eq(r1.observation().interruptionId(),r2.observation().interruptionId()); eq(r1.recovery().recoveryId(),r2.recovery().recoveryId());
  expect(()->d.report(new InterruptionDetector.ReportCommand("work-1",1,"attempt-1","LEASE_MONITOR","different","dedupe-1",true,Instant.now(),null,"EXPIRED",null,null,List.of())));
  expect(()->d.report(new InterruptionDetector.ReportCommand("work-1",1,"attempt-1","LEASE_MONITOR","x","d2",false,Instant.now(),null,"EXPIRED",null,null,List.of())));
  InterruptionDetector restarted=new InterruptionDetector(dir,a); eq(r1.observation().interruptionId(),restarted.getByDedupeKey("dedupe-1").interruptionId());

  RecoveryClassifier c=new RecoveryClassifier(dir,a); String rid=r1.recovery().recoveryId();
  var valid=e(RecoveryClassifier.CheckpointState.VALID,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,true,false,false,"cp-1");
  var cv=c.classify(rid,valid); eq(RecoveryClassification.RecoveryClass.RESUME,cv.recoveryClass()); eq("CLASSIFYING",a.get(rid).state()); yes(cv.evidenceSetDigest().matches("[0-9a-f]{64}")); eq(cv.classificationId(),c.classify(rid,valid).classificationId()); eq("work-1",cv.workUnitId()); eq("cp-1",cv.checkpointCandidateRef());
  eq(RecoveryClassification.RecoveryClass.RECONCILE_THEN_RESUME,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.VALID,RecoveryClassifier.ExternalEffectState.UNKNOWN,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,false,"cp-1")).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.RESTART_SAFE_BOUNDARY,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.NONE,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,true,false,false,null)).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.RESTART_BEGINNING,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.NONE,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,false,null)).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.WAIT_DEPENDENCY,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.VALID,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.WAITING,false,false,false,"cp")).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.MIGRATE,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.VALID,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.INCOMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,false,"cp")).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.OLD_RUNTIME,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.VALID,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.INCOMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,true,false,"cp")).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.MANUAL,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.UNKNOWN,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,false,null)).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.MANUAL,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.VALID,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.UNKNOWN,RecoveryClassifier.DependencyState.READY,false,false,false,"cp")).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.QUARANTINE,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.CORRUPT,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,false,"cp")).recoveryClass());
  eq(RecoveryClassification.RecoveryClass.TERMINAL,RecoveryClassifier.decide(e(RecoveryClassifier.CheckpointState.NONE,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,true,null)).recoveryClass());
  eq(10,RecoveryClassification.RecoveryClass.values().length);

  RecoveryPlanner p=new RecoveryPlanner(dir,a); var pi=new RecoveryPlanner.PlanInputs("policy-1","cp-1",List.of(),"compat-1","auth-1","STANDARD",List.of("state-match","effect-match"));
  var plan=p.plan(rid,cv,pi); yes(plan.ready()); eq(1L,plan.version()); eq(RecoveryClassification.RecoveryClass.RESUME,plan.disposition()); eq(List.of("VALIDATE_CHECKPOINT","START_RESUME","VERIFY"),plan.steps()); yes(plan.planDigest().matches("[0-9a-f]{64}")); yes(plan.inputStateDigest().matches("[0-9a-f]{64}")); eq("PLAN_READY",a.get(rid).state()); eq(cv.classificationId(),plan.classificationId()); eq(2,plan.verificationCriteria().size());
  var same=p.plan(rid,cv,pi); eq(plan.planDigest(),same.planDigest()); eq(1L,same.version());
  var changed=p.plan(rid,cv,new RecoveryPlanner.PlanInputs("policy-2","cp-1",List.of(),"compat-1","auth-1","STANDARD",List.of("state-match","effect-match"))); eq(2L,changed.version()); no(plan.inputStateDigest().equals(changed.inputStateDigest())); no(plan.planDigest().equals(changed.planDigest()));
  RecoveryPlanner restartedPlanner=new RecoveryPlanner(dir,a); eq(changed.planDigest(),restartedPlanner.getRecoveryPlan(rid).planDigest());

  a.register("work-2"); var rr=d.report(new InterruptionDetector.ReportCommand("work-2",1,"a2","MON","x","d-work-2",true,Instant.now(),null,"EXPIRED",null,null,List.of("ev2"))); var cc=new RecoveryClassifier(dir,a).classify(rr.recovery().recoveryId(),e(RecoveryClassifier.CheckpointState.UNKNOWN,RecoveryClassifier.ExternalEffectState.NONE,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,false,null)); eq(RecoveryClassification.RecoveryClass.MANUAL,cc.recoveryClass()); eq("MANUAL_DECISION",a.get(rr.recovery().recoveryId()).state()); var blocked=new RecoveryPlanner(dir,a).plan(rr.recovery().recoveryId(),cc,new RecoveryPlanner.PlanInputs("p",null,List.of(),"c","a","STANDARD",List.of("verify"))); no(blocked.ready()); yes(blocked.blockers().contains("MANUAL_DECISION_REQUIRED"));

  a.register("work-3"); var r3=d.report(new InterruptionDetector.ReportCommand("work-3",1,"a3","MON","x","d-work-3",true,Instant.now(),null,"EXPIRED",null,null,List.of())); var c3=new RecoveryClassifier(dir,a).classify(r3.recovery().recoveryId(),e(RecoveryClassifier.CheckpointState.VALID,RecoveryClassifier.ExternalEffectState.UNKNOWN,RecoveryClassifier.CompatibilityState.COMPATIBLE,RecoveryClassifier.AuthorityState.AUTHORIZED,RecoveryClassifier.DependencyState.READY,false,false,false,"cp3")); var p3=new RecoveryPlanner(dir,a).plan(r3.recovery().recoveryId(),c3,new RecoveryPlanner.PlanInputs("p","cp3",List.of(),"c","a","STANDARD",List.of("verify"))); no(p3.ready()); yes(p3.blockers().contains("RECONCILIATION_ITEMS_MISSING"));

  Path journal=dir.resolve("gwp003-recovery-planning.journal"); byte[] bytes=Files.readAllBytes(journal); bytes[bytes.length/2]^=1; Files.write(journal,bytes); expect(()->new RecoveryClassifier(dir,a));
  if(n!=50)throw new AssertionError("TEST_COUNT expected=50 actual="+n); System.out.println("PASS G-WP-003 tests=50 requirements=6");
 }
 static RecoveryClassifier.EvidenceSet e(RecoveryClassifier.CheckpointState cp,RecoveryClassifier.ExternalEffectState ex,RecoveryClassifier.CompatibilityState co,RecoveryClassifier.AuthorityState au,RecoveryClassifier.DependencyState de,boolean safe,boolean old,boolean term,String ref){return new RecoveryClassifier.EvidenceSet(cp,ref,ex,co,au,de,safe,old,term,List.of("ev"));}
 static void eq(Object a,Object b){n++;if(!Objects.equals(a,b))throw new AssertionError(a+" != "+b);} static void yes(boolean v){n++;if(!v)throw new AssertionError("expected true");} static void no(boolean v){yes(!v);} static void expect(Runnable r){n++;try{r.run();throw new AssertionError("expected throw");}catch(AssertionError e){throw e;}catch(RuntimeException ok){}}
 static final class FakeAuthority implements RecoveryAuthority{final Map<String,Handle> byId=new HashMap<>();final Map<String,String> active=new HashMap<>();void register(String w){} public Handle openRecovery(String w,long v,String i){String id=active.get(w);if(id!=null)return byId.get(id);id="rec-"+w;Handle h=new Handle(id,w,1,"DETECTED");active.put(w,id);byId.put(id,h);return h;} public Handle get(String id){Handle h=byId.get(id);if(h==null)throw new IllegalArgumentException("unknown");return h;} public Handle transition(String id,long expected,String from,String to,String reason,List<String> e,String c){Handle h=get(id);if(h.version()!=expected)throw new IllegalStateException("stale");if(!h.state().equals(from))throw new IllegalStateException("from");Handle x=new Handle(id,h.workUnitId(),h.version()+1,to);byId.put(id,x);return x;}}
}
