package org.systemmaster.tools.pdf;
import java.nio.charset.StandardCharsets;import java.util.*;
public final class PdfFullLanePortableTests {static int n;public static void main(String[]a)throws Exception{
 check(PdfFullLaneCapabilities.all().size()==164,"164 capabilities");check(PdfSemanticActions.all().size()==70,"70 semantic actions");check(PdfFullLaneCapabilities.all().stream().noneMatch(d->d.disposition().isBlank()),"all dispositions");
 PdfStructuralEngine e=new PdfStructuralEngine();byte[] pdf=e.createTextPdf(List.of("System Master PDF","portable proof"));var i=e.inspect(pdf);check(i.pages()==1,"one page");check(i.indirectObjects()==5,"five objects");check(i.eofPresent()&&i.startXrefPresent(),"xref eof");check(i.literalText().stream().anyMatch(x->x.contains("System Master PDF")),"literal extraction");check(e.diagnose(pdf).isEmpty(),"clean diagnosis");check(e.absenceProof(pdf,List.of("/JavaScript","/Launch")),"active-content absence");
 PdfEnginePort fake=new PdfEnginePort(){public Identity identity(){return new Identity("FAKE-PDF","1","digest",Set.of("pdf.extract.text","pdf.redaction.apply"),true);}public Result execute(Request r){if(r.action().equals("pdf.redaction.apply")){String s=new String(r.source(),StandardCharsets.ISO_8859_1).replace(r.parameters().getOrDefault("forbiddenToken","NEVER"),"[REDACTED]");return new Result(s.getBytes(StandardCharsets.ISO_8859_1),Map.of("mode","test"),List.of());}return new Result(r.source(),Map.of("text","ok"),List.of());}};
 PdfFullLaneService svc=new PdfFullLaneService();var receipt=svc.executeWith(fake,"pdf.extract.text",pdf,Map.of());check(receipt.verified(),"adapter read verified");byte[] withSecret=new String(pdf,StandardCharsets.ISO_8859_1).replace("portable proof","SECRET_VALUE").getBytes(StandardCharsets.ISO_8859_1);var red=svc.executeWith(fake,"pdf.redaction.apply",withSecret,Map.of("forbiddenToken","SECRET_VALUE"));check(red.verified(),"redaction absence proof");
 boolean rejected=false;try{svc.executeWith(new PdfEnginePort(){public Identity identity(){return new Identity("BAD","1","d",Set.of("pdf.extract.text"),false);}public Result execute(Request r){throw new AssertionError();}},"pdf.extract.text",pdf,Map.of());}catch(IllegalStateException ex){rejected=true;}check(rejected,"unhealthy engine rejected");
 System.out.println("PDF_FULL_LANE_PORTABLE_PASS assertions="+n+" portable="+PdfFullLaneCapabilities.portable()+" delegated="+PdfFullLaneCapabilities.delegated()+" pending="+PdfFullLaneCapabilities.pending());}
 static void check(boolean c,String m){n++;if(!c)throw new AssertionError(m);} }
