package org.systemmaster.foundation.root;

import static org.systemmaster.foundation.root.SystemAuthority.AuthorityKind.*;
import static org.systemmaster.foundation.root.SystemAuthority.Descriptor;

import java.util.List;
import java.util.Set;

/** Machine-readable bootstrap roster for the currently locked Foundation & Spine architecture. */
public final class FoundationAuthorityCatalog {
    private FoundationAuthorityCatalog() {}

    public static List<Descriptor> canonical() {
        return List.of(
                d("system-root", "System Root & Authority Registry",
                        "What shared systems and authorities exist now, which version is current, who owns each one, and which are admitted or retired?",
                        FOUNDATION_CONTROL,
                        s("foundation.topology", "foundation.truth-owner-map", "foundation.authority-version-pointer", "foundation.system-lifecycle", "foundation.product-root-integration"),
                        s("Does not own specialist data", "Does not own runtime job state", "Does not own user intent")),
                d("identity-delegation", "Identity, Principal & Delegation",
                        "Who or what actor is this, and what authority was delegated to it?",
                        FOUNDATION_CONTROL,
                        s("identity.principal", "identity.actor-chain", "identity.delegation", "identity.capability-grant", "identity.revocation"),
                        s("Does not own goals", "Does not own resource scheduling", "Does not own effect decisions")),
                d("contracts-versioning", "Contracts & Versioning",
                        "What exact schema, protocol, or contract version governs this exchange?",
                        FOUNDATION_CONTROL,
                        s("contracts.schema", "contracts.protocol", "contracts.compatibility", "contracts.digest", "contracts.deprecation"),
                        s("Does not own business semantics", "Does not own policy decisions")),
                d("intent-keel", "Intent / Keel",
                        "What outcome did the user authorize, under what constraints?",
                        FOUNDATION_CONTROL,
                        s("intent.goal-revision", "intent.constraints", "intent.success-criteria", "intent.delegation-ceiling", "intent.cancel-supersede"),
                        s("Does not own executable plans", "Does not own routes", "Does not own jobs")),
                d("work-project", "Work & Project Control",
                        "What durable work or project are we managing over time?",
                        FOUNDATION_SHARED,
                        s("work.identity", "work.hierarchy", "work.milestones", "work.rollup", "work.project-memory-ref"),
                        s("Does not own low-level attempts", "Does not own worker leases", "Does not own plan execution state")),
                d("planning-orchestration", "Planning & Orchestration",
                        "What plan revision and step graph should satisfy the active goal?",
                        FOUNDATION_CONTROL,
                        s("plan.revision", "plan.step-graph", "plan.readiness", "plan.replanning", "plan.completion-predicate"),
                        s("Does not own user intent", "Does not own resource grants", "Does not own concrete worker placement")),
                d("resource-admission", "Resource Admission & Budgeting",
                        "May this workload consume capacity now, and what exact resources are reserved for it?",
                        FOUNDATION_CONTROL,
                        s("resource.budget", "resource.admission", "resource.reservation", "resource.grant", "resource.accounting"),
                        s("Does not choose capability routes", "Does not choose concrete executors")),
                d("capability-routing", "Capability Registry & Routing",
                        "Which qualified capability or provider path is valid for this plan step?",
                        FOUNDATION_CONTROL,
                        s("routing.capability-descriptor", "routing.candidate", "routing.decision", "routing.snapshot", "routing.eligibility"),
                        s("Does not allocate resources", "Does not place workers", "Does not authorize external effects")),
                d("execution-placement", "Execution Placement",
                        "Which exact executor is eligible and should run this routed attempt?",
                        FOUNDATION_CONTROL,
                        s("placement.executor-eligibility", "placement.assignment", "placement.drain", "placement.reassignment", "placement.assignment-lease"),
                        s("Does not choose capability routes", "Does not admit resources", "Does not authorize effects")),
                d("durable-runtime", "Durable Execution Runtime",
                        "What is the durable execution state of this job or attempt right now?",
                        FOUNDATION_CONTROL,
                        s("runtime.job", "runtime.attempt", "runtime.lease-fence", "runtime.checkpoint", "runtime.retry-cancel"),
                        s("Does not own user intent", "Does not own project semantics", "Does not choose routes")),
                d("transport-delivery", "Transport & Delivery",
                        "Was this command or event durably delivered, consumed, replayed, or quarantined?",
                        FOUNDATION_SHARED,
                        s("transport.outbox", "transport.inbox", "transport.delivery-attempt", "transport.dedup", "transport.quarantine"),
                        s("Does not own workflow completion", "Does not own event business meaning")),
                d("context-retrieval", "Context, Memory & Retrieval Broker",
                        "What authorized context was assembled, and from where?",
                        FOUNDATION_SHARED,
                        s("context.assembly", "context.source-binding", "context.freshness", "context.trust", "context.receipt"),
                        s("Does not own source truth", "Does not own user intent")),
                d("model-gateway", "Model Gateway",
                        "What model, profile, and version ran under what limits, and what result did it return?",
                        FOUNDATION_SHARED,
                        s("model.invocation", "model.profile", "model.version-binding", "model.structured-result", "model.receipt"),
                        s("Does not grant effect permission", "Does not own AI safety standing")),
                d("tool-connector-gateway", "Tool & Connector Gateway",
                        "What tool or connector invocation occurred, and what normalized result returned?",
                        FOUNDATION_SHARED,
                        s("tool.discovery", "tool.invocation", "tool.schema-validation", "tool.result-normalization", "tool.transport"),
                        s("Does not grant invocation authority", "Does not authorize external effects")),
                d("effect-authority", "Effect / Action Authority",
                        "Is this exact external mutation authorized now, and what committed?",
                        FOUNDATION_CONTROL,
                        s("effect.commit-authority", "effect.identity", "effect.idempotency", "effect.receipt", "effect.unknown-commit"),
                        s("Does not own tool availability", "Does not own planning approval")),
                d("artifact-gateway", "Artifact Gateway",
                        "What exact artifact bytes, version, and lineage are in shared custody?",
                        FOUNDATION_SHARED,
                        s("artifact.custody", "artifact.digest-identity", "artifact.version", "artifact.lineage", "artifact.transfer-state"),
                        s("Does not own specialist artifact semantics", "Does not own project intent")),
                d("canonical-data", "Canonical Data & Persistence",
                        "What shared structured-state transaction and version are canonical?",
                        FOUNDATION_SHARED,
                        s("data.transaction", "data.concurrency", "data.migration", "data.backup-restore", "data.projection"),
                        s("Does not absorb domain semantic ownership", "Does not certify completion")),
                d("evidence-assurance", "Evidence, Provenance & Assurance",
                        "What evidence supports which exact claim and subject, and what standing follows?",
                        FOUNDATION_CONTROL,
                        s("evidence.object", "evidence.causal-link", "evidence.provenance", "evidence.standing", "evidence.invalidation"),
                        s("Does not treat logs as proof", "Does not own production telemetry")),
                d("observability", "Observability & Telemetry",
                        "What operational telemetry was observed?",
                        FOUNDATION_SHARED,
                        s("telemetry.trace", "telemetry.metric", "telemetry.log", "telemetry.health", "telemetry.alert"),
                        s("Does not own business truth", "Does not certify completion")),
                d("recovery-reconciliation", "Recovery & Reconciliation",
                        "Given fault, interruption, ambiguity, or divergence, what recovery action is valid?",
                        FOUNDATION_CONTROL,
                        s("recovery.episode", "recovery.reconciliation", "recovery.compensation", "recovery.restore-reentry", "recovery.resource-reclaim"),
                        s("Does not become a shadow job engine", "Does not become a shadow router", "Does not overwrite source truth")),
                d("security-privacy-crypto", "Security, Privacy, Secrets & Cryptography",
                        "What shared security, privacy, secret, and cryptographic policy permits or blocks this?",
                        FOUNDATION_CONTROL,
                        s("security.policy-enforcement", "security.privacy-purpose", "security.secret-reference", "security.crypto-verification", "security.sandbox-policy"),
                        s("Does not own business goals", "Does not infer rights standing")),
                d("provider-dependency", "Provider & Dependency Governance",
                        "What provider, dependency, build, model, or tool version and provenance standing is acceptable?",
                        FOUNDATION_CONTROL,
                        s("provider.identity", "provider.approved-version", "provider.health-standing", "provider.deprecation", "provider.supply-chain-standing"),
                        s("Does not make per-step route decisions", "Does not own release promotion")),
                d("ai-safety", "AI Safety & Model Risk",
                        "What AI, model, or agent risk standing and autonomy limit applies?",
                        FOUNDATION_CONTROL,
                        s("ai-risk.tier", "ai-risk.autonomy-ceiling", "ai-risk.eval-standing", "ai-risk.human-oversight", "ai-risk.drift-standing"),
                        s("Does not own model availability", "Does not grant effect permission")),
                d("rights-licensing", "Rights, Licensing & Attribution",
                        "What rights, licensing, permission, and attribution constraints permit this use?",
                        FOUNDATION_CONTROL,
                        s("rights.use-standing", "rights.source-restriction", "rights.attribution", "rights.commercial-use", "rights.publication"),
                        s("Does not own privacy policy", "Does not provide legal advice")),
                d("ux-work-control", "UX / Chat / Work Control Surface",
                        "What truthful user-facing projection or control is shown or requested?",
                        FOUNDATION_SHARED,
                        s("ux.work-projection", "ux.control-request", "ux.approval-surface", "ux.offline-state", "ux.artifact-navigation"),
                        s("Does not own job truth", "Does not own evidence truth", "Does not own work completion truth")),
                d("change-release-governance", "Change, Migration, Release & Operator Governance",
                        "What governed system change, release, migration, or operator action is current and approved?",
                        FOUNDATION_CONTROL,
                        s("change.registration", "change.impact", "change.approval", "change.release-candidate", "change.operator-action"),
                        s("Does not own runtime job execution", "Does not own provider qualification truth")),
                d("creative-fabric", "Creative Fabric",
                        "What creative coordination and coherence support applies without becoming a spine control authority?",
                        FEDERATED_OVERLAY,
                        s("creative.participation-profile", "creative.work-graph", "creative.context", "creative.quality-profile", "creative.coherence-evaluation"),
                        s("Does not own routing", "Does not own resource grants", "Does not own effect authority", "Does not own artifact byte truth"))
        );
    }

    private static Descriptor d(
            String id,
            String name,
            String question,
            SystemAuthority.AuthorityKind kind,
            Set<String> truths,
            Set<String> negatives) {
        return new Descriptor(id, name, question, kind, truths, negatives);
    }

    private static Set<String> s(String... values) {
        return Set.of(values);
    }
}
