package org.systemmaster.continuity;
import java.io.*;import java.nio.*;import java.nio.channels.*;import java.nio.charset.*;import java.nio.file.*;import java.security.*;import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.locks.*;
final class ResumeStore{private static final Map<Path,ReentrantLock>L=new ConcurrentHashMap<>();private final Path root,journal,lock;private final ReentrantLock jl;
 ResumeStore(Path root){try{this.root=root.toAbsolutePath().normalize();Files.createDirectories(this.root);journal=this.root.resolve("resume.log");lock=this.root.resolve("resume.lock");if(!Files.exists(journal))Files.createFile(journal);if(!Files.exists(lock))Files.createFile(lock);jl=L.computeIfAbsent(this.root,p->new ReentrantLock());}catch(IOException e){throw new StoreException(e);}}
 <T>T tx(Fn<T> fn){jl.lock();try(FileChannel c=FileChannel.open(lock,StandardOpenOption.WRITE);FileLock ignored=c.lock()){Snapshot s=load();Decision<T>d=fn.apply(s);if(d.frame!=null)append(d.frame);return d.result;}catch(IOException e){throw new StoreException(e);}finally{jl.unlock();}}
 Snapshot snapshot(){return tx(s->Decision.read(s));}
 private Snapshot load(){try{Map<String,RecordedDecision>dec=new LinkedHashMap<>();Map<String,ExecutionAttemptRef>att=new LinkedHashMap<>();Map<String,String>start=new HashMap<>();Map<String,Outcome>out=new HashMap<>();Map<String,Receipt>receipts=new HashMap<>();Map<String,Long>maxAttempt=new HashMap<>();for(String line:Files.readAllLines(journal,StandardCharsets.UTF_8)){if(line.isBlank())continue;int k=line.lastIndexOf('|');if(k<1)throw new StoreException("corrupt resume journal");String p=line.substring(0,k);if(!sha(p).equals(line.substring(k+1)))throw new StoreException("resume journal checksum mismatch");String[]x=p.split("\\|",-1);switch(x[0]){case"D"->{if(x.length!=11)throw new StoreException("bad decision frame");RecordedDecision d=new RecordedDecision(x[1],Long.parseLong(x[2]),ub(x[3]),x[4],ub(x[5]),Instant.parse(x[6]),blank(ub(x[7])),decodeList(x[8]),x[9]);dec.put(key(d.workUnitId(),d.decisionSeq()),d);receipts.put("D:"+key(d.workUnitId(),d.decisionSeq()),new Receipt(x[10],"D"));}case"A"->{if(x.length!=13)throw new StoreException("bad attempt frame");ExecutionAttemptRef a=new ExecutionAttemptRef(x[1],x[2],Long.parseLong(x[3]),x[4],blank(ub(x[5])),Long.parseLong(x[6]),ub(x[7]),Instant.parse(x[8]),null,null);att.put(a.attemptId(),a);start.put(x[9],a.attemptId());maxAttempt.merge(a.workUnitId(),a.attemptNo(),Math::max);receipts.put("A:"+x[9],new Receipt(x[10],a.attemptId()));}case"O"->{if(x.length!=8)throw new StoreException("bad outcome frame");Outcome o=new Outcome(x[1],Long.parseLong(x[2]),ub(x[3]),x[4],Instant.parse(x[5]));out.put(x[1]+":"+x[2],o);receipts.put("O:"+x[1]+":"+x[2],new Receipt(x[6],x[1]));}default->throw new StoreException("unknown frame");}}return new Snapshot(Map.copyOf(dec),Map.copyOf(att),Map.copyOf(start),Map.copyOf(out),Map.copyOf(receipts),Map.copyOf(maxAttempt));}catch(IOException|RuntimeException e){if(e instanceof StoreException s)throw s;throw new StoreException(e);}}
 void append(String p){byte[]b=(p+"|"+sha(p)+"\n").getBytes(StandardCharsets.UTF_8);try(FileChannel c=FileChannel.open(journal,StandardOpenOption.WRITE,StandardOpenOption.APPEND)){c.write(ByteBuffer.wrap(b));c.force(true);}catch(IOException e){throw new StoreException(e);}}
 static String decisionFrame(RecordedDecision d,String digest){return String.join("|","D",d.workUnitId(),Long.toString(d.decisionSeq()),b64(d.decisionType()),d.inputDigest(),b64(d.result()),d.logicalTime().toString(),b64(d.providerOrToolRef()==null?"":d.providerOrToolRef()),encodeList(d.evidenceRefs()),d.resultDigest(),digest);} static String attemptFrame(ExecutionAttemptRef a,String startKey,String requestDigest){return String.join("|","A",a.attemptId(),a.workUnitId(),Long.toString(a.attemptNo()),a.recoveryId(),b64(a.resumedFromCheckpointRef()==null?"":a.resumedFromCheckpointRef()),Long.toString(a.fenceEpoch()),b64(a.runtimeIdentity()),a.startedAt().toString(),startKey,requestDigest,"","");} static String outcomeFrame(Outcome o,String requestDigest){return String.join("|","O",o.attemptId,Long.toString(o.seq),b64(o.outcome),o.evidenceDigest,o.recordedAt.toString(),requestDigest,"");}
 static String key(String w,long s){return w+":"+s;} static String encodeList(List<String> xs){return b64(String.join("\n",xs));} static List<String> decodeList(String s){String x=ub(s);return x.isEmpty()?List.of():List.of(x.split("\n",-1));} static String sha(String s){try{byte[]d=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();for(byte x:d)b.append(String.format("%02x",x));return b.toString();}catch(Exception e){throw new IllegalStateException(e);}}static String b64(String s){return Base64.getUrlEncoder().withoutPadding().encodeToString(s.getBytes(StandardCharsets.UTF_8));}static String ub(String s){return new String(Base64.getUrlDecoder().decode(s),StandardCharsets.UTF_8);}static String blank(String s){return s==null||s.isBlank()?null:s;}
 record Snapshot(Map<String,RecordedDecision>decisions,Map<String,ExecutionAttemptRef>attempts,Map<String,String>startKeys,Map<String,Outcome>outcomes,Map<String,Receipt>receipts,Map<String,Long>maxAttempt){}record Outcome(String attemptId,long seq,String outcome,String evidenceDigest,Instant recordedAt){}record Receipt(String digest,String ref){}record Decision<T>(T result,String frame){static<T>Decision<T>read(T r){return new Decision<>(r,null);}static<T>Decision<T>append(T r,String f){return new Decision<>(r,f);}}interface Fn<T>{Decision<T>apply(Snapshot s);}static final class StoreException extends RuntimeException{StoreException(String m){super(m);}StoreException(Throwable t){super(t);}}
}
