package org.systemmaster.continuity;
import java.nio.file.Path;import java.time.Instant;import java.util.*;
public final class ExternalEffectRecoveryCoordinator{
 private final Gwp007Store s;private final Authorizer a;public ExternalEffectRecoveryCoordinator(Path d,Authorizer a){s=new Gwp007Store(d);this.a=Objects.requireNonNull(a);}
 public ExternalEffectRecoveryItem registerEffect(String id,String w,String op,String key,String p,ExternalEffectRecoveryItem.ReconciliationPolicy pol,List<String> ev){var n=new ExternalEffectRecoveryItem(id,w,op,key,p,ExternalEffectRecoveryItem.State.PENDING,null,null,pol,ev,1);return s.transact(x->{var old=x.items().get(n.effectId());if(old!=null){if(!same(old,n))throw new Conflict("effect intent conflict");return new Gwp007Store.Decision<>(old,null);}if(n.idempotencyKey()!=null){String oid=x.idempotencyKeys().get(n.idempotencyKey());if(oid!=null){var o=x.items().get(oid);if(o!=null&&(!o.operationDigest().equals(n.operationDigest())||!o.providerRef().equals(n.providerRef())))throw new Conflict("idempotency semantic conflict");}}return new Gwp007Store.Decision<>(n,Gwp007Store.itemFrame(n));});}
 public ReconciliationReceipt reconcileExternalEffect(String id,String rid,Observation o){req(rid);Objects.requireNonNull(o);return s.transact(x->{var c=x.items().get(req(id));if(c==null)throw new UnknownEffect();if(!a.ok(c.providerRef(),rid,o.authRef(),o.at()))throw new Unauthorized();String dg=digest(c.effectId(),rid,c.providerRef(),o.state(),o.receipt(),o.authRef(),o.at(),o.evidence());if(!dg.equals(o.digest()))throw new IllegalArgumentException("observation digest");var prior=x.receipts().get(c.effectId()+"|"+o.digest());if(prior!=null)return new Gwp007Store.Decision<>(prior,null);if(o.state()==ExternalEffectRecoveryItem.State.CONFIRMED_APPLIED&&blank(o.receipt()))throw new IllegalArgumentException("receipt required");if(c.state()==ExternalEffectRecoveryItem.State.CONFIRMED_APPLIED&&o.state()==ExternalEffectRecoveryItem.State.PENDING)throw new Conflict("applied regression");var ev=merge(c.evidenceRefs(),o.evidence());var n=new ExternalEffectRecoveryItem(c.effectId(),c.workUnitId(),c.operationDigest(),c.idempotencyKey(),c.providerRef(),o.state(),o.receipt(),o.at(),c.reconciliationPolicy(),ev,c.version()+1);var r=new ReconciliationReceipt(c.effectId(),o.digest(),n.state(),n.version(),n.externalReceiptRef(),Gwp007Store.sha256(String.join("|",ev)),o.at());return new Gwp007Store.Decision<>(r,Gwp007Store.reconcileFrame(n,r));});}
 public List<ExternalEffectRecoveryItem> listUnknownExternalEffects(String w){w=req(w);var out=new ArrayList<ExternalEffectRecoveryItem>();for(var i:s.snapshot().items().values())if(i.workUnitId().equals(w)&&i.blocksReplay())out.add(i);out.sort(Comparator.comparing(ExternalEffectRecoveryItem::effectId));return List.copyOf(out);}
 public ReplayDecision replayDecision(String id,String w){var i=s.snapshot().items().get(req(id));if(i==null)throw new UnknownEffect();if(!i.workUnitId().equals(req(w)))throw new Conflict("work mismatch");return switch(i.state()){case PENDING,UNKNOWN,DIVERGED->new ReplayDecision(Disposition.BLOCK_REPLAY,i.effectId(),i.externalReceiptRef(),i.version(),"UNRESOLVED_EXTERNAL_EFFECT");case CONFIRMED_APPLIED->new ReplayDecision(Disposition.CONSUME_RECEIPT,i.effectId(),i.externalReceiptRef(),i.version(),"ALREADY_APPLIED_DO_NOT_REISSUE");case CONFIRMED_NOT_APPLIED->new ReplayDecision(Disposition.ALLOW_NEW_EFFECT_ACTIVITY,i.effectId(),null,i.version(),"NEW_EFFECT_MUST_RUN_OUTSIDE_PURE_REPLAY");};}
 public boolean pureReplayAllowed(String w){return listUnknownExternalEffects(w).isEmpty();}public ExternalEffectRecoveryItem get(String id){return s.snapshot().items().get(req(id));}Path journalPath(){return s.file();}
 public static String digest(String id,String rid,String p,ExternalEffectRecoveryItem.State st,String rc,String ar,Instant at,List<String> ev){return Gwp007Store.sha256(String.join("|",req(id),req(rid),req(p),Objects.requireNonNull(st).name(),rc==null?"":rc.trim(),req(ar),Objects.requireNonNull(at).toString(),String.join(",",ev==null?List.of():ev)));}
 private static boolean same(ExternalEffectRecoveryItem x,ExternalEffectRecoveryItem y){return x.workUnitId().equals(y.workUnitId())&&x.operationDigest().equals(y.operationDigest())&&Objects.equals(x.idempotencyKey(),y.idempotencyKey())&&x.providerRef().equals(y.providerRef())&&x.reconciliationPolicy()==y.reconciliationPolicy();}private static List<String> merge(List<String>x,List<String>y){var z=new LinkedHashSet<String>(x);if(y!=null)z.addAll(y);return List.copyOf(z);}private static boolean blank(String v){return v==null||v.trim().isEmpty();}private static String req(String v){if(blank(v))throw new IllegalArgumentException("required");return v.trim();}
 public record Observation(ExternalEffectRecoveryItem.State state,String receipt,String authRef,Instant at,List<String> evidence,String digest){public Observation{Objects.requireNonNull(state);authRef=req(authRef);Objects.requireNonNull(at);evidence=List.copyOf(evidence==null?List.of():evidence);digest=req(digest);}}public record ReplayDecision(Disposition disposition,String effectId,String receipt,long version,String reason){}public enum Disposition{BLOCK_REPLAY,CONSUME_RECEIPT,ALLOW_NEW_EFFECT_ACTIVITY}@FunctionalInterface public interface Authorizer{boolean ok(String provider,String recovery,String authRef,Instant at);}public static final class Conflict extends RuntimeException{Conflict(String m){super(m);}}public static final class UnknownEffect extends RuntimeException{}public static final class Unauthorized extends RuntimeException{}
}
