package org.systemmaster.continuity;

import java.io.*;import java.nio.channels.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.*;import java.time.Instant;import java.util.*;import java.util.Base64;

final class Gwp007Store {
 private final Path file; private static final Base64.Encoder E=Base64.getUrlEncoder().withoutPadding(); private static final Base64.Decoder D=Base64.getUrlDecoder();
 Gwp007Store(Path dir){try{Files.createDirectories(dir);file=dir.resolve("gwp007-effects.journal");if(!Files.exists(file))Files.createFile(file);snapshot();}catch(IOException e){throw new IllegalStateException(e);}}
 Snapshot snapshot(){return withLock(false,s->s);}
 <T>T transact(Tx<T> tx){return withLock(true,s->{Decision<T>d=tx.apply(s);if(d.line()!=null){try{append(d.line());}catch(IOException e){throw new IllegalStateException(e);}}return d.value();});}
 private <T>T withLock(boolean write,Fn<T> fn){try(FileChannel ch=FileChannel.open(file,StandardOpenOption.READ,StandardOpenOption.WRITE);FileLock l=ch.lock()){Snapshot s=replay();return fn.apply(s);}catch(IOException e){throw new IllegalStateException(e);}}
 private void append(String body)throws IOException{String line=body+"\t"+sha256(body)+"\n";try(FileChannel ch=FileChannel.open(file,StandardOpenOption.APPEND,StandardOpenOption.WRITE)){ch.write(StandardCharsets.UTF_8.encode(line));ch.force(true);}}
 private Snapshot replay()throws IOException{Map<String,ExternalEffectRecoveryItem> items=new HashMap<>();Map<String,String> keys=new HashMap<>();Map<String,ReconciliationReceipt> receipts=new HashMap<>();for(String line:Files.readAllLines(file,StandardCharsets.UTF_8)){if(line.isBlank())continue;int p=line.lastIndexOf('\t');if(p<1)throw new IntegrityException("truncated journal");String b=line.substring(0,p),h=line.substring(p+1);if(!sha256(b).equals(h))throw new IntegrityException("checksum mismatch");String[]f=b.split("\\|",-1);if(f[0].equals("I")){ExternalEffectRecoveryItem i=item(f,1);items.put(i.effectId(),i);if(i.idempotencyKey()!=null)keys.put(i.idempotencyKey(),i.effectId());}else if(f[0].equals("R")){ExternalEffectRecoveryItem i=item(f,1);items.put(i.effectId(),i);if(i.idempotencyKey()!=null)keys.put(i.idempotencyKey(),i.effectId());ReconciliationReceipt r=new ReconciliationReceipt(dec(f[12]),dec(f[13]),ExternalEffectRecoveryItem.State.valueOf(f[14]),Long.parseLong(f[15]),decN(f[16]),dec(f[17]),Instant.parse(f[18]));receipts.put(r.effectId()+"|"+r.observationDigest(),r);}else throw new IntegrityException("unknown frame");}return new Snapshot(Map.copyOf(items),Map.copyOf(keys),Map.copyOf(receipts));}
 static String itemFrame(ExternalEffectRecoveryItem i){return "I|"+encItem(i);}
 static String reconcileFrame(ExternalEffectRecoveryItem i,ReconciliationReceipt r){return "R|"+encItem(i)+"|"+enc(r.effectId())+"|"+enc(r.observationDigest())+"|"+r.resultingState()+"|"+r.itemVersion()+"|"+encN(r.externalReceiptRef())+"|"+enc(r.evidenceDigest())+"|"+r.recordedAt();}
 private static String encItem(ExternalEffectRecoveryItem i){return String.join("|",enc(i.effectId()),enc(i.workUnitId()),enc(i.operationDigest()),encN(i.idempotencyKey()),enc(i.providerRef()),i.state().name(),encN(i.externalReceiptRef()),i.lastQueryAt()==null?"":i.lastQueryAt().toString(),i.reconciliationPolicy().name(),enc(String.join("\u001f",i.evidenceRefs())),Long.toString(i.version()));}
 private static ExternalEffectRecoveryItem item(String[]f,int o){return new ExternalEffectRecoveryItem(dec(f[o]),dec(f[o+1]),dec(f[o+2]),decN(f[o+3]),dec(f[o+4]),ExternalEffectRecoveryItem.State.valueOf(f[o+5]),decN(f[o+6]),f[o+7].isEmpty()?null:Instant.parse(f[o+7]),ExternalEffectRecoveryItem.ReconciliationPolicy.valueOf(f[o+8]),split(dec(f[o+9])),Long.parseLong(f[o+10]));}
 private static List<String> split(String s){return s.isEmpty()?List.of():List.of(s.split("\\u001f",-1));}
 static String sha256(String s){try{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private static String enc(String s){return E.encodeToString(s.getBytes(StandardCharsets.UTF_8));} private static String dec(String s){return new String(D.decode(s),StandardCharsets.UTF_8);} private static String encN(String s){return s==null?"":enc(s);} private static String decN(String s){return s.isEmpty()?null:dec(s);}
 Path file(){return file;} record Snapshot(Map<String,ExternalEffectRecoveryItem>items,Map<String,String>idempotencyKeys,Map<String,ReconciliationReceipt>receipts){} record Decision<T>(T value,String line){} interface Tx<T>{Decision<T>apply(Snapshot s);} interface Fn<T>{T apply(Snapshot s);} static final class IntegrityException extends RuntimeException{IntegrityException(String m){super(m);}}
}
