package org.systemmaster.tools.ocr;
import javax.imageio.ImageIO;import java.awt.Color;import java.awt.Graphics2D;import java.awt.image.BufferedImage;import java.io.*;import java.util.*;
public final class OcrFullLanePortableTests {static int n;public static void main(String[]a)throws Exception{
 check(OcrFullLaneCapabilities.all().size()==189,"189 capabilities");check(OcrSemanticActions.all().size()==54,"54 semantic actions");check(OcrFullLaneCapabilities.all().stream().noneMatch(d->d.disposition().isBlank()),"all dispositions");
 BufferedImage img=new BufferedImage(80,40,BufferedImage.TYPE_INT_RGB);Graphics2D g=img.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,80,40);g.setColor(Color.BLACK);g.drawString("ABC",10,20);g.dispose();ByteArrayOutputStream bo=new ByteArrayOutputStream();ImageIO.write(img,"png",bo);byte[] src=bo.toByteArray();OcrFullLaneEngine e=new OcrFullLaneEngine();var si=e.inspect(src);check(si.imageReadable()&&si.width()==80&&si.height()==40,"source inspect");byte[] bw=e.grayscaleThreshold(src,128);check(e.inspect(bw).imageReadable(),"threshold output readable");byte[] rot=e.rotate90(src);check(e.inspect(rot).width()==40&&e.inspect(rot).height()==80,"rotate90");
 OcrEnginePort port=new OcrEnginePort(){public Identity identity(){return new Identity("FAKE-OCR","1.0","abc",Set.of("ocr.run.recognize"),true,false);}public Result recognize(byte[] image,String action,Map<String,String> options){return new Result(List.of(new Region("r2","World",10,20,20,8,.72,"TEXT",Map.of()),new Region("r1","Hello",5,5,20,8,.98,"TEXT",Map.of())),Map.of("language","en"),List.of());}};
 OcrFullLaneService svc=new OcrFullLaneService();var graph=svc.recognize(port,src,"ocr.run.recognize",Map.of());check(graph.regions().size()==2,"regions normalized");check(graph.readingOrder().equals(List.of("r1","r2")),"reading order");check(graph.regions().get(0).confidenceState().equals("HIGH")&&graph.regions().get(1).confidenceState().equals("LOW"),"confidence states");var corrected=e.correct(graph,"r2","Earth","human-1");check(corrected.regions().get(1).text().equals("Earth")&&corrected.regions().get(1).confidenceState().equals("HUMAN_CORRECTED"),"human correction state");check(e.differential(graph,corrected).stream().anyMatch(x->x.startsWith("TEXT_MISMATCH")),"differential text mismatch");var receipt=svc.receipt(port,src,"ocr.run.recognize",graph);check(receipt.engineId().equals("FAKE-OCR")&&receipt.regionCount()==2,"receipt identity");
 boolean rejected=false;try{svc.recognize(new OcrEnginePort(){public Identity identity(){return new Identity("BAD","1","d",Set.of("ocr.run.recognize"),false,false);}public Result recognize(byte[]i,String a,Map<String,String>o){throw new AssertionError();}},src,"ocr.run.recognize",Map.of());}catch(IllegalStateException ex){rejected=true;}check(rejected,"unhealthy OCR rejected");
 System.out.println("OCR_FULL_LANE_PORTABLE_PASS assertions="+n+" portable="+OcrFullLaneCapabilities.portable()+" delegated="+OcrFullLaneCapabilities.delegated()+" pending="+OcrFullLaneCapabilities.pending());}
 static void check(boolean c,String m){n++;if(!c)throw new AssertionError(m);} }
