package org.systemmaster.tools.docx;

import org.systemmaster.tools.common.OoxmlPackageSupport;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;

/** Typed DOCX T05 image styling, DrawingML shape/group and chart authority. */
public final class DocxDrawingChartMasteryEngine {
    private static final String W="http://schemas.openxmlformats.org/wordprocessingml/2006/main";
    private static final String R="http://schemas.openxmlformats.org/officeDocument/2006/relationships";
    private static final String REL="http://schemas.openxmlformats.org/package/2006/relationships";
    private static final String CT="http://schemas.openxmlformats.org/package/2006/content-types";
    private static final String WP="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing";
    private static final String A="http://schemas.openxmlformats.org/drawingml/2006/main";
    private static final String PIC="http://schemas.openxmlformats.org/drawingml/2006/picture";
    private static final String WPS="http://schemas.microsoft.com/office/word/2010/wordprocessingShape";
    private static final String WPG="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup";
    private static final String C="http://schemas.openxmlformats.org/drawingml/2006/chart";
    private static final String IMAGE_REL="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image";
    private static final String CHART_REL="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart";

    public record Crop(int left, int top, int right, int bottom) {
        public Crop { for (int v:new int[]{left,top,right,bottom}) if(v<0||v>100000) throw new IllegalArgumentException("crop must be 0..100000"); }
        public static Crop none(){return new Crop(0,0,0,0);}
    }
    public record ImageStyle(Crop crop,String wrap,Long xEmu,Long yEmu,String horizontalRelativeFrom,String verticalRelativeFrom,String title,String altText,Boolean decorative){
        public ImageStyle {
            crop=Objects.requireNonNullElseGet(crop,Crop::none); wrap=clean(wrap);
            if(!wrap.isBlank()&&!List.of("square","tight","through","topAndBottom","none").contains(wrap)) throw new IllegalArgumentException("unsupported wrap");
            horizontalRelativeFrom=clean(horizontalRelativeFrom); verticalRelativeFrom=clean(verticalRelativeFrom);
            title=title==null?null:title.strip(); altText=altText==null?null:altText.strip();
        }
    }
    public record ImageStyleSnapshot(String locator,String mediaKind,String relationshipId,String targetPart,Crop crop,String placement,String wrap,long xEmu,long yEmu,String horizontalRelativeFrom,String verticalRelativeFrom,String title,String altText,boolean decorative){}
    public record SvgSpec(byte[] svg,long widthEmu,long heightEmu,String name,String title,String altText,boolean icon){
        public SvgSpec { svg=Objects.requireNonNull(svg,"svg").clone(); if(svg.length==0) throw new IllegalArgumentException("svg required"); if(widthEmu<=0||heightEmu<=0) throw new IllegalArgumentException("dimensions required"); name=clean(name).isBlank()?(icon?"Icon":"SVG"):clean(name); title=clean(title); altText=clean(altText); }
        @Override public byte[] svg(){return svg.clone();}
    }
    public record ShapeSpec(String preset,long widthEmu,long heightEmu,String fillHex,String lineHex,String text,String wordArtPreset){
        public ShapeSpec { preset=clean(preset).isBlank()?"rect":clean(preset); if(widthEmu<=0||heightEmu<=0) throw new IllegalArgumentException("shape dimensions required"); fillHex=color(fillHex,"D9EAF7"); lineHex=color(lineHex,"4F81BD"); text=Objects.requireNonNullElse(text,""); wordArtPreset=clean(wordArtPreset); }
    }
    public record ShapeSnapshot(String locator,String preset,String text,String fillHex,String lineHex,boolean textBox,String wordArtPreset,long widthEmu,long heightEmu){}
    public record GroupSpec(List<ShapeSpec> shapes,long widthEmu,long heightEmu){ public GroupSpec{shapes=List.copyOf(Objects.requireNonNullElse(shapes,List.of())); if(shapes.isEmpty())throw new IllegalArgumentException("group requires shapes"); if(widthEmu<=0||heightEmu<=0)throw new IllegalArgumentException("group dimensions required");}}
    public record GroupSnapshot(String locator,int childCount,long widthEmu,long heightEmu){}
    public record ChartSeries(String name,List<String> categories,List<Double> values){ public ChartSeries{name=clean(name);categories=List.copyOf(Objects.requireNonNullElse(categories,List.of()));values=List.copyOf(Objects.requireNonNullElse(values,List.of()));if(categories.isEmpty()||categories.size()!=values.size())throw new IllegalArgumentException("chart categories/values must align");for(Double v:values)Objects.requireNonNull(v,"chart value");}}
    public record ChartSpec(String type,String title,long widthEmu,long heightEmu,List<ChartSeries> series){ public ChartSpec{type=clean(type).toLowerCase(Locale.ROOT);if(!List.of("bar","line","pie").contains(type))throw new IllegalArgumentException("unsupported chart type");title=clean(title);if(widthEmu<=0||heightEmu<=0)throw new IllegalArgumentException("chart dimensions required");series=List.copyOf(Objects.requireNonNullElse(series,List.of()));if(series.isEmpty())throw new IllegalArgumentException("chart requires series");}}
    public record ChartSnapshot(String locator,String relationshipId,String chartPart,String type,String title,List<ChartSeries> series){}

    public List<ImageStyleSnapshot> readImageStyles(byte[] bytes) throws IOException {
        Map<String,byte[]> parts=requireDocx(bytes); Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml")); Document rels=documentRelationships(parts); ArrayList<ImageStyleSnapshot> out=new ArrayList<>();
        for(Element p:bodyParagraphs(doc)){ NodeList drawings=p.getElementsByTagNameNS(W,"drawing"); int pIndex=paragraphIndex(doc,p); int image=0; for(int i=0;i<drawings.getLength();i++){Element drawing=(Element)drawings.item(i);NodeList blips=drawing.getElementsByTagNameNS(A,"blip");for(int j=0;j<blips.getLength();j++){image++;Element blip=(Element)blips.item(j);String rid=blip.getAttributeNS(R,"embed");String target=normalizeTarget(relationshipTarget(rels,rid));Element container=firstContainer(drawing);Element docPr=container==null?null:first(container.getElementsByTagNameNS(WP,"docPr"));Element srcRect=first(drawing.getElementsByTagNameNS(A,"srcRect"));Crop crop=srcRect==null?Crop.none():new Crop(intAttr(srcRect,"l"),intAttr(srcRect,"t"),intAttr(srcRect,"r"),intAttr(srcRect,"b"));String placement=container==null?"unknown":container.getLocalName();String wrap=wrap(container);long x=position(container,"positionH");long y=position(container,"positionV");String h=relative(container,"positionH");String v=relative(container,"positionV");String title=docPr==null?"":docPr.getAttribute("title");String alt=docPr==null?"":docPr.getAttribute("descr");boolean decorative=docPr!=null&&("1".equals(docPr.getAttribute("decorative"))||"true".equalsIgnoreCase(docPr.getAttribute("decorative")));String kind=target.toLowerCase(Locale.ROOT).endsWith(".svg")?((docPr!=null&&docPr.getAttribute("name").startsWith("Icon:"))?"icon":"svg"):"raster";out.add(new ImageStyleSnapshot("body/p:"+pIndex+"/drawing-image:"+image,kind,rid,target,crop,placement,wrap,x,y,h,v,title,alt,decorative));}}
        }
        return List.copyOf(out);
    }

    public byte[] styleImage(byte[] bytes,String locator,ImageStyle style) throws IOException {
        Objects.requireNonNull(style,"style"); Map<String,byte[]> parts=requireDocx(bytes); Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml")); Element drawing=locateDrawing(doc,locator,"drawing-image"); Element fill=first(drawing.getElementsByTagNameNS(PIC,"blipFill")); if(fill==null) throw new IllegalArgumentException("target is not a picture"); Element src=first(fill.getElementsByTagNameNS(A,"srcRect")); if(src==null){src=doc.createElementNS(A,"a:srcRect");Node blip=first(fill.getElementsByTagNameNS(A,"blip"));Node next=blip==null?fill.getFirstChild():blip.getNextSibling();if(next==null)fill.appendChild(src);else fill.insertBefore(src,next);}src.setAttribute("l",Integer.toString(style.crop().left()));src.setAttribute("t",Integer.toString(style.crop().top()));src.setAttribute("r",Integer.toString(style.crop().right()));src.setAttribute("b",Integer.toString(style.crop().bottom()));Element container=firstContainer(drawing);if(container==null)throw new IllegalArgumentException("picture missing placement container");if(!style.wrap().isBlank()){if(!"anchor".equals(container.getLocalName())) throw new IllegalArgumentException("wrap requires floating anchor");replaceWrap(doc,container,style.wrap());}if(style.xEmu()!=null||style.yEmu()!=null){if(!"anchor".equals(container.getLocalName()))throw new IllegalArgumentException("position requires floating anchor");if(style.xEmu()!=null)setPosition(doc,container,"positionH",style.horizontalRelativeFrom(),style.xEmu());if(style.yEmu()!=null)setPosition(doc,container,"positionV",style.verticalRelativeFrom(),style.yEmu());}Element dp=first(container.getElementsByTagNameNS(WP,"docPr"));if(dp!=null){if(style.title()!=null)dp.setAttribute("title",style.title());if(style.altText()!=null)dp.setAttribute("descr",style.altText());if(style.decorative()!=null)dp.setAttribute("decorative",Boolean.toString(style.decorative()));}parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));return OoxmlPackageSupport.write(parts);
    }

    public byte[] insertSvg(byte[] bytes,String paragraphLocator,SvgSpec spec) throws IOException { return insertSvgLike(bytes,paragraphLocator,spec); }
    public byte[] insertIcon(byte[] bytes,String paragraphLocator,SvgSpec spec) throws IOException { if(!spec.icon()) spec=new SvgSpec(spec.svg(),spec.widthEmu(),spec.heightEmu(),spec.name(),spec.title(),spec.altText(),true); return insertSvgLike(bytes,paragraphLocator,spec); }
    public byte[] replaceSvgBytes(byte[] bytes,String locator,byte[] svg,boolean icon)throws IOException{Objects.requireNonNull(svg,"svg");if(svg.length==0)throw new IllegalArgumentException("svg required");Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Document rels=documentRelationships(parts);Element drawing=locateDrawing(doc,locator,"drawing-image");Element blip=first(drawing.getElementsByTagNameNS(A,"blip"));if(blip==null)throw new IllegalArgumentException("image blip missing");String rid=blip.getAttributeNS(R,"embed");String target=normalizeTarget(relationshipTarget(rels,rid));if(!target.toLowerCase(Locale.ROOT).endsWith(".svg"))throw new IllegalArgumentException("target is not SVG media");if(countTargetUses(doc,rels,target)>1){String newPart=nextPart(parts,"word/media/t05graphic","svg");parts.put(newPart,svg.clone());String newRid=addRelationship(rels,IMAGE_REL,relativeWordTarget(newPart));blip.setAttributeNS(R,"r:embed",newRid);}else{parts.put(target,svg.clone());}Element container=firstContainer(drawing);Element dp=container==null?null:first(container.getElementsByTagNameNS(WP,"docPr"));if(icon&&dp!=null&&!dp.getAttribute("name").startsWith("Icon:"))dp.setAttribute("name","Icon:"+dp.getAttribute("name"));ensureDefaultContentType(parts,"svg","image/svg+xml");parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));parts.put("word/_rels/document.xml.rels",OoxmlPackageSupport.serialize(rels));return OoxmlPackageSupport.write(parts);}

    private byte[] insertSvgLike(byte[] bytes,String paragraphLocator,SvgSpec spec) throws IOException {
        Map<String,byte[]> parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Document rels=documentRelationships(parts);String part=nextPart(parts,"word/media/t05graphic","svg");parts.put(part,spec.svg());ensureDefaultContentType(parts,"svg","image/svg+xml");String rid=addRelationship(rels,IMAGE_REL,relativeWordTarget(part));Element p=locateParagraph(doc,paragraphLocator);p.appendChild(createPictureRun(doc,rid,spec.widthEmu(),spec.heightEmu(),spec.icon()?"Icon:"+spec.name():spec.name(),spec.title(),spec.altText()));parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));parts.put("word/_rels/document.xml.rels",OoxmlPackageSupport.serialize(rels));return OoxmlPackageSupport.write(parts);
    }

    public List<ShapeSnapshot> readShapes(byte[] bytes) throws IOException {
        Map<String,byte[]> parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));ArrayList<ShapeSnapshot> out=new ArrayList<>();int n=0;NodeList shapes=doc.getElementsByTagNameNS(WPS,"wsp");for(int i=0;i<shapes.getLength();i++){Element s=(Element)shapes.item(i);if(hasAncestor(s,WPG,"wgp"))continue;n++;Element geom=first(s.getElementsByTagNameNS(A,"prstGeom"));String preset=geom==null?"":geom.getAttribute("prst");Element fill=first(s.getElementsByTagNameNS(A,"solidFill"));String fillHex=colorValue(fill);Element ln=first(s.getElementsByTagNameNS(A,"ln"));String lineHex=colorValue(ln);String text=textContent(s,W,"t");Element warp=first(s.getElementsByTagNameNS(A,"prstTxWarp"));Element ext=first(s.getElementsByTagNameNS(A,"ext"));long w=ext==null?0:longAttr(ext,"cx");long h=ext==null?0:longAttr(ext,"cy");out.add(new ShapeSnapshot("drawing-shape:"+n,preset,text,fillHex,lineHex,first(s.getElementsByTagNameNS(WPS,"txbx"))!=null,warp==null?"":warp.getAttribute("prst"),w,h));}return List.copyOf(out);
    }

    public byte[] insertShape(byte[] bytes,String paragraphLocator,ShapeSpec spec) throws IOException{return insertShapeInternal(bytes,paragraphLocator,spec,false);}
    public byte[] insertTextBox(byte[] bytes,String paragraphLocator,ShapeSpec spec) throws IOException{return insertShapeInternal(bytes,paragraphLocator,spec,true);}
    public byte[] insertWordArt(byte[] bytes,String paragraphLocator,ShapeSpec spec) throws IOException { if(spec.wordArtPreset().isBlank()) spec=new ShapeSpec(spec.preset(),spec.widthEmu(),spec.heightEmu(),spec.fillHex(),spec.lineHex(),spec.text(),"textArchUp"); return insertShapeInternal(bytes,paragraphLocator,spec,true); }
    private byte[] insertShapeInternal(byte[] bytes,String paragraphLocator,ShapeSpec spec,boolean textBox)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Element p=locateParagraph(doc,paragraphLocator);p.appendChild(createShapeRun(doc,spec,textBox));parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));return OoxmlPackageSupport.write(parts);}
    public byte[] editShape(byte[] bytes,int oneBasedIndex,ShapeSpec spec,boolean textBox)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Element shape=nthStandaloneShape(doc,oneBasedIndex);applyShape(shape,spec,textBox);parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));return OoxmlPackageSupport.write(parts);}
    public byte[] editShape(byte[] bytes,String locator,ShapeSpec spec,boolean textBox)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Element shape=locateStandaloneShape(doc,locator);applyShape(shape,spec,textBox);parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));return OoxmlPackageSupport.write(parts);}

    public byte[] insertGroup(byte[] bytes,String paragraphLocator,GroupSpec spec)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Element p=locateParagraph(doc,paragraphLocator);p.appendChild(createGroupRun(doc,spec));parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));return OoxmlPackageSupport.write(parts);}
    public List<GroupSnapshot> readGroups(byte[] bytes)throws IOException{Document doc=OoxmlPackageSupport.parseXml(requireDocx(bytes).get("word/document.xml"));ArrayList<GroupSnapshot>out=new ArrayList<>();NodeList groups=doc.getElementsByTagNameNS(WPG,"wgp");for(int i=0;i<groups.getLength();i++){Element g=(Element)groups.item(i);Element ext=first(g.getElementsByTagNameNS(A,"ext"));out.add(new GroupSnapshot("drawing-group:"+(i+1),g.getElementsByTagNameNS(WPS,"wsp").getLength(),ext==null?0:longAttr(ext,"cx"),ext==null?0:longAttr(ext,"cy")));}return List.copyOf(out);}
    public byte[] replaceGroup(byte[] bytes,int oneBasedIndex,GroupSpec spec)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));NodeList groups=doc.getElementsByTagNameNS(WPG,"wgp");if(oneBasedIndex<1||oneBasedIndex>groups.getLength())throw new IllegalArgumentException("group index out of range");Element old=(Element)groups.item(oneBasedIndex-1);Element fresh=groupElement(doc,spec);old.getParentNode().replaceChild(fresh,old);parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));return OoxmlPackageSupport.write(parts);}
    public byte[] replaceGroup(byte[] bytes,String locator,GroupSpec spec)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Element old=locateGroup(doc,locator);Element fresh=groupElement(doc,spec);old.getParentNode().replaceChild(fresh,old);parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));return OoxmlPackageSupport.write(parts);}

    public byte[] insertChart(byte[] bytes,String paragraphLocator,ChartSpec spec)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Document rels=documentRelationships(parts);String chartPart=nextPart(parts,"word/charts/chart","xml");parts.put(chartPart,chartXml(spec));ensureOverrideContentType(parts,"/"+chartPart,"application/vnd.openxmlformats-officedocument.drawingml.chart+xml");String rid=addRelationship(rels,CHART_REL,relativeWordTarget(chartPart));Element p=locateParagraph(doc,paragraphLocator);p.appendChild(createChartRun(doc,rid,spec));parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));parts.put("word/_rels/document.xml.rels",OoxmlPackageSupport.serialize(rels));return OoxmlPackageSupport.write(parts);}
    public List<ChartSnapshot> readCharts(byte[] bytes)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Document rels=documentRelationships(parts);ArrayList<ChartSnapshot>out=new ArrayList<>();for(Element p:bodyParagraphs(doc)){int pIndex=paragraphIndex(doc,p);NodeList charts=p.getElementsByTagNameNS(C,"chart");for(int i=0;i<charts.getLength();i++){Element ref=(Element)charts.item(i);String rid=ref.getAttributeNS(R,"id");String part=normalizeTarget(relationshipTarget(rels,rid));if(!parts.containsKey(part))throw new IOException("chart relationship target missing: "+part);ChartSpec spec=parseChart(parts.get(part));out.add(new ChartSnapshot("body/p:"+pIndex+"/chart:"+(i+1),rid,part,spec.type(),spec.title(),spec.series()));}}return List.copyOf(out);}
    public byte[] editChart(byte[] bytes,String locator,ChartSpec spec)throws IOException{Map<String,byte[]>parts=requireDocx(bytes);Document doc=OoxmlPackageSupport.parseXml(parts.get("word/document.xml"));Document rels=documentRelationships(parts);Element chart=locateChart(doc,locator);String rid=chart.getAttributeNS(R,"id");String part=normalizeTarget(relationshipTarget(rels,rid));if(!parts.containsKey(part))throw new IOException("chart part missing");if(countChartTargetUses(doc,rels,part)>1){String newPart=nextPart(parts,"word/charts/chart","xml");parts.put(newPart,parts.get(part).clone());cloneChartRelationships(parts,part,newPart);ensureOverrideContentType(parts,"/"+newPart,"application/vnd.openxmlformats-officedocument.drawingml.chart+xml");String newRid=addRelationship(rels,CHART_REL,relativeWordTarget(newPart));chart.setAttributeNS(R,"r:id",newRid);part=newPart;}parts.put(part,chartXml(spec));Element drawing=(Element)chart.getParentNode().getParentNode().getParentNode();Element extent=first(drawing.getElementsByTagNameNS(WP,"extent"));if(extent!=null){extent.setAttribute("cx",Long.toString(spec.widthEmu()));extent.setAttribute("cy",Long.toString(spec.heightEmu()));}parts.put("word/document.xml",OoxmlPackageSupport.serialize(doc));parts.put("word/_rels/document.xml.rels",OoxmlPackageSupport.serialize(rels));return OoxmlPackageSupport.write(parts);}

    private static ChartSpec parseChart(byte[] bytes)throws IOException{Document d=OoxmlPackageSupport.parseXml(bytes);String type=first(d.getElementsByTagNameNS(C,"lineChart"))!=null?"line":first(d.getElementsByTagNameNS(C,"pieChart"))!=null?"pie":"bar";String title="";Element titleEl=first(d.getElementsByTagNameNS(C,"title"));if(titleEl!=null)title=textContent(titleEl,A,"t");Element plot=first(d.getElementsByTagNameNS(C,type+"Chart"));ArrayList<ChartSeries> series=new ArrayList<>();if(plot!=null){NodeList ns=plot.getElementsByTagNameNS(C,"ser");for(int i=0;i<ns.getLength();i++){Element s=(Element)ns.item(i);String name=textContent(first(s.getElementsByTagNameNS(C,"tx")),C,"v");ArrayList<String>cats=new ArrayList<>();Element cat=first(s.getElementsByTagNameNS(C,"cat"));if(cat!=null){NodeList pts=cat.getElementsByTagNameNS(C,"pt");for(int j=0;j<pts.getLength();j++)cats.add(textContent((Element)pts.item(j),C,"v"));}ArrayList<Double>vals=new ArrayList<>();Element val=first(s.getElementsByTagNameNS(C,"val"));if(val!=null){NodeList pts=val.getElementsByTagNameNS(C,"pt");for(int j=0;j<pts.getLength();j++){String v=textContent((Element)pts.item(j),C,"v");vals.add(Double.valueOf(v));}}if(!cats.isEmpty()&&cats.size()==vals.size())series.add(new ChartSeries(name,cats,vals));}}return new ChartSpec(type,title,9144000,5143500,series.isEmpty()?List.of(new ChartSeries("Series",List.of("Category"),List.of(0.0))):series);}

    private static byte[] chartXml(ChartSpec spec)throws IOException{Document d=newDocument("c:chartSpace",C);Element root=d.getDocumentElement();root.setAttribute("xmlns:a",A);root.setAttribute("xmlns:r",R);Element chart=append(d,root,C,"c:chart");if(!spec.title().isBlank()){Element title=append(d,chart,C,"c:title");Element tx=append(d,title,C,"c:tx");Element rich=append(d,tx,C,"c:rich");append(d,rich,A,"a:bodyPr");append(d,rich,A,"a:lstStyle");Element p=append(d,rich,A,"a:p");Element r=append(d,p,A,"a:r");append(d,r,A,"a:rPr");appendText(d,r,A,"a:t",spec.title());}Element plot=append(d,chart,C,"c:plotArea");append(d,plot,C,"c:layout");String local=spec.type()+"Chart";Element type=append(d,plot,C,"c:"+local);if("bar".equals(spec.type())){Element dir=append(d,type,C,"c:barDir");dir.setAttribute("val","col");Element grouping=append(d,type,C,"c:grouping");grouping.setAttribute("val","clustered");}for(int i=0;i<spec.series().size();i++){ChartSeries s=spec.series().get(i);Element ser=append(d,type,C,"c:ser");val(d,ser,"idx",i);val(d,ser,"order",i);Element tx=append(d,ser,C,"c:tx");appendText(d,tx,C,"c:v",s.name());Element cat=append(d,ser,C,"c:cat");Element strLit=append(d,cat,C,"c:strLit");val(d,strLit,"ptCount",s.categories().size());for(int j=0;j<s.categories().size();j++){Element pt=append(d,strLit,C,"c:pt");pt.setAttribute("idx",Integer.toString(j));appendText(d,pt,C,"c:v",s.categories().get(j));}Element vals=append(d,ser,C,"c:val");Element numLit=append(d,vals,C,"c:numLit");Element fmt=append(d,numLit,C,"c:formatCode");fmt.setTextContent("General");val(d,numLit,"ptCount",s.values().size());for(int j=0;j<s.values().size();j++){Element pt=append(d,numLit,C,"c:pt");pt.setAttribute("idx",Integer.toString(j));appendText(d,pt,C,"c:v",Double.toString(s.values().get(j)));}}
        if(!"pie".equals(spec.type())){val(d,type,"axId",123456);val(d,type,"axId",654321);Element catAx=append(d,plot,C,"c:catAx");val(d,catAx,"axId",123456);Element scaling=append(d,catAx,C,"c:scaling");Element orient=append(d,scaling,C,"c:orientation");orient.setAttribute("val","minMax");Element pos=append(d,catAx,C,"c:axPos");pos.setAttribute("val","b");val(d,catAx,"crossAx",654321);Element crosses=append(d,catAx,C,"c:crosses");crosses.setAttribute("val","autoZero");Element valAx=append(d,plot,C,"c:valAx");val(d,valAx,"axId",654321);scaling=append(d,valAx,C,"c:scaling");orient=append(d,scaling,C,"c:orientation");orient.setAttribute("val","minMax");pos=append(d,valAx,C,"c:axPos");pos.setAttribute("val","l");val(d,valAx,"crossAx",123456);crosses=append(d,valAx,C,"c:crosses");crosses.setAttribute("val","autoZero");}
        Element legend=append(d,chart,C,"c:legend");Element legendPos=append(d,legend,C,"c:legendPos");legendPos.setAttribute("val","r");Element plotVisOnly=append(d,chart,C,"c:plotVisOnly");plotVisOnly.setAttribute("val","1");return OoxmlPackageSupport.serialize(d);}

    private static Element createPictureRun(Document d,String rid,long w,long h,String name,String title,String alt){Element run=d.createElementNS(W,"w:r");Element drawing=d.createElementNS(W,"w:drawing");run.appendChild(drawing);Element in=d.createElementNS(WP,"wp:inline");drawing.appendChild(in);Element ext=d.createElementNS(WP,"wp:extent");ext.setAttribute("cx",Long.toString(w));ext.setAttribute("cy",Long.toString(h));in.appendChild(ext);Element dp=d.createElementNS(WP,"wp:docPr");dp.setAttribute("id",Integer.toString(nextDocPrId(d)));dp.setAttribute("name",name);if(!title.isBlank())dp.setAttribute("title",title);if(!alt.isBlank())dp.setAttribute("descr",alt);in.appendChild(dp);in.appendChild(d.createElementNS(WP,"wp:cNvGraphicFramePr"));Element g=d.createElementNS(A,"a:graphic");in.appendChild(g);Element gd=d.createElementNS(A,"a:graphicData");gd.setAttribute("uri",PIC);g.appendChild(gd);Element pic=d.createElementNS(PIC,"pic:pic");gd.appendChild(pic);Element nv=d.createElementNS(PIC,"pic:nvPicPr");pic.appendChild(nv);Element cnp=d.createElementNS(PIC,"pic:cNvPr");cnp.setAttribute("id","0");cnp.setAttribute("name",name);if(!alt.isBlank())cnp.setAttribute("descr",alt);nv.appendChild(cnp);nv.appendChild(d.createElementNS(PIC,"pic:cNvPicPr"));Element bf=d.createElementNS(PIC,"pic:blipFill");pic.appendChild(bf);Element blip=d.createElementNS(A,"a:blip");blip.setAttributeNS(R,"r:embed",rid);bf.appendChild(blip);Element stretch=d.createElementNS(A,"a:stretch");stretch.appendChild(d.createElementNS(A,"a:fillRect"));bf.appendChild(stretch);Element sp=d.createElementNS(PIC,"pic:spPr");pic.appendChild(sp);Element x=d.createElementNS(A,"a:xfrm");Element off=d.createElementNS(A,"a:off");off.setAttribute("x","0");off.setAttribute("y","0");x.appendChild(off);Element ex=d.createElementNS(A,"a:ext");ex.setAttribute("cx",Long.toString(w));ex.setAttribute("cy",Long.toString(h));x.appendChild(ex);sp.appendChild(x);Element geom=d.createElementNS(A,"a:prstGeom");geom.setAttribute("prst","rect");geom.appendChild(d.createElementNS(A,"a:avLst"));sp.appendChild(geom);return run;}
    private static Element createShapeRun(Document d,ShapeSpec s,boolean textBox){Element run=d.createElementNS(W,"w:r");Element drawing=d.createElementNS(W,"w:drawing");run.appendChild(drawing);Element in=d.createElementNS(WP,"wp:inline");drawing.appendChild(in);Element ext=d.createElementNS(WP,"wp:extent");ext.setAttribute("cx",Long.toString(s.widthEmu()));ext.setAttribute("cy",Long.toString(s.heightEmu()));in.appendChild(ext);Element dp=d.createElementNS(WP,"wp:docPr");dp.setAttribute("id",Integer.toString(nextDocPrId(d)));dp.setAttribute("name",textBox?"Text Box":"Shape");in.appendChild(dp);in.appendChild(d.createElementNS(WP,"wp:cNvGraphicFramePr"));Element g=d.createElementNS(A,"a:graphic");in.appendChild(g);Element gd=d.createElementNS(A,"a:graphicData");gd.setAttribute("uri",WPS);g.appendChild(gd);Element wsp=d.createElementNS(WPS,"wps:wsp");gd.appendChild(wsp);applyShape(wsp,s,textBox);return run;}
    private static void applyShape(Element wsp,ShapeSpec s,boolean textBox){Document d=wsp.getOwnerDocument();while(wsp.hasChildNodes())wsp.removeChild(wsp.getFirstChild());Element cNv=d.createElementNS(WPS,"wps:cNvSpPr");if(textBox)cNv.setAttribute("txBox","1");wsp.appendChild(cNv);Element spPr=d.createElementNS(WPS,"wps:spPr");wsp.appendChild(spPr);Element x=d.createElementNS(A,"a:xfrm");Element off=d.createElementNS(A,"a:off");off.setAttribute("x","0");off.setAttribute("y","0");x.appendChild(off);Element ext=d.createElementNS(A,"a:ext");ext.setAttribute("cx",Long.toString(s.widthEmu()));ext.setAttribute("cy",Long.toString(s.heightEmu()));x.appendChild(ext);spPr.appendChild(x);Element geom=d.createElementNS(A,"a:prstGeom");geom.setAttribute("prst",s.preset());geom.appendChild(d.createElementNS(A,"a:avLst"));spPr.appendChild(geom);appendColor(d,spPr,"a:solidFill",s.fillHex());Element ln=d.createElementNS(A,"a:ln");spPr.appendChild(ln);appendColor(d,ln,"a:solidFill",s.lineHex());Element txbx=d.createElementNS(WPS,"wps:txbx");wsp.appendChild(txbx);Element content=d.createElementNS(W,"w:txbxContent");txbx.appendChild(content);Element p=d.createElementNS(W,"w:p");content.appendChild(p);Element r=d.createElementNS(W,"w:r");p.appendChild(r);Element t=d.createElementNS(W,"w:t");t.setTextContent(s.text());r.appendChild(t);Element body=d.createElementNS(WPS,"wps:bodyPr");if(!s.wordArtPreset().isBlank()){Element warp=d.createElementNS(A,"a:prstTxWarp");warp.setAttribute("prst",s.wordArtPreset());warp.appendChild(d.createElementNS(A,"a:avLst"));body.appendChild(warp);}wsp.appendChild(body);}
    private static Element createGroupRun(Document d,GroupSpec spec){Element run=d.createElementNS(W,"w:r");Element drawing=d.createElementNS(W,"w:drawing");run.appendChild(drawing);Element in=d.createElementNS(WP,"wp:inline");drawing.appendChild(in);Element ext=d.createElementNS(WP,"wp:extent");ext.setAttribute("cx",Long.toString(spec.widthEmu()));ext.setAttribute("cy",Long.toString(spec.heightEmu()));in.appendChild(ext);Element dp=d.createElementNS(WP,"wp:docPr");dp.setAttribute("id",Integer.toString(nextDocPrId(d)));dp.setAttribute("name","Drawing Group");in.appendChild(dp);in.appendChild(d.createElementNS(WP,"wp:cNvGraphicFramePr"));Element g=d.createElementNS(A,"a:graphic");in.appendChild(g);Element gd=d.createElementNS(A,"a:graphicData");gd.setAttribute("uri",WPG);g.appendChild(gd);gd.appendChild(groupElement(d,spec));return run;}
    private static Element groupElement(Document d,GroupSpec spec){Element grp=d.createElementNS(WPG,"wpg:wgp");grp.appendChild(d.createElementNS(WPG,"wpg:cNvGrpSpPr"));Element gp=d.createElementNS(WPG,"wpg:grpSpPr");grp.appendChild(gp);Element x=d.createElementNS(A,"a:xfrm");gp.appendChild(x);for(String name:List.of("off","chOff")){Element e=d.createElementNS(A,"a:"+name);e.setAttribute("x","0");e.setAttribute("y","0");x.appendChild(e);}for(String name:List.of("ext","chExt")){Element e=d.createElementNS(A,"a:"+name);e.setAttribute("cx",Long.toString(spec.widthEmu()));e.setAttribute("cy",Long.toString(spec.heightEmu()));x.appendChild(e);}for(ShapeSpec s:spec.shapes()){Element wsp=d.createElementNS(WPS,"wps:wsp");applyShape(wsp,s,false);grp.appendChild(wsp);}return grp;}
    private static Element createChartRun(Document d,String rid,ChartSpec spec){Element run=d.createElementNS(W,"w:r");Element drawing=d.createElementNS(W,"w:drawing");run.appendChild(drawing);Element in=d.createElementNS(WP,"wp:inline");drawing.appendChild(in);Element ext=d.createElementNS(WP,"wp:extent");ext.setAttribute("cx",Long.toString(spec.widthEmu()));ext.setAttribute("cy",Long.toString(spec.heightEmu()));in.appendChild(ext);Element dp=d.createElementNS(WP,"wp:docPr");dp.setAttribute("id",Integer.toString(nextDocPrId(d)));dp.setAttribute("name","Chart");dp.setAttribute("title",spec.title());in.appendChild(dp);in.appendChild(d.createElementNS(WP,"wp:cNvGraphicFramePr"));Element g=d.createElementNS(A,"a:graphic");in.appendChild(g);Element gd=d.createElementNS(A,"a:graphicData");gd.setAttribute("uri",C);g.appendChild(gd);Element c=d.createElementNS(C,"c:chart");c.setAttributeNS(R,"r:id",rid);gd.appendChild(c);return run;}

    private static Map<String,byte[]> requireDocx(byte[] bytes)throws IOException{Map<String,byte[]>p=OoxmlPackageSupport.read(bytes);if(!p.containsKey("word/document.xml")||!p.containsKey("[Content_Types].xml"))throw new IOException("not a DOCX package");return new LinkedHashMap<>(p);}    
    private static Document documentRelationships(Map<String,byte[]>parts)throws IOException{byte[]b=parts.get("word/_rels/document.xml.rels");if(b!=null)return OoxmlPackageSupport.parseXml(b);return OoxmlPackageSupport.parseXml(("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\""+REL+"\"/>").getBytes(StandardCharsets.UTF_8));}
    private static String addRelationship(Document rels,String type,String target){String id=nextRelationshipId(rels);Element r=rels.createElementNS(REL,"Relationship");r.setAttribute("Id",id);r.setAttribute("Type",type);r.setAttribute("Target",target);rels.getDocumentElement().appendChild(r);return id;}
    private static String nextRelationshipId(Document rels){int max=0;NodeList ns=rels.getElementsByTagNameNS(REL,"Relationship");for(int i=0;i<ns.getLength();i++){String id=((Element)ns.item(i)).getAttribute("Id");if(id.startsWith("rId"))try{max=Math.max(max,Integer.parseInt(id.substring(3)));}catch(NumberFormatException ignored){}}return "rId"+(max+1);}
    private static int nextDocPrId(Document d){int max=0;NodeList ns=d.getElementsByTagNameNS(WP,"docPr");for(int i=0;i<ns.getLength();i++)max=Math.max(max,intAttr((Element)ns.item(i),"id"));return max+1;}
    private static void ensureDefaultContentType(Map<String,byte[]>parts,String ext,String mime)throws IOException{Document d=OoxmlPackageSupport.parseXml(parts.get("[Content_Types].xml"));NodeList ns=d.getElementsByTagNameNS(CT,"Default");for(int i=0;i<ns.getLength();i++)if(ext.equalsIgnoreCase(((Element)ns.item(i)).getAttribute("Extension"))){parts.put("[Content_Types].xml",OoxmlPackageSupport.serialize(d));return;}Element e=d.createElementNS(CT,"Default");e.setAttribute("Extension",ext);e.setAttribute("ContentType",mime);d.getDocumentElement().appendChild(e);parts.put("[Content_Types].xml",OoxmlPackageSupport.serialize(d));}
    private static void ensureOverrideContentType(Map<String,byte[]>parts,String part,String mime)throws IOException{Document d=OoxmlPackageSupport.parseXml(parts.get("[Content_Types].xml"));NodeList ns=d.getElementsByTagNameNS(CT,"Override");for(int i=0;i<ns.getLength();i++)if(part.equals(((Element)ns.item(i)).getAttribute("PartName"))){((Element)ns.item(i)).setAttribute("ContentType",mime);parts.put("[Content_Types].xml",OoxmlPackageSupport.serialize(d));return;}Element e=d.createElementNS(CT,"Override");e.setAttribute("PartName",part);e.setAttribute("ContentType",mime);d.getDocumentElement().appendChild(e);parts.put("[Content_Types].xml",OoxmlPackageSupport.serialize(d));}
    private static String nextPart(Map<String,byte[]>parts,String prefix,String ext){int i=1;while(parts.containsKey(prefix+i+"."+ext))i++;return prefix+i+"."+ext;}
    private static String relativeWordTarget(String part){return part.startsWith("word/")?part.substring(5):part;}
    private static String relationshipTarget(Document rels,String rid){NodeList ns=rels.getElementsByTagNameNS(REL,"Relationship");for(int i=0;i<ns.getLength();i++){Element e=(Element)ns.item(i);if(rid.equals(e.getAttribute("Id")))return e.getAttribute("Target");}return "";}
    private static String normalizeTarget(String target){target=clean(target).replace('\\','/');while(target.startsWith("../"))target=target.substring(3);if(target.startsWith("/"))target=target.substring(1);return target.startsWith("word/")?target:"word/"+target;}
    private static Element locateParagraph(Document d,String locator){if(locator==null||!locator.matches("body/p:[1-9][0-9]*"))throw new IllegalArgumentException("unsafe paragraph locator: "+locator);int n=Integer.parseInt(locator.substring("body/p:".length()));List<Element>ps=bodyParagraphs(d);if(n>ps.size())throw new IllegalArgumentException("paragraph locator out of range");return ps.get(n-1);}
    private static List<Element> bodyParagraphs(Document d){Element body=first(d.getElementsByTagNameNS(W,"body"));ArrayList<Element>out=new ArrayList<>();if(body!=null)for(Node n=body.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e&&W.equals(e.getNamespaceURI())&&"p".equals(e.getLocalName()))out.add(e);return out;}
    private static int paragraphIndex(Document d,Element target){List<Element>ps=bodyParagraphs(d);for(int i=0;i<ps.size();i++)if(ps.get(i)==target)return i+1;return -1;}
    private static Element locateDrawing(Document d,String locator,String kind){if(locator==null||!locator.matches("body/p:[1-9][0-9]*/"+kind+":[1-9][0-9]*"))throw new IllegalArgumentException("unsafe drawing locator: "+locator);String[]p=locator.split("/");Element para=locateParagraph(d,p[0]+"/"+p[1]);int idx=Integer.parseInt(p[2].substring((kind+":").length()));NodeList drawings=para.getElementsByTagNameNS(W,"drawing");int count=0;for(int i=0;i<drawings.getLength();i++){Element dr=(Element)drawings.item(i);if("drawing-image".equals(kind)&&dr.getElementsByTagNameNS(A,"blip").getLength()==0)continue;if("chart".equals(kind)&&dr.getElementsByTagNameNS(C,"chart").getLength()==0)continue;if(++count==idx)return dr;}throw new IllegalArgumentException("drawing locator out of range");}
    private static Element locateChart(Document d,String locator){Element drawing=locateDrawing(d,locator,"chart");Element chart=first(drawing.getElementsByTagNameNS(C,"chart"));if(chart==null)throw new IllegalArgumentException("chart missing");return chart;}
    private static Element locateStandaloneShape(Document d,String locator){if(locator==null||!locator.matches("body/p:[1-9][0-9]*/drawing-shape:[1-9][0-9]*"))throw new IllegalArgumentException("unsafe shape locator: "+locator);String[] chunks=locator.split("/");Element p=locateParagraph(d,chunks[0]+"/"+chunks[1]);int target=Integer.parseInt(chunks[2].substring("drawing-shape:".length()));NodeList ns=p.getElementsByTagNameNS(WPS,"wsp");int n=0;for(int i=0;i<ns.getLength();i++){Element e=(Element)ns.item(i);if(hasAncestor(e,WPG,"wgp"))continue;if(++n==target)return e;}throw new IllegalArgumentException("shape locator out of range");}
    private static Element locateGroup(Document d,String locator){if(locator==null||!locator.matches("body/p:[1-9][0-9]*/drawing-group:[1-9][0-9]*"))throw new IllegalArgumentException("unsafe group locator: "+locator);String[] chunks=locator.split("/");Element p=locateParagraph(d,chunks[0]+"/"+chunks[1]);int target=Integer.parseInt(chunks[2].substring("drawing-group:".length()));NodeList ns=p.getElementsByTagNameNS(WPG,"wgp");if(target<1||target>ns.getLength())throw new IllegalArgumentException("group locator out of range");return (Element)ns.item(target-1);}
    private static Element nthStandaloneShape(Document d,int oneBased){if(oneBased<1)throw new IllegalArgumentException("shape index out of range");NodeList ns=d.getElementsByTagNameNS(WPS,"wsp");int n=0;for(int i=0;i<ns.getLength();i++){Element e=(Element)ns.item(i);if(hasAncestor(e,WPG,"wgp"))continue;if(++n==oneBased)return e;}throw new IllegalArgumentException("shape index out of range");}
    private static boolean hasAncestor(Node n,String ns,String local){for(Node p=n.getParentNode();p!=null;p=p.getParentNode())if(p instanceof Element e&&ns.equals(e.getNamespaceURI())&&local.equals(e.getLocalName()))return true;return false;}
    private static Element firstContainer(Element drawing){Element e=first(drawing.getElementsByTagNameNS(WP,"inline"));return e!=null?e:first(drawing.getElementsByTagNameNS(WP,"anchor"));}
    private static String wrap(Element container){if(container==null||!"anchor".equals(container.getLocalName()))return "inline";for(String x:List.of("Square","Tight","Through","TopAndBottom","None"))if(first(container.getElementsByTagNameNS(WP,"wrap"+x))!=null)return Character.toLowerCase(x.charAt(0))+x.substring(1);return "none";}
    private static long position(Element container,String local){if(container==null)return 0;Element p=first(container.getElementsByTagNameNS(WP,local));if(p==null)return 0;Element o=first(p.getElementsByTagNameNS(WP,"posOffset"));if(o==null)return 0;try{return Long.parseLong(o.getTextContent().strip());}catch(NumberFormatException e){return 0;}}
    private static String relative(Element container,String local){Element p=container==null?null:first(container.getElementsByTagNameNS(WP,local));return p==null?"":p.getAttribute("relativeFrom");}
    private static void setPosition(Document d,Element container,String local,String relative,long value){Element p=first(container.getElementsByTagNameNS(WP,local));if(p==null){p=d.createElementNS(WP,"wp:"+local);container.insertBefore(p,first(container.getElementsByTagNameNS(WP,"extent")));}if(!clean(relative).isBlank())p.setAttribute("relativeFrom",relative);Element o=first(p.getElementsByTagNameNS(WP,"posOffset"));if(o==null){o=d.createElementNS(WP,"wp:posOffset");p.appendChild(o);}o.setTextContent(Long.toString(value));}
    private static void replaceWrap(Document d,Element container,String wrap){for(String x:List.of("wrapSquare","wrapTight","wrapThrough","wrapTopAndBottom","wrapNone")){NodeList ns=container.getElementsByTagNameNS(WP,x);for(int i=ns.getLength()-1;i>=0;i--){Node n=ns.item(i);if(n.getParentNode()==container)container.removeChild(n);}}String local=switch(wrap){case"square"->"wrapSquare";case"tight"->"wrapTight";case"through"->"wrapThrough";case"topAndBottom"->"wrapTopAndBottom";default->"wrapNone";};Element e=d.createElementNS(WP,"wp:"+local);if(List.of("square","tight","through").contains(wrap))e.setAttribute("wrapText","bothSides");Element docPr=first(container.getElementsByTagNameNS(WP,"docPr"));if(docPr==null)container.appendChild(e);else container.insertBefore(e,docPr);}
    private static int countTargetUses(Document doc,Document rels,String target){int count=0;NodeList ns=doc.getElementsByTagNameNS(A,"blip");for(int i=0;i<ns.getLength();i++){String rid=((Element)ns.item(i)).getAttributeNS(R,"embed");if(target.equals(normalizeTarget(relationshipTarget(rels,rid))))count++;}return count;}
    private static int countChartTargetUses(Document doc,Document rels,String target){int count=0;NodeList ns=doc.getElementsByTagNameNS(C,"chart");for(int i=0;i<ns.getLength();i++){String rid=((Element)ns.item(i)).getAttributeNS(R,"id");if(target.equals(normalizeTarget(relationshipTarget(rels,rid))))count++;}return count;}
    private static void cloneChartRelationships(Map<String,byte[]>parts,String oldPart,String newPart){String oldRels=chartRelsPart(oldPart);if(!parts.containsKey(oldRels))return;parts.put(chartRelsPart(newPart),parts.get(oldRels).clone());}
    private static String chartRelsPart(String chartPart){int slash=chartPart.lastIndexOf('/');String dir=slash<0?"":chartPart.substring(0,slash+1);String base=slash<0?chartPart:chartPart.substring(slash+1);return dir+"_rels/"+base+".rels";}
    private static Document newDocument(String qname,String ns)throws IOException{return OoxmlPackageSupport.parseXml(("<?xml version=\"1.0\" encoding=\"UTF-8\"?><"+qname+" xmlns:c=\""+C+"\" xmlns:a=\""+A+"\" xmlns:r=\""+R+"\"/>").getBytes(StandardCharsets.UTF_8));}
    private static Element append(Document d,Element p,String ns,String q){Element e=d.createElementNS(ns,q);p.appendChild(e);return e;}
    private static Element appendText(Document d,Element p,String ns,String q,String text){Element e=append(d,p,ns,q);e.setTextContent(text);return e;}
    private static void val(Document d,Element p,String local,int value){Element e=append(d,p,C,"c:"+local);e.setAttribute("val",Integer.toString(value));}
    private static void appendColor(Document d,Element p,String q,String hex){Element f=d.createElementNS(A,q);Element rgb=d.createElementNS(A,"a:srgbClr");rgb.setAttribute("val",hex);f.appendChild(rgb);p.appendChild(f);}
    private static String colorValue(Element parent){if(parent==null)return"";Element rgb=first(parent.getElementsByTagNameNS(A,"srgbClr"));return rgb==null?"":rgb.getAttribute("val");}
    private static String textContent(Element p,String ns,String local){if(p==null)return"";NodeList n=p.getElementsByTagNameNS(ns,local);StringBuilder b=new StringBuilder();for(int i=0;i<n.getLength();i++)b.append(n.item(i).getTextContent());return b.toString();}
    private static Element first(NodeList n){return n==null||n.getLength()==0?null:(Element)n.item(0);}
    private static int intAttr(Element e,String a){try{return Integer.parseInt(e.getAttribute(a));}catch(NumberFormatException ex){return 0;}}
    private static long longAttr(Element e,String a){try{return Long.parseLong(e.getAttribute(a));}catch(NumberFormatException ex){return 0;}}
    private static String clean(String s){return Objects.requireNonNullElse(s,"").strip();}
    private static String color(String s,String fallback){String v=clean(s).toUpperCase(Locale.ROOT);if(v.isBlank())return fallback;if(!v.matches("[0-9A-F]{6}"))throw new IllegalArgumentException("color must be RRGGBB");return v;}
}
