package org.systemmaster.tools.pdf;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.Duration;import java.util.*;import java.util.concurrent.TimeUnit;
/** Bounded argv-only adapter for qualified local Poppler-style PDF tools; never uses a shell. */
public final class LocalPdfCliEnginePort implements PdfEnginePort {
 private final Path pdfinfo,pdftotext,pdftoppm;private final Duration timeout;
 public LocalPdfCliEnginePort(Path pdfinfo,Path pdftotext,Path pdftoppm,Duration timeout){this.pdfinfo=real(pdfinfo);this.pdftotext=real(pdftotext);this.pdftoppm=real(pdftoppm);this.timeout=Objects.requireNonNull(timeout);}
 public Identity identity(){return new Identity("LOCAL-PDF-CLI",version(pdfinfo),digestIdentity(),Set.of("pdf.inspect.metadata","pdf.extract.text","pdf.render.page","pdf.validate.base"),true);}
 public Result execute(Request r)throws Exception{Path dir=Files.createTempDirectory("systemmaster-pdf-");try{Path in=dir.resolve("input.pdf");Files.write(in,r.source());return switch(r.action()){case "pdf.inspect.metadata","pdf.validate.base"->new Result(null,Map.of("stdout",run(List.of(pdfinfo.toString(),in.toString()))),List.of());case "pdf.extract.text"->new Result(runBytes(List.of(pdftotext.toString(),"-layout",in.toString(),"-")),Map.of("format","text/plain"),List.of());case "pdf.render.page"->{String prefix=dir.resolve("page").toString();int page=Integer.parseInt(r.parameters().getOrDefault("page","1"));run(List.of(pdftoppm.toString(),"-f",Integer.toString(page),"-singlefile","-png",in.toString(),prefix));yield new Result(Files.readAllBytes(Path.of(prefix+".png")),Map.of("format","image/png","page",Integer.toString(page)),List.of());}default->throw new IllegalArgumentException("unsupported local PDF CLI action: "+r.action());};}finally{deleteTree(dir);}}
 private String version(Path p){try{return run(List.of(p.toString(),"-v")).lines().findFirst().orElse("UNKNOWN");}catch(Exception e){return "UNKNOWN";}}
 private String digestIdentity(){return PdfStructuralEngine.sha256((pdfinfo+"|"+pdftotext+"|"+pdftoppm).getBytes(StandardCharsets.UTF_8));}
 private String run(List<String> argv)throws Exception{return new String(runBytes(argv),StandardCharsets.UTF_8);}
 private byte[] runBytes(List<String> argv)throws Exception{Process p=new ProcessBuilder(argv).redirectErrorStream(true).start();ByteArrayOutputStream out=new ByteArrayOutputStream();Thread reader=Thread.ofVirtual().start(()->{try{p.getInputStream().transferTo(out);}catch(IOException ignored){}});boolean done=p.waitFor(timeout.toMillis(),TimeUnit.MILLISECONDS);if(!done){p.destroyForcibly();throw new IOException("PDF CLI timeout");}reader.join();if(out.size()>64*1024*1024)throw new IOException("PDF CLI output ceiling exceeded");if(p.exitValue()!=0)throw new IOException("PDF CLI failed exit="+p.exitValue()+" output="+out.toString(StandardCharsets.UTF_8).substring(0,Math.min(2048,out.size())));return out.toByteArray();}
 private static Path real(Path p){Objects.requireNonNull(p);if(!Files.isRegularFile(p)||!Files.isExecutable(p))throw new IllegalArgumentException("executable unavailable: "+p);return p.toAbsolutePath().normalize();}
 private static void deleteTree(Path root){if(root==null)return;try(var s=Files.walk(root)){s.sorted(Comparator.reverseOrder()).forEach(x->{try{Files.deleteIfExists(x);}catch(IOException ignored){}});}catch(IOException ignored){}}
}
