package org.systemmaster.tools.pdf;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.util.*;
import java.util.regex.*;

/** Conservative dependency-free PDF byte authority for creation, forensic inspection and safe routing decisions. */
public final class PdfStructuralEngine {
    public record Inspection(String sha256,String version,int indirectObjects,int pages,boolean eofPresent,boolean startXrefPresent,List<String> activeContent,List<String> features,List<String> literalText) {}
    private static final Pattern OBJ=Pattern.compile("(?m)(\\d+)\\s+(\\d+)\\s+obj\\b");
    private static final Pattern LITERAL=Pattern.compile("\\((?:\\\\.|[^\\)])*\\)");
    public Inspection inspect(byte[] bytes){Objects.requireNonNull(bytes,"bytes");String s=new String(bytes,StandardCharsets.ISO_8859_1);if(!s.startsWith("%PDF-"))throw new IllegalArgumentException("not a PDF header");String version=s.substring(5,Math.min(8,s.length())).trim();int objects=count(OBJ,s);int pages=count(Pattern.compile("/Type\\s*/Page(?!s)\\b"),s);List<String> active=new ArrayList<>();for(String token:List.of("/JavaScript","/JS","/Launch","/RichMedia","/EmbeddedFile","/XFA","/OpenAction","/AA"))if(s.contains(token))active.add(token.substring(1));List<String> features=new ArrayList<>();for(String token:List.of("/AcroForm","/Sig","/StructTreeRoot","/Metadata","/Encrypt","/ObjStm","/XRef","/EmbeddedFiles","/OCProperties"))if(s.contains(token))features.add(token.substring(1));List<String> text=new ArrayList<>();Matcher m=LITERAL.matcher(s);while(m.find()&&text.size()<500){String v=m.group();v=v.substring(1,v.length()-1).replace("\\(","(").replace("\\)",")");if(v.chars().anyMatch(Character::isLetterOrDigit))text.add(v);}return new Inspection(sha256(bytes),version,objects,pages,s.contains("%%EOF"),s.contains("startxref"),List.copyOf(active),List.copyOf(features),List.copyOf(text));}
    public byte[] createTextPdf(List<String> lines){Objects.requireNonNull(lines,"lines");StringBuilder content=new StringBuilder("BT /F1 12 Tf 72 720 Td ");boolean first=true;for(String line:lines){if(!first)content.append(" 0 -16 Td ");first=false;content.append('(').append(escape(line)).append(") Tj ");}content.append("ET");byte[] stream=content.toString().getBytes(StandardCharsets.ISO_8859_1);List<String> objs=List.of("<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>","<< /Length "+stream.length+" >>\nstream\n"+new String(stream,StandardCharsets.ISO_8859_1)+"\nendstream","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");ByteArrayOutputStream out=new ByteArrayOutputStream();try{out.write("%PDF-1.7\n%\u00e2\u00e3\u00cf\u00d3\n".getBytes(StandardCharsets.ISO_8859_1));List<Integer> offsets=new ArrayList<>();for(int i=0;i<objs.size();i++){offsets.add(out.size());out.write(((i+1)+" 0 obj\n"+objs.get(i)+"\nendobj\n").getBytes(StandardCharsets.ISO_8859_1));}int xref=out.size();out.write(("xref\n0 "+(objs.size()+1)+"\n0000000000 65535 f \n").getBytes(StandardCharsets.ISO_8859_1));for(int off:offsets)out.write(String.format(Locale.ROOT,"%010d 00000 n \n",off).getBytes(StandardCharsets.ISO_8859_1));out.write(("trailer\n<< /Size "+(objs.size()+1)+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF\n").getBytes(StandardCharsets.ISO_8859_1));return out.toByteArray();}catch(IOException e){throw new UncheckedIOException(e);}}
    public List<String> diagnose(byte[] bytes){Inspection i=inspect(bytes);ArrayList<String>d=new ArrayList<>();if(!i.eofPresent())d.add("ERROR:MISSING_EOF");if(!i.startXrefPresent())d.add("WARN:MISSING_STARTXREF");if(i.pages()==0)d.add("WARN:NO_PAGE_OBJECTS");if(!i.activeContent().isEmpty())d.add("WARN:ACTIVE_CONTENT:"+String.join(",",i.activeContent()));return List.copyOf(d);}
    public boolean absenceProof(byte[] bytes,List<String> forbiddenTokens){String s=new String(bytes,StandardCharsets.ISO_8859_1);return forbiddenTokens.stream().noneMatch(s::contains);}
    private static int count(Pattern p,String s){int n=0;Matcher m=p.matcher(s);while(m.find())n++;return n;}
    private static String escape(String s){return Objects.requireNonNullElse(s,"").replace("\\","\\\\").replace("(","\\(").replace(")","\\)").replace("\r"," ").replace("\n"," ");}
    public static String sha256(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
