package org.systemmaster.tools.pdf;

import java.util.*;

public final class PdfSemanticActions {
 public record Action(String action,String effect,String domain,String meaning){}
 private static final List<Action> ALL=List.of(
  new Action("pdf.inspect.bytes","READ","ARTIFACT","Hash/header/EOF/byte identity"),
  new Action("pdf.inspect.revisions","READ","REVISION","Parse startxref/Prev/xref revision chain"),
  new Action("pdf.inspect.objects","READ","OBJECT","Object graph inventory"),
  new Action("pdf.inspect.pages","READ","PAGE","Page tree/geometry/resources"),
  new Action("pdf.inspect.metadata","READ","METADATA","Info/XMP/profile metadata"),
  new Action("pdf.inspect.extensions","READ","PROFILE","Version/extensions/filters/features"),
  new Action("pdf.inspect.actions","READ","SECURITY","Actions/JS/external refs inert inventory"),
  new Action("pdf.inspect.forms","READ","FORMS","AcroForm/widgets/appearances/actions"),
  new Action("pdf.inspect.attachments","READ","COMPOUND","Embedded/associated/portfolio inventory"),
  new Action("pdf.inspect.signatures","READ","SIGNATURE","Signature/ByteRange/cert inventory"),
  new Action("pdf.inspect.tags","READ","ACCESSIBILITY","Tag/namespace/MCID/reading-order inventory"),
  new Action("pdf.render.page","VERIFY","RENDER","Render exact page/profile"),
  new Action("pdf.extract.text","READ","SEMANTIC","Text spans with page/geometry/source binding"),
  new Action("pdf.extract.structure","READ","SEMANTIC","Semantic/tagged structure projection"),
  new Action("pdf.extract.tables","READ","SEMANTIC","Table candidate extraction with evidence"),
  new Action("pdf.validate.base","VERIFY","CONFORMANCE","Base PDF/spec checks"),
  new Action("pdf.validate.pdfa","VERIFY","CONFORMANCE","Exact PDF/A flavor/ruleset"),
  new Action("pdf.validate.pdfua","VERIFY","ACCESSIBILITY","PDF/UA machine validation"),
  new Action("pdf.validate.wtpdf","VERIFY","ACCESSIBILITY","WTPDF reuse/accessibility validation"),
  new Action("pdf.validate.declarations","VERIFY","PROFILE","Declaration assertion/validated-claim check"),
  new Action("pdf.verify.signature.crypto","VERIFY","SIGNATURE","CMS/algorithm/ByteRange"),
  new Action("pdf.verify.signature.trust","VERIFY","SIGNATURE","Trust/revocation/time/LTV"),
  new Action("pdf.plan.repair","PLAN","REPAIR","Repair plan only"),
  new Action("pdf.repair.derivative","MUTATE","REPAIR","Create repair derivative"),
  new Action("pdf.mutate.object","MUTATE","OBJECT","Bounded low-level object mutation"),
  new Action("pdf.mutate.page.insert","MUTATE","PAGE","Insert page"),
  new Action("pdf.mutate.page.delete","MUTATE","PAGE","Delete page"),
  new Action("pdf.mutate.page.reorder","MUTATE","PAGE","Reorder page identity"),
  new Action("pdf.mutate.metadata","MUTATE","METADATA","Metadata update"),
  new Action("pdf.form.fill","MUTATE","FORMS","Fill value without implied flatten/action execution"),
  new Action("pdf.form.regenerate_appearance","MUTATE","FORMS","Explicit appearance regeneration"),
  new Action("pdf.form.flatten","DESTRUCTIVE","FORMS","Flatten derivative"),
  new Action("pdf.annotation.add","MUTATE","ANNOTATION","Add annotation"),
  new Action("pdf.annotation.edit","MUTATE","ANNOTATION","Edit annotation"),
  new Action("pdf.annotation.delete","DESTRUCTIVE","ANNOTATION","Delete annotation"),
  new Action("pdf.attachment.add","MUTATE","COMPOUND","Add governed child artifact"),
  new Action("pdf.attachment.remove","DESTRUCTIVE","COMPOUND","Remove child from derivative"),
  new Action("pdf.associated_file.bind","MUTATE","COMPOUND","Set Associated File relationship"),
  new Action("pdf.plan.redaction","PLAN","REDACTION","Select targets and proof policy"),
  new Action("pdf.redaction.apply","DESTRUCTIVE","REDACTION","Apply redaction to derivative"),
  new Action("pdf.sanitize.apply","DESTRUCTIVE","SANITIZATION","Remove selected hidden content"),
  new Action("pdf.verify.redaction","VERIFY","REDACTION","Multi-oracle absence proof"),
  new Action("pdf.verify.sanitization","VERIFY","SANITIZATION","Hidden-data absence proof"),
  new Action("pdf.sign.prepare","PLAN","SIGNATURE","Prepare signature/certification plan"),
  new Action("pdf.sign.apply","EXTERNAL_OR_NATIVE_WRITE","SIGNATURE","Signing through qualified signer"),
  new Action("pdf.signature.predict_impact","VERIFY","SIGNATURE","Predict mutation effect on existing signatures"),
  new Action("pdf.ai.workspace.bind_source","READ","AI_WORKSPACE","Bind exact source/version/permissions"),
  new Action("pdf.ai.answer","DERIVE","AI_WORKSPACE","Generate candidate claims"),
  new Action("pdf.ai.citation.bind","DERIVE","AI_WORKSPACE","Bind claim→source location"),
  new Action("pdf.ai.citation.verify","VERIFY","AI_WORKSPACE","Resolve exact source/version/location"),
  new Action("pdf.ai.workspace.reconcile","VERIFY","AI_WORKSPACE","Permission/version/freshness reconcile"),
  new Action("pdf.publish.html","DERIVE","PUBLICATION","Create HTML projection"),
  new Action("pdf.publish.markdown","DERIVE","PUBLICATION","Create Markdown projection"),
  new Action("pdf.publish.docx","DERIVE","PUBLICATION","Create DOCX candidate under DOCX authority"),
  new Action("pdf.publish.xlsx","DERIVE","PUBLICATION","Create XLSX candidate under Excel authority"),
  new Action("pdf.publish.image","DERIVE","PUBLICATION","Create rendered image derivative"),
  new Action("pdf.publish.ocr","DERIVE","PUBLICATION","Create OCR recognition derivative"),
  new Action("pdf.mobile.observe","VERIFY","MOBILE","Physical-device observation"),
  new Action("pdf.mobile.reconcile","VERIFY","MOBILE","External/mobile version reconciliation"),
  new Action("pdf.corpus.admit","MUTATE_METADATA","CORPUS","Admit rights/provenance fixture"),
  new Action("pdf.corpus.mutate","DERIVE","CORPUS","Generate mutation family member"),
  new Action("pdf.corpus.seal_oracle","MUTATE_METADATA","CORPUS","Seal expected result"),
  new Action("pdf.corpus.partition","MUTATE_METADATA","CORPUS","Assign immutable partition"),
  new Action("pdf.corpus.near_duplicate_check","VERIFY","CORPUS","Detect leakage across partitions"),
  new Action("pdf.diff.parsers","VERIFY","DIFFERENTIAL","Run parser differential"),
  new Action("pdf.diff.renderers","VERIFY","DIFFERENTIAL","Run render differential"),
  new Action("pdf.diff.text","VERIFY","DIFFERENTIAL","Run text/layout extraction differential"),
  new Action("pdf.diff.signatures","VERIFY","DIFFERENTIAL","Run signature result differential"),
  new Action("pdf.release","COMMIT","EVIDENCE","Exact candidate release"),
  new Action("pdf.rollback","RECOVERY","EVIDENCE","Restore/reconcile previous governed state")
);
 private PdfSemanticActions(){}
 public static List<Action> all(){return ALL;}
 public static Optional<Action> find(String id){return ALL.stream().filter(a->a.action().equals(id)).findFirst();}
}
