package org.systemmaster.continuity;
import static org.systemmaster.continuity.ResumeAuthorities.*; import java.nio.file.*;import java.time.*;import java.util.*;import java.util.concurrent.atomic.*;
public final class Gwp006QualificationTest{static int n;public static void main(String[]z)throws Exception{Path root=Files.createTempDirectory("gwp006-");MutableRecovery rec=new MutableRecovery(new RecoveryStanding("r1","w1",1,10,"CLAIMED"));MutablePlan plans=new MutablePlan(plan("p1","r1","pd1",List.of()));Fence fence=new Fence("r1","c1",7);Gate comp=new Gate(Decision.ALLOW),recon=new Gate(Decision.ALLOW),adm=new Gate(Decision.ALLOW);CountingRuntime runtime=new CountingRuntime();CountingClock clock=new CountingClock();Transitions tr=new Transitions();Verify ver=new Verify();ResumeCoordinator c=new ResumeCoordinator(root,rec,plans,fence,comp::forPlan,recon::forPlan,(r,rc)->adm.d,runtime,clock,tr,ver);
 var s1=c.startResume("r1","p1","c1",7);eq(ResumeCoordinator.Status.STARTED,s1.status());check(!s1.idempotentExisting());eq("w1",s1.attempt().workUnitId());eq("r1",s1.attempt().recoveryId());eq(1L,s1.attempt().attemptNo());eq(7L,s1.attempt().fenceEpoch());eq("cp1",s1.attempt().resumedFromCheckpointRef());eq("runtime-1",s1.attempt().runtimeIdentity());check(s1.attempt().attemptId().startsWith("attempt-"));eq(1,tr.started.get());
 var s1b=c.startResume("r1","p1","c1",7);check(s1b.idempotentExisting());eq(s1.attempt().attemptId(),s1b.attempt().attemptId());
 plans.p=plan("p1","r1","pd1",List.of("BLOCK"));eq("PLAN_NOT_CURRENT_OR_READY",c.startResume("r1","p1","c1",7).blocker());plans.p=plan("p1","r1","pd1",List.of());
 rec.s=new RecoveryStanding("r1","w1",1,10,"BLOCKED");eq("RECOVERY_STATE_NOT_RESUMABLE",c.startResume("r1","p1","c1",7).blocker());rec.s=new RecoveryStanding("r1","w1",1,10,"CLAIMED");
 comp.d=Decision.DENY;eq("COMPATIBILITY_DENIED",c.startResume("r1","p1","c1",7).blocker());comp.d=Decision.UNKNOWN;eq("COMPATIBILITY_UNKNOWN",c.startResume("r1","p1","c1",7).blocker());comp.d=Decision.ALLOW;
 recon.d=Decision.DENY;eq("RECONCILIATION_INCOMPLETE",c.startResume("r1","p1","c1",7).blocker());recon.d=Decision.UNKNOWN;eq("RECONCILIATION_UNKNOWN",c.startResume("r1","p1","c1",7).blocker());recon.d=Decision.ALLOW;
 adm.d=Decision.DENY;eq("RESOURCE_DENIED",c.startResume("r1","p1","c1",7).blocker());adm.d=Decision.UNKNOWN;eq("RESOURCE_UNKNOWN",c.startResume("r1","p1","c1",7).blocker());adm.d=Decision.ALLOW;
 throwsType(()->c.startResume("r1","p1","wrong",7),IllegalStateException.class);
 rec.s=new RecoveryStanding("r1","w1",2,11,"CLAIMED");plans.p=plan("p1","r1","pd2",List.of());var s2=c.startResume("r1","p1","c1",7);eq(2L,s2.attempt().attemptNo());check(!s2.attempt().attemptId().equals(s1.attempt().attemptId()));
 String result="chosen-A", rd=ResumeStore.sha(result);RecordedDecision d=new RecordedDecision("w1",1,"ROUTE",ResumeStore.sha("input"),result,Instant.parse("2026-01-01T00:00:00Z"),"provider-x",List.of("ev1","ev2"),rd);eq(d,c.recordDecision(d));eq(d,c.recordDecision(d));eq(result,c.replayDecision("w1",1,d.inputDigest()));eq(List.of("ev1","ev2"),c.getRecordedDecision("w1",1).orElseThrow().evidenceRefs());
 int cc=clock.calls.get(),rc=runtime.calls.get();eq(result,c.replayDecision("w1",1,d.inputDigest()));eq(cc,clock.calls.get());eq(rc,runtime.calls.get());
 throwsType(()->c.replayDecision("w1",2,d.inputDigest()),ResumeCoordinator.ReplayBlockedException.class);throwsType(()->c.replayDecision("w1",1,ResumeStore.sha("other")),ResumeCoordinator.ReplayBlockedException.class);
 RecordedDecision bad=new RecordedDecision("w1",2,"RANDOM",ResumeStore.sha("i2"),"x",Instant.parse("2026-01-01T00:00:01Z"),null,List.of(),"bad");throwsType(()->c.recordDecision(bad),ResumeCoordinator.ReplayConflictException.class);
 RecordedDecision d2=new RecordedDecision("w1",2,"RANDOM",ResumeStore.sha("i2"),"42",Instant.parse("2026-01-01T00:00:01Z"),null,List.of("e2"),ResumeStore.sha("42"));c.recordDecision(d2);RecordedDecision conflict=new RecordedDecision("w1",2,"RANDOM",ResumeStore.sha("changed"),"42",d2.logicalTime(),null,List.of("e2"),d2.resultDigest());throwsType(()->c.recordDecision(conflict),ResumeCoordinator.ReplayConflictException.class);
 ResumeCoordinator restarted=new ResumeCoordinator(root,rec,plans,fence,comp::forPlan,recon::forPlan,(r,rcx)->adm.d,runtime,clock,tr,ver);eq(result,restarted.replayDecision("w1",1,d.inputDigest()));eq(s2.attempt().attemptId(),restarted.startResume("r1","p1","c1",7).attempt().attemptId());check(restarted.getAttempt(s1.attempt().attemptId()).isPresent());
 ver.d=Decision.UNKNOWN;var o1=restarted.recordResumeOutcome(s2.attempt().attemptId(),7,"RESUMED",List.of("v1"),1);eq("VERIFICATION_PENDING",o1.state());check(!o1.recovered());
 ver.d=Decision.ALLOW;ver.critical=true;var o2=restarted.recordResumeOutcome(s2.attempt().attemptId(),7,"RESUMED",List.of("v2"),2);eq("VERIFICATION_PENDING",o2.state());check(!o2.recovered());ver.critical=false;var o3=restarted.recordResumeOutcome(s2.attempt().attemptId(),7,"RESUMED",List.of("v3"),3);eq("RECOVERED",o3.state());check(o3.recovered());eq(1,tr.recovered.get());
 var fail=restarted.recordResumeOutcome(s2.attempt().attemptId(),7,"FAILED",List.of("err"),4);eq("RECOVERY_FAILED",fail.state());eq(1,tr.failed.get());
 throwsType(()->restarted.recordResumeOutcome(s2.attempt().attemptId(),8,"RESUMED",List.of(),5),ResumeCoordinator.ResumeConflictException.class);fence.epoch=8;throwsType(()->restarted.recordResumeOutcome(s2.attempt().attemptId(),7,"RESUMED",List.of(),5),IllegalStateException.class);fence.epoch=7;
 for(int i=3;i<=102;i++){String r="R"+i;RecordedDecision x=new RecordedDecision("w1",i,"SOAK",ResumeStore.sha("I"+i),r,Instant.parse("2026-01-01T00:00:00Z").plusSeconds(i),null,List.of(),ResumeStore.sha(r));restarted.recordDecision(x);}eq("R102",restarted.replayDecision("w1",102,ResumeStore.sha("I102")));
 Path corrupt=Files.createTempDirectory("gwp006-corrupt-");Files.writeString(corrupt.resolve("resume.log"),"broken\n");Files.createFile(corrupt.resolve("resume.lock"));throwsType(()->new ResumeStore(corrupt).snapshot(),ResumeStore.StoreException.class);
 if(n!=50)throw new AssertionError("TEST_COUNT expected=50 actual="+n);System.out.println("PASS G-WP-006 tests=50 requirements=3");}
 static RecoveryPlan plan(String id,String r,String pd,List<String>b){return new RecoveryPlan(id,1,r,"cl",RecoveryClassification.RecoveryClass.RESUME,"cp1",List.of(),"compat","auth","standard",List.of("START_RESUME","VERIFY"),List.of("healthy"),b,"input",pd,Instant.parse("2026-01-01T00:00:00Z"));}
 static void eq(Object a,Object b){n++;if(!Objects.equals(a,b))throw new AssertionError("expected="+a+" actual="+b+" n="+n);}static void check(boolean v){n++;if(!v)throw new AssertionError("n="+n);}static void throwsType(Runnable r,Class<?extends Throwable>t){n++;try{r.run();throw new AssertionError("expected "+t.getSimpleName());}catch(Throwable x){if(x instanceof AssertionError)throw(AssertionError)x;if(!t.isInstance(x))throw new AssertionError("expected="+t+" got="+x,x);}}
 static final class MutableRecovery implements RecoveryStandingAuthority{RecoveryStanding s;MutableRecovery(RecoveryStanding s){this.s=s;}public RecoveryStanding current(String r){return s;}}static final class MutablePlan implements PlanAuthority{RecoveryPlan p;MutablePlan(RecoveryPlan p){this.p=p;}public RecoveryPlan currentPlan(String r){return p;}}static final class Fence implements FenceAuthority{String r,c;long epoch;Fence(String r,String c,long e){this.r=r;this.c=c;epoch=e;}public void assertClaim(String rr,String cc,long e){if(!r.equals(rr)||!c.equals(cc)||epoch!=e)throw new IllegalStateException("stale claim");}public void assertFence(String rr,long e){if(!r.equals(rr)||epoch!=e)throw new IllegalStateException("stale fence");}}static final class Gate{Decision d;Gate(Decision d){this.d=d;}Decision forPlan(RecoveryPlan p){return d;}}static final class CountingRuntime implements RuntimeIdentityAuthority{AtomicInteger calls=new AtomicInteger();public String runtimeIdentity(RecoveryPlan p){return"runtime-"+calls.incrementAndGet();}}static final class CountingClock implements AttemptClock{AtomicInteger calls=new AtomicInteger();public Instant now(){return Instant.parse("2026-09-08T00:00:00Z").plusSeconds(calls.getAndIncrement());}}static final class Transitions implements RecoveryTransitionAuthority{AtomicInteger started=new AtomicInteger(),pending=new AtomicInteger(),failed=new AtomicInteger(),recovered=new AtomicInteger();public void resumeStarted(String r,long v,String a){started.incrementAndGet();}public void verificationPending(String r,String a){pending.incrementAndGet();}public void recoveryFailed(String r,String a,String e){failed.incrementAndGet();}public void markRecovered(String r,String a,List<String>e){recovered.incrementAndGet();}}static final class Verify implements VerificationAuthority{Decision d=Decision.ALLOW;boolean critical;public Decision verify(String r,String a,List<String>e){return d;}public boolean unresolvedCriticalEffects(String r){return critical;}}
}
